-- Minimal SandAdmin database surface required by isolated SandIAM acceptance.
-- This fixture is test-only and must never be shipped as SandIAM-owned schema.
CREATE TABLE sand_system_menu (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id bigint NOT NULL DEFAULT 0,
    name varchar(128) NOT NULL,
    code varchar(128) NOT NULL DEFAULT '',
    slug varchar(128) NOT NULL DEFAULT '',
    type smallint NOT NULL,
    path varchar(255) NOT NULL DEFAULT '',
    component varchar(255) NOT NULL DEFAULT '',
    icon varchar(128) NOT NULL DEFAULT '',
    sort integer NOT NULL DEFAULT 0,
    is_hidden smallint NOT NULL DEFAULT 2,
    status smallint NOT NULL DEFAULT 1,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sand_system_role_menu (
    role_id bigint NOT NULL,
    menu_id bigint NOT NULL,
    PRIMARY KEY (role_id, menu_id)
);

CREATE TYPE tablestruct AS (
    fields_key_name varchar(100),
    fields_name varchar(200),
    fields_type varchar(20),
    fields_length bigint,
    fields_not_null varchar(10),
    fields_default varchar(500),
    fields_comment varchar(1000)
);

CREATE FUNCTION pgsql_type(a_type varchar) RETURNS varchar LANGUAGE plpgsql AS $$
BEGIN
    RETURN CASE a_type
        WHEN 'int8' THEN 'bigint'
        WHEN 'int4' THEN 'integer'
        WHEN 'int2' THEN 'smallint'
        WHEN 'bpchar' THEN 'char'
        ELSE a_type
    END;
END
$$;

CREATE FUNCTION table_msg(a_schema_name varchar, a_table_name varchar) RETURNS SETOF tablestruct LANGUAGE plpgsql AS $$
DECLARE
    v_ret tablestruct;
    v_record record;
BEGIN
    FOR v_record IN
        SELECT
            constraint_info.constraint_name AS fields_key_name,
            attribute.attname AS fields_name,
            pgsql_type(type_record.typname::varchar) AS fields_type,
            NULLIF(attribute.atttypmod - 4, -5)::bigint AS fields_length,
            CASE WHEN attribute.attnotnull THEN 'not null' ELSE '' END AS fields_not_null,
            pg_get_expr(default_record.adbin, default_record.adrelid)::varchar AS fields_default,
            description.description::varchar AS fields_comment
        FROM pg_attribute attribute
        JOIN pg_class class_record ON class_record.oid = attribute.attrelid
        JOIN pg_namespace namespace_record ON namespace_record.oid = class_record.relnamespace
        JOIN pg_type type_record ON type_record.oid = attribute.atttypid
        LEFT JOIN pg_attrdef default_record ON default_record.adrelid = class_record.oid AND default_record.adnum = attribute.attnum
        LEFT JOIN pg_description description ON description.objoid = class_record.oid AND description.objsubid = attribute.attnum
        LEFT JOIN LATERAL (
            SELECT key_usage.constraint_name
            FROM information_schema.key_column_usage key_usage
            WHERE key_usage.table_schema = a_schema_name
              AND key_usage.table_name = a_table_name
              AND key_usage.column_name = attribute.attname
            ORDER BY key_usage.constraint_name
            LIMIT 1
        ) constraint_info ON true
        WHERE namespace_record.nspname = a_schema_name
          AND class_record.relname = a_table_name
          AND attribute.attnum > 0
          AND NOT attribute.attisdropped
        ORDER BY attribute.attnum
    LOOP
        v_ret.fields_key_name := COALESCE(v_record.fields_key_name, '');
        v_ret.fields_name := v_record.fields_name;
        v_ret.fields_type := v_record.fields_type;
        v_ret.fields_length := CASE WHEN v_record.fields_length > 0 THEN v_record.fields_length ELSE NULL END;
        v_ret.fields_not_null := v_record.fields_not_null;
        v_ret.fields_default := v_record.fields_default;
        v_ret.fields_comment := v_record.fields_comment;
        RETURN NEXT v_ret;
    END LOOP;
END
$$;

CREATE FUNCTION table_msg(a_table_name varchar) RETURNS SETOF tablestruct LANGUAGE sql AS $$
    SELECT * FROM table_msg('public', a_table_name)
$$;
