CREATE TABLE standalone_work_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL,
    owner_identity_id bigint NOT NULL,
    state varchar(16) NOT NULL DEFAULT 'open' CHECK (state IN ('open', 'closed')),
    version integer NOT NULL DEFAULT 1 CHECK (version > 0),
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX standalone_work_item_scope_idx
    ON standalone_work_item (organization_id, owner_identity_id);

CREATE TABLE standalone_business_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action varchar(64) NOT NULL,
    outcome varchar(16) NOT NULL CHECK (outcome IN ('allowed', 'denied')),
    reason_code varchar(96) NULL,
    work_item_id bigint NULL,
    organization_ref varchar(32) NOT NULL,
    owner_ref varchar(32) NOT NULL,
    actor_ref varchar(32) NOT NULL,
    request_id varchar(96) NOT NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX standalone_business_audit_request_idx
    ON standalone_business_audit (request_id);
