-- IAM-T03-005 BEGIN
-- OAuth 2.0 / OpenID Connect provider records.  All user and client records
-- are application scoped; signing-key history is issuer scoped by design.
BEGIN;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uk_sand_iam_auth_session_id_application_identity') THEN
        ALTER TABLE sand_iam_auth_session ADD CONSTRAINT uk_sand_iam_auth_session_id_application_identity UNIQUE (id, application_id, identity_id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS sand_iam_oauth_client (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL REFERENCES sand_iam_application(id) ON DELETE RESTRICT,
    code varchar(128) NOT NULL,
    name varchar(128) NOT NULL,
    client_type varchar(16) NOT NULL CHECK (client_type IN ('public', 'confidential')),
    secret_hash varchar(255) NULL,
    secret_version varchar(32) NULL,
    redirect_uris jsonb NOT NULL DEFAULT '[]'::jsonb,
    post_logout_redirect_uris jsonb NOT NULL DEFAULT '[]'::jsonb,
    allowed_scopes jsonb NOT NULL DEFAULT '["openid","profile","email"]'::jsonb,
    allowed_audiences jsonb NOT NULL DEFAULT '[]'::jsonb,
    default_audience varchar(255) NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    -- client_id is presented at issuer-wide endpoints, so it cannot be scoped
    -- only to an application even though all ownership FKs remain scoped.
    CONSTRAINT uk_sand_iam_oauth_client_code UNIQUE (code),
    CONSTRAINT uk_sand_iam_oauth_client_id_application UNIQUE (id, application_id),
    CONSTRAINT ck_sand_iam_oauth_client_secret CHECK ((client_type = 'public' AND secret_hash IS NULL AND secret_version IS NULL) OR (client_type = 'confidential' AND secret_hash IS NOT NULL AND secret_version IS NOT NULL))
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_oauth_client_application_active ON sand_iam_oauth_client (application_id, status);

CREATE TABLE IF NOT EXISTS sand_iam_oauth_consent (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL REFERENCES sand_iam_application(id) ON DELETE RESTRICT,
    client_id bigint NOT NULL,
    identity_id bigint NOT NULL,
    scope varchar(1000) NOT NULL,
    granted_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_time timestamp(0) without time zone NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_oauth_consent_scope UNIQUE (application_id, client_id, identity_id),
    CONSTRAINT fk_sand_iam_oauth_consent_client_scope FOREIGN KEY (client_id, application_id) REFERENCES sand_iam_oauth_client(id, application_id) ON DELETE RESTRICT,
    CONSTRAINT fk_sand_iam_oauth_consent_identity_scope FOREIGN KEY (identity_id, application_id) REFERENCES sand_iam_identity(id, application_id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_oauth_consent_identity_active ON sand_iam_oauth_consent (application_id, identity_id, status);

-- Browser authorization requests are server-side, one-time records.  The
-- browser only carries an opaque request handle and a same-site CSRF proof;
-- state, nonce and PKCE data are encrypted inside this record.
CREATE TABLE IF NOT EXISTS sand_iam_oauth_authorization_request (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL REFERENCES sand_iam_application(id) ON DELETE RESTRICT,
    client_id bigint NOT NULL,
    identity_id bigint NULL,
    auth_session_id bigint NULL,
    -- session and identity are intentionally bound only by POST interaction/session.
    request_hash char(64) NOT NULL,
    csrf_hash char(64) NOT NULL,
    encrypted_payload text NOT NULL,
    encryption_version varchar(32) NOT NULL,
    expire_time timestamp(0) without time zone NOT NULL,
    consumed_time timestamp(0) without time zone NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_oauth_authorization_request_hash UNIQUE (request_hash),
    CONSTRAINT ck_sand_iam_oauth_authorization_request_binding CHECK ((identity_id IS NULL AND auth_session_id IS NULL) OR (identity_id IS NOT NULL AND auth_session_id IS NOT NULL)),
    CONSTRAINT fk_sand_iam_oauth_authorization_request_client_scope FOREIGN KEY (client_id, application_id) REFERENCES sand_iam_oauth_client(id, application_id) ON DELETE RESTRICT,
    CONSTRAINT fk_sand_iam_oauth_authorization_request_identity_scope FOREIGN KEY (identity_id, application_id) REFERENCES sand_iam_identity(id, application_id) ON DELETE RESTRICT,
    CONSTRAINT fk_sand_iam_oauth_authorization_request_session_scope FOREIGN KEY (auth_session_id, application_id, identity_id) REFERENCES sand_iam_auth_session(id, application_id, identity_id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_oauth_authorization_request_active ON sand_iam_oauth_authorization_request (application_id, client_id, identity_id, status, expire_time);

CREATE TABLE IF NOT EXISTS sand_iam_oauth_grant (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL REFERENCES sand_iam_application(id) ON DELETE RESTRICT,
    client_id bigint NOT NULL,
    identity_id bigint NULL,
    auth_session_id bigint NULL,
    grant_type varchar(24) NOT NULL CHECK (grant_type IN ('authorization_code', 'client_credentials')),
    scope varchar(1000) NOT NULL,
    auth_time timestamp(0) without time zone NULL,
    revoked_time timestamp(0) without time zone NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_oauth_grant_id_application UNIQUE (id, application_id),
    CONSTRAINT uk_sand_iam_oauth_grant_id_application_client UNIQUE (id, application_id, client_id),
    CONSTRAINT ck_sand_iam_oauth_grant_subject CHECK ((grant_type = 'authorization_code' AND identity_id IS NOT NULL AND auth_session_id IS NOT NULL AND auth_time IS NOT NULL) OR (grant_type = 'client_credentials' AND identity_id IS NULL AND auth_session_id IS NULL AND auth_time IS NULL)),
    CONSTRAINT fk_sand_iam_oauth_grant_client_scope FOREIGN KEY (client_id, application_id) REFERENCES sand_iam_oauth_client(id, application_id) ON DELETE RESTRICT,
    CONSTRAINT fk_sand_iam_oauth_grant_identity_scope FOREIGN KEY (identity_id, application_id) REFERENCES sand_iam_identity(id, application_id) ON DELETE RESTRICT,
    CONSTRAINT fk_sand_iam_oauth_grant_session_scope FOREIGN KEY (auth_session_id, application_id, identity_id) REFERENCES sand_iam_auth_session(id, application_id, identity_id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_oauth_grant_active ON sand_iam_oauth_grant (application_id, client_id, identity_id, status);

CREATE TABLE IF NOT EXISTS sand_iam_authorization_code (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL REFERENCES sand_iam_application(id) ON DELETE RESTRICT,
    client_id bigint NOT NULL,
    identity_id bigint NOT NULL,
    auth_session_id bigint NOT NULL,
    code_hash char(64) NOT NULL,
    redirect_uri varchar(2048) NOT NULL,
    scope varchar(1000) NOT NULL,
    encrypted_nonce text NULL,
    nonce_encryption_version varchar(32) NULL,
    nonce_hash char(64) NULL,
    code_challenge varchar(128) NOT NULL,
    code_challenge_method varchar(8) NOT NULL CHECK (code_challenge_method = 'S256'),
    auth_time timestamp(0) without time zone NOT NULL,
    expire_time timestamp(0) without time zone NOT NULL,
    consumed_time timestamp(0) without time zone NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_authorization_code_hash UNIQUE (code_hash),
    CONSTRAINT fk_sand_iam_authorization_code_client_scope FOREIGN KEY (client_id, application_id) REFERENCES sand_iam_oauth_client(id, application_id) ON DELETE RESTRICT,
    CONSTRAINT fk_sand_iam_authorization_code_identity_scope FOREIGN KEY (identity_id, application_id) REFERENCES sand_iam_identity(id, application_id) ON DELETE RESTRICT,
    CONSTRAINT fk_sand_iam_authorization_code_session_scope FOREIGN KEY (auth_session_id, application_id, identity_id) REFERENCES sand_iam_auth_session(id, application_id, identity_id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_authorization_code_active ON sand_iam_authorization_code (application_id, client_id, status, expire_time);

CREATE TABLE IF NOT EXISTS sand_iam_oauth_token (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL REFERENCES sand_iam_application(id) ON DELETE RESTRICT,
    client_id bigint NOT NULL,
    grant_id bigint NOT NULL,
    identity_id bigint NULL,
    token_type varchar(16) NOT NULL CHECK (token_type IN ('access', 'refresh', 'id')),
    token_hash char(64) NOT NULL,
    token_id varchar(96) NOT NULL,
    scope varchar(1000) NOT NULL,
    expire_time timestamp(0) without time zone NOT NULL,
    used_time timestamp(0) without time zone NULL,
    revoked_time timestamp(0) without time zone NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_oauth_token_hash UNIQUE (token_hash),
    CONSTRAINT uk_sand_iam_oauth_token_id UNIQUE (token_id),
    CONSTRAINT fk_sand_iam_oauth_token_client_scope FOREIGN KEY (client_id, application_id) REFERENCES sand_iam_oauth_client(id, application_id) ON DELETE RESTRICT,
    CONSTRAINT fk_sand_iam_oauth_token_grant_scope FOREIGN KEY (grant_id, application_id, client_id) REFERENCES sand_iam_oauth_grant(id, application_id, client_id) ON DELETE RESTRICT,
    CONSTRAINT fk_sand_iam_oauth_token_identity_scope FOREIGN KEY (identity_id, application_id) REFERENCES sand_iam_identity(id, application_id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_oauth_token_grant_active ON sand_iam_oauth_token (application_id, grant_id, token_type, status, expire_time);

CREATE TABLE IF NOT EXISTS sand_iam_oidc_signing_key (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kid varchar(128) NOT NULL,
    public_jwk jsonb NOT NULL,
    -- Private material is write-only. Imported verification keys intentionally
    -- have no private material, so the two envelope fields stay nullable as a pair.
    encrypted_private_key text NULL,
    encryption_version varchar(32) NULL,
    algorithm varchar(16) NOT NULL DEFAULT 'RS256',
    state varchar(16) NOT NULL CHECK (state IN ('active', 'verify_only', 'retired')),
    not_before_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    retire_time timestamp(0) without time zone NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sand_iam_oidc_signing_key_kid UNIQUE (kid)
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_oidc_signing_key_publish ON sand_iam_oidc_signing_key (state, retire_time);
COMMENT ON COLUMN sand_iam_oidc_signing_key.encrypted_private_key IS 'Write-only versioned private-key envelope; NULL only when no private signing material is stored.';
COMMENT ON COLUMN sand_iam_oidc_signing_key.encryption_version IS 'Key-encryption version for encrypted_private_key; NULL when no private signing material is stored.';

COMMIT;
-- IAM-T03-005 END
