-- IAM-T04 browser handoff.  Plaintext codes never reach durable storage.

ALTER TABLE sand_iam_federation_transaction
    ADD COLUMN IF NOT EXISTS handoff_return_uri varchar(2048),
    ADD COLUMN IF NOT EXISTS handoff_state varchar(2048),
    ADD COLUMN IF NOT EXISTS handoff_code_challenge varchar(64),
    ADD COLUMN IF NOT EXISTS link_identity_id bigint NULL,
    ADD COLUMN IF NOT EXISTS link_session_id bigint NULL;

ALTER TABLE sand_iam_auth_session
    ADD COLUMN IF NOT EXISTS step_up_time timestamp(0) without time zone NULL,
    ADD COLUMN IF NOT EXISTS step_up_method varchar(16) NULL;

CREATE TABLE IF NOT EXISTS sand_iam_federation_handoff (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL,
    application_id bigint NOT NULL,
    identity_provider_id bigint NOT NULL,
    identity_binding_id bigint NOT NULL,
    provider_config_version bigint NOT NULL,
    code_hash char(64) NOT NULL,
    return_uri varchar(2048) NOT NULL,
    code_challenge varchar(64) NOT NULL,
    expire_time timestamp(0) without time zone NOT NULL,
    consumed_time timestamp(0) without time zone NULL,
    status smallint NOT NULL DEFAULT 1,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_federation_handoff_code_hash UNIQUE (code_hash),
    CONSTRAINT ck_sand_iam_federation_handoff_status CHECK (status IN (1, 2)),
    CONSTRAINT fk_sand_iam_federation_handoff_application FOREIGN KEY (application_id) REFERENCES sand_iam_application(id),
    CONSTRAINT fk_sand_iam_federation_handoff_provider FOREIGN KEY (identity_provider_id) REFERENCES sand_iam_identity_provider(id),
    CONSTRAINT fk_sand_iam_federation_handoff_binding FOREIGN KEY (identity_binding_id) REFERENCES sand_iam_identity_binding(id)
);

CREATE INDEX IF NOT EXISTS idx_sand_iam_federation_handoff_expire ON sand_iam_federation_handoff (expire_time);
CREATE INDEX IF NOT EXISTS idx_sand_iam_federation_handoff_binding ON sand_iam_federation_handoff (identity_binding_id, status);
