CREATE UNIQUE INDEX IF NOT EXISTS uk_sand_iam_resource_id_application
    ON sand_iam_resource (id, application_id);

CREATE TABLE IF NOT EXISTS sand_iam_api_resource (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL,
    resource_id bigint NOT NULL,
    code varchar(96) NOT NULL,
    name varchar(128) NOT NULL,
    action varchar(96) NOT NULL,
    operation varchar(16) NOT NULL,
    api_version varchar(32) NOT NULL DEFAULT 'v1',
    audience varchar(128) NOT NULL,
    required_scope varchar(96) NULL,
    risk_level varchar(16) NOT NULL DEFAULT 'medium',
    description varchar(500) NULL,
    status smallint NOT NULL DEFAULT 1,
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT fk_sand_iam_api_resource_application
        FOREIGN KEY (application_id) REFERENCES sand_iam_application(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sand_iam_api_resource_resource
        FOREIGN KEY (resource_id, application_id) REFERENCES sand_iam_resource(id, application_id) ON DELETE RESTRICT,
    CONSTRAINT ck_sand_iam_api_resource_operation
        CHECK (operation IN ('list', 'read', 'create', 'update', 'delete', 'export', 'batch')),
    CONSTRAINT ck_sand_iam_api_resource_risk
        CHECK (risk_level IN ('low', 'medium', 'high', 'critical')),
    CONSTRAINT ck_sand_iam_api_resource_status
        CHECK (status IN (1, 2)),
    CONSTRAINT uk_sand_iam_api_resource_code_version
        UNIQUE (application_id, code, api_version),
    CONSTRAINT uk_sand_iam_api_resource_id_application
        UNIQUE (id, application_id)
);

CREATE INDEX IF NOT EXISTS idx_sand_iam_api_resource_resource
    ON sand_iam_api_resource (application_id, resource_id, status);

CREATE TABLE IF NOT EXISTS sand_iam_api_route_binding (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL,
    api_resource_id bigint NOT NULL,
    http_method varchar(8) NOT NULL,
    route_template varchar(255) NOT NULL,
    route_fingerprint char(64) NOT NULL,
    source varchar(16) NOT NULL DEFAULT 'manual',
    last_seen_time timestamp(0) without time zone NULL,
    status smallint NOT NULL DEFAULT 1,
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT fk_sand_iam_api_route_application
        FOREIGN KEY (application_id) REFERENCES sand_iam_application(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sand_iam_api_route_resource
        FOREIGN KEY (api_resource_id, application_id) REFERENCES sand_iam_api_resource(id, application_id) ON DELETE RESTRICT,
    CONSTRAINT ck_sand_iam_api_route_method
        CHECK (http_method IN ('GET', 'POST', 'PUT', 'PATCH', 'DELETE')),
    CONSTRAINT ck_sand_iam_api_route_source
        CHECK (source IN ('manual', 'openapi', 'route_scan')),
    CONSTRAINT ck_sand_iam_api_route_status
        CHECK (status IN (1, 2)),
    CONSTRAINT uk_sand_iam_api_route_method_template
        UNIQUE (application_id, http_method, route_template)
);

CREATE INDEX IF NOT EXISTS idx_sand_iam_api_route_resource
    ON sand_iam_api_route_binding (application_id, api_resource_id, status);
