CREATE TABLE IF NOT EXISTS sand_iam_admin_application_grant (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id bigint NOT NULL,
    application_id bigint NOT NULL,
    status smallint NOT NULL DEFAULT 1,
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT fk_sand_iam_admin_application_grant_application
        FOREIGN KEY (application_id) REFERENCES sand_iam_application(id) ON DELETE RESTRICT,
    CONSTRAINT ck_sand_iam_admin_application_grant_status
        CHECK (status IN (1, 2)),
    CONSTRAINT uk_sand_iam_admin_application_grant_admin_app
        UNIQUE (admin_user_id, application_id)
);

CREATE INDEX IF NOT EXISTS idx_sand_iam_admin_application_grant_app
    ON sand_iam_admin_application_grant (application_id, status);
