CREATE TABLE IF NOT EXISTS sand_iam_webhook_endpoint (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL,
    code varchar(64) NOT NULL,
    name varchar(128) NOT NULL,
    url varchar(500) NOT NULL,
    encrypted_secret text NOT NULL,
    secret_version integer NOT NULL DEFAULT 1,
    event_types jsonb NOT NULL DEFAULT '[]'::jsonb,
    timeout_seconds smallint NOT NULL DEFAULT 10,
    max_attempts smallint NOT NULL DEFAULT 5,
    status smallint NOT NULL DEFAULT 1,
    disabled_time timestamp(0) without time zone NULL,
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT fk_sand_iam_webhook_endpoint_application
        FOREIGN KEY (application_id) REFERENCES sand_iam_application(id) ON DELETE RESTRICT,
    CONSTRAINT ck_sand_iam_webhook_endpoint_event_types
        CHECK (jsonb_typeof(event_types) = 'array'),
    CONSTRAINT ck_sand_iam_webhook_endpoint_timeout
        CHECK (timeout_seconds BETWEEN 1 AND 30),
    CONSTRAINT ck_sand_iam_webhook_endpoint_attempts
        CHECK (max_attempts BETWEEN 1 AND 10),
    CONSTRAINT ck_sand_iam_webhook_endpoint_status
        CHECK (status IN (1, 2)),
    CONSTRAINT uk_sand_iam_webhook_endpoint_app_code
        UNIQUE (application_id, code),
    CONSTRAINT uk_sand_iam_webhook_endpoint_id_application
        UNIQUE (id, application_id)
);

CREATE INDEX IF NOT EXISTS idx_sand_iam_webhook_endpoint_app_status
    ON sand_iam_webhook_endpoint (application_id, status);

CREATE TABLE IF NOT EXISTS sand_iam_webhook_delivery (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL,
    webhook_endpoint_id bigint NOT NULL,
    event_id varchar(96) NOT NULL,
    event_type varchar(96) NOT NULL,
    payload jsonb NOT NULL,
    status smallint NOT NULL DEFAULT 1,
    attempt_count smallint NOT NULL DEFAULT 0,
    next_attempt_time timestamp(0) without time zone NULL,
    locked_until timestamp(0) without time zone NULL,
    delivered_time timestamp(0) without time zone NULL,
    response_status smallint NULL,
    response_digest char(64) NULL,
    last_error_code varchar(96) NULL,
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT fk_sand_iam_webhook_delivery_endpoint
        FOREIGN KEY (webhook_endpoint_id, application_id) REFERENCES sand_iam_webhook_endpoint(id, application_id) ON DELETE RESTRICT,
    CONSTRAINT ck_sand_iam_webhook_delivery_payload
        CHECK (jsonb_typeof(payload) = 'object'),
    CONSTRAINT ck_sand_iam_webhook_delivery_status
        CHECK (status IN (1, 2, 3, 4)),
    CONSTRAINT ck_sand_iam_webhook_delivery_attempts
        CHECK (attempt_count BETWEEN 0 AND 10),
    CONSTRAINT uk_sand_iam_webhook_delivery_event
        UNIQUE (webhook_endpoint_id, event_id)
);

CREATE INDEX IF NOT EXISTS idx_sand_iam_webhook_delivery_pending
    ON sand_iam_webhook_delivery (status, next_attempt_time, id);

CREATE INDEX IF NOT EXISTS idx_sand_iam_webhook_delivery_application
    ON sand_iam_webhook_delivery (application_id, event_type, create_time DESC);
