CREATE TABLE IF NOT EXISTS sand_iam_security_operation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_type varchar(32) NOT NULL,
    actor_ref varchar(128) NOT NULL,
    operation varchar(96) NOT NULL,
    request_id varchar(96) NOT NULL,
    request_fingerprint char(64) NOT NULL,
    resource_type varchar(64) NOT NULL,
    resource_id bigint NULL,
    state varchar(16) NOT NULL,
    result jsonb NOT NULL DEFAULT '{}'::jsonb,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sand_iam_security_operation_actor_request UNIQUE (actor_type, actor_ref, operation, request_id),
    CONSTRAINT ck_sand_iam_security_operation_state CHECK (state IN ('pending', 'succeeded')),
    CONSTRAINT ck_sand_iam_security_operation_fingerprint CHECK (request_fingerprint ~ '^[0-9a-f]{64}$')
);

ALTER TABLE sand_iam_security_operation ADD COLUMN IF NOT EXISTS actor_type varchar(32);
ALTER TABLE sand_iam_security_operation ADD COLUMN IF NOT EXISTS actor_ref varchar(128);
ALTER TABLE sand_iam_security_operation ADD COLUMN IF NOT EXISTS operation varchar(96);
ALTER TABLE sand_iam_security_operation ADD COLUMN IF NOT EXISTS request_id varchar(96);
ALTER TABLE sand_iam_security_operation ADD COLUMN IF NOT EXISTS request_fingerprint char(64);
ALTER TABLE sand_iam_security_operation ADD COLUMN IF NOT EXISTS resource_type varchar(64);
ALTER TABLE sand_iam_security_operation ADD COLUMN IF NOT EXISTS resource_id bigint NULL;
ALTER TABLE sand_iam_security_operation ADD COLUMN IF NOT EXISTS state varchar(16);
ALTER TABLE sand_iam_security_operation ADD COLUMN IF NOT EXISTS result jsonb NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE sand_iam_security_operation ADD COLUMN IF NOT EXISTS create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE sand_iam_security_operation ADD COLUMN IF NOT EXISTS update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uk_sand_iam_security_operation_actor_request' AND conrelid = 'sand_iam_security_operation'::regclass) THEN
        ALTER TABLE sand_iam_security_operation ADD CONSTRAINT uk_sand_iam_security_operation_actor_request UNIQUE (actor_type, actor_ref, operation, request_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_sand_iam_security_operation_state' AND conrelid = 'sand_iam_security_operation'::regclass) THEN
        ALTER TABLE sand_iam_security_operation ADD CONSTRAINT ck_sand_iam_security_operation_state CHECK (state IN ('pending', 'succeeded'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_sand_iam_security_operation_fingerprint' AND conrelid = 'sand_iam_security_operation'::regclass) THEN
        ALTER TABLE sand_iam_security_operation ADD CONSTRAINT ck_sand_iam_security_operation_fingerprint CHECK (request_fingerprint ~ '^[0-9a-f]{64}$');
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_sand_iam_security_operation_resource ON sand_iam_security_operation (resource_type, resource_id);
CREATE INDEX IF NOT EXISTS idx_sand_iam_security_operation_create_time ON sand_iam_security_operation (create_time);
