BEGIN;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ck_sand_iam_service_grant_data_class'
          AND conrelid = 'sand_iam_service_grant'::regclass
    ) THEN
        ALTER TABLE sand_iam_service_grant
            ADD CONSTRAINT ck_sand_iam_service_grant_data_class
            CHECK (data_class IS NULL OR data_class ~ '^[a-z0-9][a-z0-9._-]{1,31}$')
            NOT VALID;
    END IF;
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ck_sand_iam_service_grant_quota_object'
          AND conrelid = 'sand_iam_service_grant'::regclass
    ) THEN
        ALTER TABLE sand_iam_service_grant
            ADD CONSTRAINT ck_sand_iam_service_grant_quota_object
            CHECK (quota_policy IS NULL OR jsonb_typeof(quota_policy) = 'object')
            NOT VALID;
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS sand_iam_service_invocation_operation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workload_client_id bigint NOT NULL REFERENCES sand_iam_workload_client(id) ON DELETE RESTRICT,
    credential_id bigint NOT NULL REFERENCES sand_iam_credential(id) ON DELETE RESTRICT,
    organization_id bigint NOT NULL REFERENCES sand_iam_organization(id) ON DELETE RESTRICT,
    application_id bigint NOT NULL REFERENCES sand_iam_application(id) ON DELETE RESTRICT,
    environment_id bigint NOT NULL REFERENCES sand_iam_environment(id) ON DELETE RESTRICT,
    grant_id bigint NOT NULL REFERENCES sand_iam_service_grant(id) ON DELETE RESTRICT,
    operation_id varchar(96) NOT NULL,
    request_fingerprint varchar(64) NOT NULL,
    context_id varchar(64) NOT NULL,
    service_code varchar(64) NOT NULL,
    action_code varchar(96) NOT NULL,
    audience varchar(128) NOT NULL,
    data_class varchar(32) NULL,
    resource_type varchar(64) NOT NULL,
    resource_ref varchar(128) NOT NULL,
    outcome varchar(16) NOT NULL DEFAULT 'pending',
    error_code varchar(96) NULL,
    request_id varchar(96) NOT NULL,
    quota_window_start timestamp(0) without time zone NULL,
    quota_used bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sand_iam_invocation_operation_client_operation UNIQUE (workload_client_id, operation_id),
    CONSTRAINT ck_sand_iam_invocation_operation_outcome CHECK (outcome IN ('pending', 'allowed', 'denied')),
    CONSTRAINT ck_sand_iam_invocation_operation_quota_used CHECK (quota_used IS NULL OR quota_used > 0)
);

CREATE INDEX IF NOT EXISTS idx_sand_iam_invocation_operation_grant_time
    ON sand_iam_service_invocation_operation (grant_id, create_time DESC);
CREATE INDEX IF NOT EXISTS idx_sand_iam_invocation_operation_context
    ON sand_iam_service_invocation_operation (context_id);

CREATE TABLE IF NOT EXISTS sand_iam_service_quota_bucket (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grant_id bigint NOT NULL REFERENCES sand_iam_service_grant(id) ON DELETE RESTRICT,
    window_seconds integer NOT NULL,
    window_start timestamp(0) without time zone NOT NULL,
    used bigint NOT NULL DEFAULT 0,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sand_iam_service_quota_bucket UNIQUE (grant_id, window_seconds, window_start),
    CONSTRAINT ck_sand_iam_service_quota_bucket_window CHECK (window_seconds > 0 AND window_seconds <= 31536000),
    CONSTRAINT ck_sand_iam_service_quota_bucket_used CHECK (used >= 0)
);

CREATE INDEX IF NOT EXISTS idx_sand_iam_service_quota_bucket_window
    ON sand_iam_service_quota_bucket (window_start DESC);

COMMIT;
