-- SandIAM 0.7.0: editable, secret-free initialization drafts.
-- Applied initialization runs remain immutable rollback evidence.
-- These permissions are cataloged only. Existing roles are never granted them
-- automatically because initialization changes require an explicit administrator decision.
BEGIN;

DO $$
DECLARE
    application_ownership_key text;
BEGIN
    SELECT pg_get_constraintdef(constraint_row.oid, true)
    INTO application_ownership_key
    FROM pg_constraint constraint_row
    JOIN pg_class table_row ON table_row.oid = constraint_row.conrelid
    JOIN pg_namespace schema_row ON schema_row.oid = table_row.relnamespace
    WHERE schema_row.nspname = current_schema()
      AND table_row.relname = 'sand_iam_application'
      AND constraint_row.conname = 'uk_sand_iam_application_id_organization'
      AND constraint_row.contype = 'u';
    IF application_ownership_key IS DISTINCT FROM 'UNIQUE (id, organization_id)' THEN
        RAISE EXCEPTION 'SandIAM initialization drafts require the exact sand_iam_application ownership key';
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS sand_iam_initialization_draft (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL REFERENCES sand_iam_organization(id) ON DELETE RESTRICT,
    application_id bigint NULL,
    package_code varchar(64) NOT NULL,
    manifest jsonb NOT NULL,
    manifest_hash char(64) NOT NULL,
    revision integer NOT NULL DEFAULT 1,
    status smallint NOT NULL DEFAULT 1,
    created_by bigint NOT NULL,
    updated_by bigint NOT NULL,
    disabled_by bigint NULL,
    disabled_time timestamp(0) without time zone NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sand_iam_initialization_draft_application_organization
        FOREIGN KEY (application_id, organization_id)
        REFERENCES sand_iam_application(id, organization_id) ON DELETE RESTRICT,
    CONSTRAINT uk_sand_iam_initialization_draft_organization_package UNIQUE (organization_id, package_code),
    CONSTRAINT ck_sand_iam_initialization_draft_code CHECK (package_code ~ '^[a-z0-9][a-z0-9_-]{1,63}$'),
    CONSTRAINT ck_sand_iam_initialization_draft_hash CHECK (manifest_hash ~ '^[a-f0-9]{64}$'),
    CONSTRAINT ck_sand_iam_initialization_draft_revision CHECK (revision >= 1),
    CONSTRAINT ck_sand_iam_initialization_draft_status CHECK (status IN (1, 2))
);

CREATE INDEX IF NOT EXISTS idx_sand_iam_initialization_draft_application
    ON sand_iam_initialization_draft(organization_id, application_id, status, update_time DESC);
CREATE INDEX IF NOT EXISTS idx_sand_iam_initialization_draft_organization
    ON sand_iam_initialization_draft(organization_id, status, update_time DESC);

CREATE TABLE IF NOT EXISTS sand_iam_initialization_draft_revision (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draft_id bigint NOT NULL REFERENCES sand_iam_initialization_draft(id) ON DELETE RESTRICT,
    revision integer NOT NULL,
    manifest jsonb NOT NULL,
    manifest_hash char(64) NOT NULL,
    status smallint NOT NULL,
    action varchar(16) NOT NULL,
    actor_id bigint NOT NULL,
    request_id varchar(96) NOT NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sand_iam_initialization_draft_revision UNIQUE (draft_id, revision),
    CONSTRAINT ck_sand_iam_initialization_draft_revision_number CHECK (revision >= 1),
    CONSTRAINT ck_sand_iam_initialization_draft_revision_hash CHECK (manifest_hash ~ '^[a-f0-9]{64}$'),
    CONSTRAINT ck_sand_iam_initialization_draft_revision_status CHECK (status IN (1, 2)),
    CONSTRAINT ck_sand_iam_initialization_draft_revision_action CHECK (action IN ('created', 'updated', 'disabled', 'restored')),
    CONSTRAINT ck_sand_iam_initialization_draft_revision_request CHECK (request_id ~ '^[A-Za-z0-9][A-Za-z0-9_.:-]{7,95}$')
);

CREATE INDEX IF NOT EXISTS idx_sand_iam_initialization_draft_revision_history
    ON sand_iam_initialization_draft_revision(draft_id, create_time DESC);

DO $$
DECLARE
    actual_columns integer;
    matched_columns integer;
    matched_constraints integer;
    matched_indexes integer;
    index_evidence text;
BEGIN
    SELECT count(*) INTO actual_columns
    FROM information_schema.columns
    WHERE table_schema = current_schema()
      AND table_name IN ('sand_iam_initialization_draft', 'sand_iam_initialization_draft_revision');

    WITH required_column(table_name, column_name, data_type, character_maximum_length, is_nullable, requires_default) AS (
        VALUES
            ('sand_iam_initialization_draft', 'id', 'bigint', NULL::integer, 'NO', false),
            ('sand_iam_initialization_draft', 'organization_id', 'bigint', NULL, 'NO', false),
            ('sand_iam_initialization_draft', 'application_id', 'bigint', NULL, 'YES', false),
            ('sand_iam_initialization_draft', 'package_code', 'character varying', 64, 'NO', false),
            ('sand_iam_initialization_draft', 'manifest', 'jsonb', NULL, 'NO', false),
            ('sand_iam_initialization_draft', 'manifest_hash', 'character', 64, 'NO', false),
            ('sand_iam_initialization_draft', 'revision', 'integer', NULL, 'NO', true),
            ('sand_iam_initialization_draft', 'status', 'smallint', NULL, 'NO', true),
            ('sand_iam_initialization_draft', 'created_by', 'bigint', NULL, 'NO', false),
            ('sand_iam_initialization_draft', 'updated_by', 'bigint', NULL, 'NO', false),
            ('sand_iam_initialization_draft', 'disabled_by', 'bigint', NULL, 'YES', false),
            ('sand_iam_initialization_draft', 'disabled_time', 'timestamp without time zone', NULL, 'YES', false),
            ('sand_iam_initialization_draft', 'create_time', 'timestamp without time zone', NULL, 'NO', true),
            ('sand_iam_initialization_draft', 'update_time', 'timestamp without time zone', NULL, 'NO', true),
            ('sand_iam_initialization_draft_revision', 'id', 'bigint', NULL, 'NO', false),
            ('sand_iam_initialization_draft_revision', 'draft_id', 'bigint', NULL, 'NO', false),
            ('sand_iam_initialization_draft_revision', 'revision', 'integer', NULL, 'NO', false),
            ('sand_iam_initialization_draft_revision', 'manifest', 'jsonb', NULL, 'NO', false),
            ('sand_iam_initialization_draft_revision', 'manifest_hash', 'character', 64, 'NO', false),
            ('sand_iam_initialization_draft_revision', 'status', 'smallint', NULL, 'NO', false),
            ('sand_iam_initialization_draft_revision', 'action', 'character varying', 16, 'NO', false),
            ('sand_iam_initialization_draft_revision', 'actor_id', 'bigint', NULL, 'NO', false),
            ('sand_iam_initialization_draft_revision', 'request_id', 'character varying', 96, 'NO', false),
            ('sand_iam_initialization_draft_revision', 'create_time', 'timestamp without time zone', NULL, 'NO', true)
    )
    SELECT count(*) INTO matched_columns
    FROM required_column expected
    JOIN information_schema.columns actual
      ON actual.table_schema = current_schema()
     AND actual.table_name = expected.table_name
     AND actual.column_name = expected.column_name
     AND actual.data_type = expected.data_type
     AND actual.character_maximum_length IS NOT DISTINCT FROM expected.character_maximum_length
     AND actual.is_nullable = expected.is_nullable
     AND (NOT expected.requires_default OR actual.column_default IS NOT NULL);

    IF actual_columns <> 24 OR matched_columns <> 24
       OR (SELECT count(*) FROM information_schema.columns WHERE table_schema = current_schema() AND table_name IN ('sand_iam_initialization_draft', 'sand_iam_initialization_draft_revision') AND column_name = 'id' AND is_identity = 'YES') <> 2 THEN
        RAISE EXCEPTION 'SandIAM initialization-draft column fingerprint is incompatible';
    END IF;

    WITH required_constraint(table_name, constraint_name, constraint_type, definition_token, normalized_check_definition) AS (
        VALUES
            ('sand_iam_initialization_draft', 'sand_iam_initialization_draft_pkey', 'p', 'PRIMARY KEY (id)', NULL),
            ('sand_iam_initialization_draft', 'sand_iam_initialization_draft_organization_id_fkey', 'f', 'FOREIGN KEY (organization_id) REFERENCES sand_iam_organization(id) ON DELETE RESTRICT', NULL),
            ('sand_iam_initialization_draft', 'fk_sand_iam_initialization_draft_application_organization', 'f', 'FOREIGN KEY (application_id, organization_id) REFERENCES sand_iam_application(id, organization_id) ON DELETE RESTRICT', NULL),
            ('sand_iam_initialization_draft', 'uk_sand_iam_initialization_draft_organization_package', 'u', 'UNIQUE (organization_id, package_code)', NULL),
            ('sand_iam_initialization_draft', 'ck_sand_iam_initialization_draft_code', 'c', NULL, 'checkpackage_code~''^[a-z0-9][a-z0-9_-]{1,63}$'''),
            ('sand_iam_initialization_draft', 'ck_sand_iam_initialization_draft_hash', 'c', NULL, 'checkmanifest_hash~''^[a-f0-9]{64}$'''),
            ('sand_iam_initialization_draft', 'ck_sand_iam_initialization_draft_revision', 'c', NULL, 'checkrevision>=1'),
            ('sand_iam_initialization_draft', 'ck_sand_iam_initialization_draft_status', 'c', NULL, 'checkstatus=anyarray[1,2]'),
            ('sand_iam_initialization_draft_revision', 'sand_iam_initialization_draft_revision_pkey', 'p', 'PRIMARY KEY (id)', NULL),
            ('sand_iam_initialization_draft_revision', 'sand_iam_initialization_draft_revision_draft_id_fkey', 'f', 'FOREIGN KEY (draft_id) REFERENCES sand_iam_initialization_draft(id) ON DELETE RESTRICT', NULL),
            ('sand_iam_initialization_draft_revision', 'uk_sand_iam_initialization_draft_revision', 'u', 'UNIQUE (draft_id, revision)', NULL),
            ('sand_iam_initialization_draft_revision', 'ck_sand_iam_initialization_draft_revision_number', 'c', NULL, 'checkrevision>=1'),
            ('sand_iam_initialization_draft_revision', 'ck_sand_iam_initialization_draft_revision_hash', 'c', NULL, 'checkmanifest_hash~''^[a-f0-9]{64}$'''),
            ('sand_iam_initialization_draft_revision', 'ck_sand_iam_initialization_draft_revision_status', 'c', NULL, 'checkstatus=anyarray[1,2]'),
            ('sand_iam_initialization_draft_revision', 'ck_sand_iam_initialization_draft_revision_action', 'c', NULL, 'checkaction=anyarray[''created'',''updated'',''disabled'',''restored'']'),
            ('sand_iam_initialization_draft_revision', 'ck_sand_iam_initialization_draft_revision_request', 'c', NULL, 'checkrequest_id~''^[a-za-z0-9][a-za-z0-9_.:-]{7,95}$''')
    )
    SELECT count(*) INTO matched_constraints
    FROM required_constraint expected
    JOIN pg_constraint actual_constraint ON actual_constraint.conname = expected.constraint_name AND actual_constraint.contype = expected.constraint_type
    JOIN pg_class actual_table ON actual_table.oid = actual_constraint.conrelid
    JOIN pg_namespace actual_schema ON actual_schema.oid = actual_table.relnamespace
    WHERE actual_schema.nspname = current_schema()
      AND actual_table.relname = expected.table_name
      AND actual_constraint.convalidated
      AND (
          (expected.constraint_type <> 'c' AND pg_get_constraintdef(actual_constraint.oid, true) = expected.definition_token)
          OR (expected.constraint_type = 'c' AND regexp_replace(regexp_replace(regexp_replace(lower(pg_get_constraintdef(actual_constraint.oid, true)), E'::[a-z_][a-z0-9_]*(\\s+varying)?(\\[\\])?', '', 'g'), E'\\s+', '', 'g'), '[()]', '', 'g') = expected.normalized_check_definition)
      );

    IF matched_constraints <> 16
       OR (SELECT count(*) FROM pg_constraint actual_constraint JOIN pg_class actual_table ON actual_table.oid = actual_constraint.conrelid JOIN pg_namespace actual_schema ON actual_schema.oid = actual_table.relnamespace WHERE actual_schema.nspname = current_schema() AND actual_table.relname IN ('sand_iam_initialization_draft', 'sand_iam_initialization_draft_revision') AND actual_constraint.contype IN ('p', 'f', 'u', 'c')) <> 16 THEN
        RAISE EXCEPTION 'SandIAM initialization-draft constraint fingerprint is incompatible (matched %/16)', matched_constraints;
    END IF;

    WITH required_index(table_name, index_name, first_key, second_key, third_key, fourth_key, index_options) AS (
        VALUES
            ('sand_iam_initialization_draft', 'idx_sand_iam_initialization_draft_application', 'organization_id', 'application_id', 'status', 'update_time', '0 0 0 3'),
            ('sand_iam_initialization_draft', 'idx_sand_iam_initialization_draft_organization', 'organization_id', 'status', 'update_time', '', '0 0 3'),
            ('sand_iam_initialization_draft_revision', 'idx_sand_iam_initialization_draft_revision_history', 'draft_id', 'create_time', '', '', '0 3')
    )
    SELECT count(*) INTO matched_indexes
    FROM required_index expected
    JOIN pg_class actual_table ON actual_table.relname = expected.table_name
    JOIN pg_namespace actual_schema ON actual_schema.oid = actual_table.relnamespace AND actual_schema.nspname = current_schema()
    JOIN pg_index actual_index ON actual_index.indrelid = actual_table.oid
    JOIN pg_class index_relation ON index_relation.oid = actual_index.indexrelid AND index_relation.relname = expected.index_name
    WHERE NOT actual_index.indisunique AND actual_index.indisvalid AND actual_index.indisready
      AND pg_get_indexdef(actual_index.indexrelid, 1, true) = expected.first_key
      AND pg_get_indexdef(actual_index.indexrelid, 2, true) = expected.second_key
      AND pg_get_indexdef(actual_index.indexrelid, 3, true) IS NOT DISTINCT FROM expected.third_key
      AND pg_get_indexdef(actual_index.indexrelid, 4, true) IS NOT DISTINCT FROM expected.fourth_key
      AND actual_index.indoption::text = expected.index_options;

    IF matched_indexes <> 3 THEN
        SELECT string_agg(index_relation.relname || '=' || coalesce(pg_get_indexdef(actual_index.indexrelid, 1, true), '<null>') || '|' || coalesce(pg_get_indexdef(actual_index.indexrelid, 2, true), '<null>') || '|' || coalesce(pg_get_indexdef(actual_index.indexrelid, 3, true), '<null>') || '|' || coalesce(pg_get_indexdef(actual_index.indexrelid, 4, true), '<null>'), ';' ORDER BY index_relation.relname)
        INTO index_evidence
        FROM pg_index actual_index
        JOIN pg_class actual_table ON actual_table.oid = actual_index.indrelid
        JOIN pg_namespace actual_schema ON actual_schema.oid = actual_table.relnamespace
        JOIN pg_class index_relation ON index_relation.oid = actual_index.indexrelid
        WHERE actual_schema.nspname = current_schema()
          AND index_relation.relname IN ('idx_sand_iam_initialization_draft_application', 'idx_sand_iam_initialization_draft_organization', 'idx_sand_iam_initialization_draft_revision_history');
        RAISE EXCEPTION 'SandIAM initialization-draft index fingerprint is incompatible (matched %/3; actual %)', matched_indexes, index_evidence;
    END IF;
END $$;

DO $$
DECLARE
    parent_menu_id bigint;
BEGIN
    SELECT id INTO parent_menu_id
    FROM sand_system_menu
    WHERE code = 'SandIAMConnection'
    ORDER BY id
    LIMIT 1;
    IF parent_menu_id IS NULL THEN
        RAISE EXCEPTION 'SandIAM 0.7.0 cannot add initialization-draft permissions: parent menu SandIAMConnection is missing';
    END IF;
END $$;

WITH desired(code, name, sort) AS (
    VALUES
        ('sand_iam:initialization:save', '应用初始化方案新建草稿', 2027),
        ('sand_iam:initialization:update', '应用初始化方案编辑草稿', 2028),
        ('sand_iam:initialization:disable', '应用初始化方案停用草稿', 2029)
), parent AS (
    SELECT id FROM sand_system_menu WHERE code = 'SandIAMConnection' ORDER BY id LIMIT 1
), refresh_existing AS (
    UPDATE sand_system_menu existing
    SET parent_id = parent.id,
        name = desired.name,
        slug = desired.code,
        type = 3,
        path = '',
        component = '',
        icon = '',
        sort = desired.sort,
        is_hidden = 1,
        status = 1,
        update_time = CURRENT_TIMESTAMP
    FROM desired CROSS JOIN parent
    WHERE existing.code = desired.code
    RETURNING existing.id
)
INSERT INTO sand_system_menu (parent_id, name, code, slug, type, path, component, icon, sort, is_hidden, status, create_time, update_time)
SELECT parent.id, desired.name, desired.code, desired.code, 3, '', '', '', desired.sort, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM desired CROSS JOIN parent
WHERE NOT EXISTS (SELECT 1 FROM sand_system_menu existing WHERE existing.code = desired.code);

DO $$
DECLARE
    matched_permissions integer;
BEGIN
    WITH desired(code, name, sort) AS (
        VALUES
            ('sand_iam:initialization:save', '应用初始化方案新建草稿', 2027),
            ('sand_iam:initialization:update', '应用初始化方案编辑草稿', 2028),
            ('sand_iam:initialization:disable', '应用初始化方案停用草稿', 2029)
    ), parent AS (
        SELECT id FROM sand_system_menu WHERE code = 'SandIAMConnection' ORDER BY id LIMIT 1
    )
    SELECT count(*) INTO matched_permissions
    FROM desired
    CROSS JOIN parent
    JOIN sand_system_menu actual
      ON actual.code = desired.code
     AND actual.parent_id = parent.id
     AND actual.name = desired.name
     AND actual.slug = desired.code
     AND actual.type = 3
     AND actual.path = ''
     AND actual.component = ''
     AND actual.icon = ''
     AND actual.sort = desired.sort
     AND actual.is_hidden = 1
     AND actual.status = 1;
    IF matched_permissions <> 3 OR EXISTS (
        SELECT required.code
        FROM (VALUES
            ('sand_iam:initialization:save'),
            ('sand_iam:initialization:update'),
            ('sand_iam:initialization:disable')
        ) AS required(code)
        LEFT JOIN sand_system_menu actual ON actual.code = required.code
        GROUP BY required.code
        HAVING count(actual.id) <> 1
    ) THEN
        RAISE EXCEPTION 'SandIAM 0.7.0 initialization-draft permission fingerprint is incompatible';
    END IF;
END $$;

DO $$
DECLARE recorded record;
BEGIN
    SELECT revision, checksum, package_version INTO recorded
    FROM sand_iam_schema_migration WHERE migration_file = '037_initialization_draft.pgsql';
    IF recorded.revision IS NOT NULL AND (
        recorded.revision <> 37
        OR recorded.checksum <> 'cf7013ee42f9bd6319e8c23524f274e382901af7fbb32fa947732cd8beeb640c'
        OR recorded.package_version <> '0.7.0'
    ) THEN
        RAISE EXCEPTION 'SandIAM migration 037 ledger identity conflicts with initialization drafts';
    END IF;
END $$;

WITH self_checksum(checksum) AS (VALUES ('cf7013ee42f9bd6319e8c23524f274e382901af7fbb32fa947732cd8beeb640c'))
INSERT INTO sand_iam_schema_migration (migration_file, revision, checksum, package_version, executed_time)
SELECT '037_initialization_draft.pgsql', 37, self_checksum.checksum, '0.7.0', CURRENT_TIMESTAMP
FROM self_checksum
ON CONFLICT (migration_file) DO NOTHING;

DO $$
DECLARE recorded_rows integer;
BEGIN
    SELECT count(*) INTO recorded_rows
    FROM sand_iam_schema_migration
    WHERE migration_file = '037_initialization_draft.pgsql'
      AND revision = 37
      AND checksum = 'cf7013ee42f9bd6319e8c23524f274e382901af7fbb32fa947732cd8beeb640c'
      AND package_version = '0.7.0';
    IF recorded_rows <> 1 OR (SELECT count(*) FROM sand_iam_schema_migration) <> 38 THEN
        RAISE EXCEPTION 'SandIAM migration 037 did not close the exact 001-037 ledger';
    END IF;
END $$;

COMMIT;
