-- SandIAM 0.7.0: editable, secret-free initialization drafts.
-- Applied initialization runs remain immutable rollback evidence.
-- These permissions are cataloged only. Existing roles are never granted them
-- automatically because initialization changes require an explicit administrator decision.
BEGIN;

DO $$
DECLARE
    application_ownership_key text;
BEGIN
    SELECT pg_get_constraintdef(constraint_row.oid, true)
    INTO application_ownership_key
    FROM pg_constraint constraint_row
    JOIN pg_class table_row ON table_row.oid = constraint_row.conrelid
    JOIN pg_namespace schema_row ON schema_row.oid = table_row.relnamespace
    WHERE schema_row.nspname = current_schema()
      AND table_row.relname = 'sand_iam_application'
      AND constraint_row.conname = 'uk_sand_iam_application_id_organization'
      AND constraint_row.contype = 'u';
    IF application_ownership_key IS DISTINCT FROM 'UNIQUE (id, organization_id)' THEN
        RAISE EXCEPTION 'SandIAM initialization drafts require the exact sand_iam_application ownership key';
    END IF;
END $$;

CREATE TABLE sand_iam_initialization_draft (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL REFERENCES sand_iam_organization(id) ON DELETE RESTRICT,
    application_id bigint NULL,
    package_code varchar(64) NOT NULL,
    manifest jsonb NOT NULL,
    manifest_hash char(64) NOT NULL,
    revision integer NOT NULL DEFAULT 1,
    status smallint NOT NULL DEFAULT 1,
    created_by bigint NOT NULL,
    updated_by bigint NOT NULL,
    disabled_by bigint NULL,
    disabled_time timestamp(0) without time zone NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sand_iam_initialization_draft_application_organization
        FOREIGN KEY (application_id, organization_id)
        REFERENCES sand_iam_application(id, organization_id) ON DELETE RESTRICT,
    CONSTRAINT uk_sand_iam_initialization_draft_organization_package UNIQUE (organization_id, package_code),
    CONSTRAINT ck_sand_iam_initialization_draft_code CHECK (package_code ~ '^[a-z0-9][a-z0-9_-]{1,63}$'),
    CONSTRAINT ck_sand_iam_initialization_draft_hash CHECK (manifest_hash ~ '^[a-f0-9]{64}$'),
    CONSTRAINT ck_sand_iam_initialization_draft_revision CHECK (revision >= 1),
    CONSTRAINT ck_sand_iam_initialization_draft_status CHECK (status IN (1, 2))
);

CREATE INDEX idx_sand_iam_initialization_draft_application
    ON sand_iam_initialization_draft(organization_id, application_id, status, update_time DESC);
CREATE INDEX idx_sand_iam_initialization_draft_organization
    ON sand_iam_initialization_draft(organization_id, status, update_time DESC);

CREATE TABLE sand_iam_initialization_draft_revision (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draft_id bigint NOT NULL REFERENCES sand_iam_initialization_draft(id) ON DELETE RESTRICT,
    revision integer NOT NULL,
    manifest jsonb NOT NULL,
    manifest_hash char(64) NOT NULL,
    status smallint NOT NULL,
    action varchar(16) NOT NULL,
    actor_id bigint NOT NULL,
    request_id varchar(96) NOT NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sand_iam_initialization_draft_revision UNIQUE (draft_id, revision),
    CONSTRAINT ck_sand_iam_initialization_draft_revision_number CHECK (revision >= 1),
    CONSTRAINT ck_sand_iam_initialization_draft_revision_hash CHECK (manifest_hash ~ '^[a-f0-9]{64}$'),
    CONSTRAINT ck_sand_iam_initialization_draft_revision_status CHECK (status IN (1, 2)),
    CONSTRAINT ck_sand_iam_initialization_draft_revision_action CHECK (action IN ('created', 'updated', 'disabled', 'restored')),
    CONSTRAINT ck_sand_iam_initialization_draft_revision_request CHECK (request_id ~ '^[A-Za-z0-9][A-Za-z0-9_.:-]{7,95}$')
);

CREATE INDEX idx_sand_iam_initialization_draft_revision_history
    ON sand_iam_initialization_draft_revision(draft_id, create_time DESC);

DO $$
DECLARE
    parent_menu_id bigint;
BEGIN
    SELECT id INTO parent_menu_id
    FROM sand_system_menu
    WHERE code = 'SandIAMConnection'
    ORDER BY id
    LIMIT 1;
    IF parent_menu_id IS NULL THEN
        RAISE EXCEPTION 'SandIAM 0.7.0 cannot add initialization-draft permissions: parent menu SandIAMConnection is missing';
    END IF;
END $$;

WITH desired(code, name, sort) AS (
    VALUES
        ('sand_iam:initialization:save', '应用初始化方案新建草稿', 2027),
        ('sand_iam:initialization:update', '应用初始化方案编辑草稿', 2028),
        ('sand_iam:initialization:disable', '应用初始化方案停用草稿', 2029)
), parent AS (
    SELECT id FROM sand_system_menu WHERE code = 'SandIAMConnection' ORDER BY id LIMIT 1
), refresh_existing AS (
    UPDATE sand_system_menu existing
    SET parent_id = parent.id,
        name = desired.name,
        slug = desired.code,
        type = 3,
        path = '',
        component = '',
        icon = '',
        sort = desired.sort,
        is_hidden = 1,
        status = 1,
        update_time = CURRENT_TIMESTAMP
    FROM desired CROSS JOIN parent
    WHERE existing.code = desired.code
    RETURNING existing.id
)
INSERT INTO sand_system_menu (parent_id, name, code, slug, type, path, component, icon, sort, is_hidden, status, create_time, update_time)
SELECT parent.id, desired.name, desired.code, desired.code, 3, '', '', '', desired.sort, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM desired CROSS JOIN parent
WHERE NOT EXISTS (SELECT 1 FROM sand_system_menu existing WHERE existing.code = desired.code);

DO $$
DECLARE
    matched_permissions integer;
BEGIN
    WITH desired(code, name, sort) AS (
        VALUES
            ('sand_iam:initialization:save', '应用初始化方案新建草稿', 2027),
            ('sand_iam:initialization:update', '应用初始化方案编辑草稿', 2028),
            ('sand_iam:initialization:disable', '应用初始化方案停用草稿', 2029)
    ), parent AS (
        SELECT id FROM sand_system_menu WHERE code = 'SandIAMConnection' ORDER BY id LIMIT 1
    )
    SELECT count(*) INTO matched_permissions
    FROM desired
    CROSS JOIN parent
    JOIN sand_system_menu actual
      ON actual.code = desired.code
     AND actual.parent_id = parent.id
     AND actual.name = desired.name
     AND actual.slug = desired.code
     AND actual.type = 3
     AND actual.path = ''
     AND actual.component = ''
     AND actual.icon = ''
     AND actual.sort = desired.sort
     AND actual.is_hidden = 1
     AND actual.status = 1;
    IF matched_permissions <> 3 OR EXISTS (
        SELECT required.code
        FROM (VALUES
            ('sand_iam:initialization:save'),
            ('sand_iam:initialization:update'),
            ('sand_iam:initialization:disable')
        ) AS required(code)
        LEFT JOIN sand_system_menu actual ON actual.code = required.code
        GROUP BY required.code
        HAVING count(actual.id) <> 1
    ) THEN
        RAISE EXCEPTION 'SandIAM 0.7.0 initialization-draft permission fingerprint is incompatible';
    END IF;
END $$;

DO $$
DECLARE recorded record;
BEGIN
    SELECT revision, checksum, package_version INTO recorded
    FROM sand_iam_schema_migration WHERE migration_file = '037_initialization_draft.pgsql';
    IF recorded.revision IS NOT NULL AND (
        recorded.revision <> 37
        OR recorded.checksum <> '9b25cd1759f21305560b91304b5dba8a2c82d63d2f67714304dea174311e19a5'
        OR recorded.package_version <> '0.7.0'
    ) THEN
        RAISE EXCEPTION 'SandIAM migration 037 ledger identity conflicts with initialization drafts';
    END IF;
END $$;

WITH self_checksum(checksum) AS (VALUES ('9b25cd1759f21305560b91304b5dba8a2c82d63d2f67714304dea174311e19a5'))
INSERT INTO sand_iam_schema_migration (migration_file, revision, checksum, package_version, executed_time)
SELECT '037_initialization_draft.pgsql', 37, self_checksum.checksum, '0.7.0', CURRENT_TIMESTAMP
FROM self_checksum
ON CONFLICT (migration_file) DO NOTHING;

DO $$
DECLARE recorded_rows integer;
BEGIN
    SELECT count(*) INTO recorded_rows
    FROM sand_iam_schema_migration
    WHERE migration_file = '037_initialization_draft.pgsql'
      AND revision = 37
      AND checksum = '9b25cd1759f21305560b91304b5dba8a2c82d63d2f67714304dea174311e19a5'
      AND package_version = '0.7.0';
    IF recorded_rows <> 1 OR (SELECT count(*) FROM sand_iam_schema_migration) <> 38 THEN
        RAISE EXCEPTION 'SandIAM migration 037 did not close the exact 001-037 ledger';
    END IF;
END $$;

COMMIT;
