import { isHttpError } from '@/utils/http/error'
import type { SandIamRequestError } from './types'

const STABLE_CODES = [
  'SAND_IAM_VALIDATION_ERROR',
  'SAND_IAM_RESOURCE_NOT_FOUND',
  'SAND_IAM_ORGANIZATION_ACCESS_DENIED',
  'SAND_IAM_POLICY_DENIED',
  'SAND_IAM_RESOURCE_SCOPE_DENIED',
  'SAND_IAM_AUTHENTICATION_FAILED',
  'SAND_IAM_CREDENTIAL_REVOKED',
  'SAND_IAM_CONTEXT_EXPIRED',
  'SAND_IAM_CONTEXT_AUDIENCE_MISMATCH',
  'SAND_IAM_SERVICE_ACTION_FORBIDDEN',
  'SAND_IAM_IDEMPOTENCY_CONFLICT',
  'SAND_IAM_AUTH_POLICY_EXISTS',
  'SAND_IAM_AUTH_SESSION_NOT_FOUND',
  'SAND_IAM_MFA_CONFIGURATION_UNAVAILABLE',
  'SAND_IAM_MFA_TOTP_INVALID',
  'SAND_IAM_MFA_TOTP_REPLAYED',
  'SAND_IAM_MFA_RECOVERY_CODE_INVALID',
  'SAND_IAM_MFA_TOTP_REQUIRED_FOR_RECOVERY_CODES',
  'SAND_IAM_PASSKEY_CONFIGURATION_UNAVAILABLE',
  'SAND_IAM_FEDERATION_PROVIDER_CONFLICT',
  'SAND_IAM_FEDERATION_PROVIDER_CONFIGURATION_INVALID',
  'SAND_IAM_FEDERATION_PROVIDER_ALREADY_MOUNTED',
  'SAND_IAM_FEDERATION_IDENTITY_DOMAIN_IMMUTABLE',
  'SAND_IAM_FEDERATION_MAPPING_INVALID',
  'SAND_IAM_SAML_CONFIGURATION_INVALID',
  'SAND_IAM_SCIM_TOKEN_NAME_INVALID',
  'SAND_IAM_SCIM_TOKEN_CONFLICT',
  'SAND_IAM_SCIM_TOKEN_NOT_FOUND',
  'SAND_IAM_SCIM_TOKEN_EXPIRE_INVALID',
  'SAND_IAM_LDAP_EXTENSION_UNAVAILABLE',
  'SAND_IAM_LDAP_TLS_REQUIRED',
  'SAND_IAM_DIRECTORY_SYNC_FAILED',
  'SAND_IAM_IDP_PRESET_MANUAL_REQUIRED',
  'SAND_IAM_IDP_PRESET_SECRET_NOT_ALLOWED',
  'SAND_IAM_OAUTH_CLIENT_CODE_EXISTS',
  'SAND_IAM_OAUTH_CLIENT_SECRET_UNAVAILABLE',
  'SAND_IAM_OIDC_CONFIGURATION_UNAVAILABLE',
  'SAND_IAM_OIDC_SIGNING_KEY_NOT_FOUND',
  'SAND_IAM_OIDC_SIGNING_KEY_SCOPE_UNSUPPORTED',
  'SAND_IAM_OIDC_SIGNING_KEY_CONFIGURATION_INVALID',
  'SAND_IAM_API_CONFLICT',
  'SAND_IAM_ENVIRONMENT_CONFLICT',
  'SAND_IAM_ROUTE_BINDING_CONFLICT',
  'SAND_IAM_APPLICATION_ACTION_UNDECLARED',
  'SAND_IAM_APPLICATION_ACTION_DISABLED',
  'SAND_IAM_APPLICATION_ACTION_CODE_IMMUTABLE',
  'SAND_IAM_APPLICATION_ACTION_CONFLICT',
  'SAND_IAM_APPLICATION_ACTION_INVALID',
  'SAND_IAM_APPLICATION_ACTION_CODE_INVALID',
  'SAND_IAM_ROUTE_SYNC_ENVIRONMENT_MISMATCH',
  'SAND_IAM_ROUTE_SYNC_APPLY_BLOCKED',
  'SAND_IAM_ROUTE_SYNC_API_UNDECLARED',
  'SAND_IAM_ROUTE_SYNC_ACTION_UNDECLARED',
  'SAND_IAM_ROUTE_SYNC_ACTION_DISABLED',
  'SAND_IAM_ROUTE_SYNC_EMPTY',
  'SAND_IAM_ONBOARDING_MANIFEST_INVALID',
  'SAND_IAM_ONBOARDING_APPLY_REQUIRED',
  'SAND_IAM_ONBOARDING_PREVIEW_STALE',
  'SAND_IAM_API_NOT_REGISTERED',
  'SAND_IAM_ROUTE_NOT_REGISTERED',
  'SAND_IAM_ENTITY_SCOPE_CONFIGURATION_REQUIRED',
  'SAND_IAM_ENTITY_SCOPE_RESOLVER_REQUIRED',
  'SAND_IAM_ADMIN_APPLICATION_GRANT_CONFLICT',
  'SAND_IAM_WEBHOOK_CONFLICT',
  'SAND_IAM_WEBHOOK_NOT_FOUND',
  'SAND_IAM_WEBHOOK_EVENT_TYPES_INVALID',
  'SAND_IAM_WEBHOOK_EVENT_TYPE_INVALID',
  'SAND_IAM_WEBHOOK_CODE_INVALID',
  'SAND_IAM_WEBHOOK_NAME_INVALID',
  'SAND_IAM_WEBHOOK_URL_INVALID',
  'SAND_IAM_WEBHOOK_TIMEOUT_INVALID',
  'SAND_IAM_WEBHOOK_ATTEMPTS_INVALID',
  'SAND_IAM_WEBHOOK_DELIVERY_NOT_FOUND',
  'SAND_IAM_WEBHOOK_DELIVERY_NOT_RETRYABLE',
  'SAND_IAM_AUDIT_EXPORT_RANGE_REQUIRED',
  'SAND_IAM_AUDIT_EXPORT_TOO_LARGE',
  'SAND_IAM_AUDIT_TIME_RANGE_INVALID',
  'SAND_IAM_AUDIT_EXPORT_FAILED',
  'SAND_IAM_APPLICATION_EXPERIENCE_EXISTS',
  'SAND_IAM_APPLICATION_EXPERIENCE_UNAVAILABLE',
  'SAND_IAM_APPLICATION_EXPERIENCE_NOT_FOUND',
  'SAND_IAM_AUTH_REGISTRATION_DISABLED',
  'SAND_IAM_AUTH_METHOD_DISABLED',
  'SAND_IAM_AUTH_ACCOUNT_CONFLICT',
  'SAND_IAM_AUTH_ACCOUNT_LOCKED',
  'SAND_IAM_AUTH_PASSWORD_POLICY_VIOLATION',
  'SAND_IAM_AUTH_VERIFICATION_REQUIRED',
  'SAND_IAM_AUTH_VERIFICATION_INVALID',
  'SAND_IAM_CAPTCHA_REQUIRED',
  'SAND_IAM_CAPTCHA_INVALID',
  'SAND_IAM_CAPTCHA_UNAVAILABLE',
  'SAND_IAM_MESSAGE_PROVIDER_CONFLICT',
  'SAND_IAM_MESSAGE_PROVIDER_CONFIG_INVALID',
  'SAND_IAM_MESSAGE_PROVIDER_UNAVAILABLE',
  'SAND_IAM_IDENTITY_LIFECYCLE_UNAVAILABLE',
  'SAND_IAM_IDENTITY_NOT_ENABLEABLE',
  'SAND_IAM_IDENTITY_NOT_RESTORABLE',
  'SAND_IAM_IDENTITY_RESTORE_WINDOW_EXPIRED',
  'SAND_IAM_IDENTITY_ALREADY_DELETED',
  'SAND_IAM_IDENTITY_GROUP_DEPTH_EXCEEDED',
  'SAND_IAM_IDENTITY_GROUP_CYCLE',
  'SAND_IAM_IDENTITY_GROUP_HAS_CHILDREN',
  'SAND_IAM_IDENTITY_GROUP_HAS_MEMBERS',
  'SAND_IAM_IDENTITY_GROUP_CONFLICT',
  'SAND_IAM_IDENTITY_GROUP_DISABLED',
  'SAND_IAM_IDENTITY_GROUP_MEMBER_CONFLICT',
  'SAND_IAM_IDENTITY_GROUP_MEMBER_NOT_FOUND',
  'SAND_IAM_IDENTITY_GROUP_PARENT_INVALID',
  'SAND_IAM_INVITATION_GROUPS_INVALID',
  'SAND_IAM_GUEST_NOT_UPGRADEABLE',
  'SAND_IAM_INVITATION_CONFLICT',
  'SAND_IAM_INVITATION_NOT_RESENDABLE',
  'SAND_IAM_INVITATION_NOT_REVOCABLE',
  'SAND_IAM_INVITATION_INVALID',
  'SAND_IAM_INVITATION_EXPIRED',
  'SAND_IAM_INVITATION_DELIVERY_UNAVAILABLE',
  'SAND_IAM_INVITATION_DELIVERY_FAILED',
  'SAND_IAM_INVITATION_TARGET_INVALID',
  'SAND_IAM_INVITATION_CONFIGURATION_UNAVAILABLE',
  'SAND_IAM_IMPORT_FILE_INVALID',
  'SAND_IAM_IMPORT_MODE_INVALID',
  'SAND_IAM_IMPORT_CONFIRMATION_MISMATCH',
  'SAND_IAM_IMPORT_NOT_CONFIRMABLE',
  'SAND_IAM_IMPORT_HAS_INVALID_ROWS',
  'SAND_IAM_IMPORT_HEADERS_INVALID',
  'SAND_IAM_IMPORT_TOO_MANY_ROWS',
  'SAND_IAM_IMPORT_FILE_EMPTY',
  'SAND_IAM_IMPORT_IDENTITY_NOT_FOUND',
  'SAND_IAM_IMPORT_IDENTITY_STATE_CONFLICT',
  'SAND_IAM_IMPORT_ROW_FAILED',
  'SAND_IAM_IDENTITY_EXPORT_TOO_LARGE',
  'SAND_IAM_IDENTITY_EXPORT_FAILED',
  'SAND_IAM_SYNC_CONNECTOR_CONFLICT',
  'SAND_IAM_SYNC_CONNECTOR_NOT_FOUND',
  'SAND_IAM_SYNC_CONFIGURATION_INVALID',
  'SAND_IAM_SYNC_CONFIGURATION_UNAVAILABLE',
  'SAND_IAM_SYNC_AUTHORITY_MAP_INVALID',
  'SAND_IAM_SYNC_AUTHORITY_MAP_REQUIRED',
  'SAND_IAM_SYNC_ALREADY_RUNNING',
  'SAND_IAM_SYNC_FIELD_CONFLICT',
  'SAND_IAM_SYNC_GROUP_MAPPING_INVALID',
  'SAND_IAM_SYNC_GROUP_MAPPING_REQUIRED',
  'SAND_IAM_SYNC_GROUP_MAPPING_TARGET_NOT_FOUND',
  'SAND_IAM_SYNC_DISABLE_THRESHOLD_EXCEEDED',
  'SAND_IAM_SYNC_DRIVER_UNAVAILABLE',
  'SAND_IAM_SYNC_DIRECTION_UNSUPPORTED',
  'SAND_IAM_SYNC_DRIVER_RESPONSE_INVALID',
  'SAND_IAM_SYNC_OUTBOX_NOT_RETRYABLE',
  'SAND_IAM_SYNC_OUTBOUND_PAYLOAD_INVALID',
  'SAND_IAM_SYNC_OUTBOUND_FAILED',
  'SAND_IAM_SYNC_OUTBOUND_NOT_ACCEPTED',
  'SAND_IAM_DCR_DISABLED',
  'SAND_IAM_DCR_TOKEN_NAME_INVALID',
  'SAND_IAM_DCR_TOKEN_POLICY_INVALID',
  'SAND_IAM_DCR_TOKEN_NOT_FOUND',
  'SAND_IAM_DCR_ACCESS_DENIED',
  'SAND_IAM_DCR_INVALID_CLIENT_METADATA',
  'SAND_IAM_DCR_INVALID_REDIRECT_URI',
  'SAND_IAM_CAS_DISABLED',
  'SAND_IAM_CAS_OPTION_UNSUPPORTED',
  'SAND_IAM_CAS_REQUEST_INVALID',
  'SAND_IAM_CAS_REQUEST_REJECTED',
  'SAND_IAM_CAS_APPLICATION_MISMATCH',
  'SAND_IAM_CAS_SERVICE_URL_IMMUTABLE',
  'SAND_IAM_CAS_SERVICE_URL_EXISTS',
  'SAND_IAM_CAS_SERVICE_INVALID',
  'SAND_IAM_CAS_SERVICE_NOT_REGISTERED',
  'SAND_IAM_CAS_CONFIGURATION_UNAVAILABLE',
  'SAND_IAM_KERBEROS_CONFIGURATION_INVALID',
  'SAND_IAM_RADIUS_NAS_DISABLED',
  'SAND_IAM_RADIUS_NAS_NETWORK_OVERLAP',
  'SAND_IAM_RADIUS_MFA_REQUIRED',
  'SAND_IAM_NETWORK_POLICY_EXISTS',
  'SAND_IAM_NETWORK_POLICY_INVALID',
  'SAND_IAM_NETWORK_ACCESS_DENIED',
  'SAND_IAM_AUDIT_RETENTION_POLICY_EXISTS',
  'SAND_IAM_AUDIT_RETENTION_INVALID',
  'SAND_IAM_SECURITY_ALERT_POLICY_INVALID',
  'SAND_IAM_SECURITY_ALERT_ALREADY_RESOLVED',
  'SAND_IAM_INITIALIZATION_INVALID',
  'SAND_IAM_INITIALIZATION_PREVIEW_STALE',
  'SAND_IAM_INITIALIZATION_ORGANIZATION_NOT_FOUND',
  'SAND_IAM_INITIALIZATION_RUN_NOT_FOUND',
  'SAND_IAM_INITIALIZATION_ROLLBACK_INVALID',
  'SAND_IAM_INITIALIZATION_ROLLBACK_CONFIRMATION_INVALID',
  'SAND_IAM_INITIALIZATION_ROLLBACK_DRIFT',
  'SAND_IAM_INITIALIZATION_BINDING_DRIFT',
  'SAND_IAM_INITIALIZATION_BINDING_CONFLICT',
  'SAND_IAM_INITIALIZATION_POLICY_TARGET_CONFLICT',
  'SAND_IAM_INITIALIZATION_POLICY_AMBIGUOUS',
  'SAND_IAM_INITIALIZATION_PROVIDER_SCOPE_CONFLICT',
  'SAND_IAM_INITIALIZATION_PROVIDER_MOUNT_MISSING',
  'SAND_IAM_INITIALIZATION_SENSITIVE_FIELD',
  'SAND_IAM_INITIALIZATION_UNKNOWN_FIELD',
  'SAND_IAM_INITIALIZATION_SECRET_REQUIRED',
  'SAND_IAM_INITIALIZATION_FORMAT_UNSUPPORTED',
  'SAND_IAM_INITIALIZATION_TOO_LARGE',
  'SAND_IAM_INITIALIZATION_REFERENCE_INVALID',
  'SAND_IAM_INITIALIZATION_ACTION_UNDECLARED',
  'SAND_IAM_INITIALIZATION_RUN_INVALID',
  'SAND_IAM_OIDC_BACKCHANNEL_URI_INVALID',
  'SAND_IAM_OIDC_BACKCHANNEL_DESTINATION_REJECTED',
  'SAND_IAM_OIDC_BACKCHANNEL_TRANSPORT_UNAVAILABLE',
  'SAND_IAM_OIDC_BACKCHANNEL_DELIVERY_FAILED'
] as const

type StableCode = (typeof STABLE_CODES)[number]

const LABELS: Record<StableCode, string> = {
  SAND_IAM_VALIDATION_ERROR: '表单或筛选参数未通过校验',
  SAND_IAM_RESOURCE_NOT_FOUND: '关联对象不存在',
  SAND_IAM_ORGANIZATION_ACCESS_DENIED: '跨组织访问被拒绝',
  SAND_IAM_POLICY_DENIED: '策略拒绝本次操作',
  SAND_IAM_RESOURCE_SCOPE_DENIED: '数据范围不匹配',
  SAND_IAM_AUTHENTICATION_FAILED: '未登录或凭证无效',
  SAND_IAM_CREDENTIAL_REVOKED: '凭证已撤销或已停用',
  SAND_IAM_CONTEXT_EXPIRED: '调用上下文已过期',
  SAND_IAM_CONTEXT_AUDIENCE_MISMATCH: 'audience 与目标服务不匹配',
  SAND_IAM_SERVICE_ACTION_FORBIDDEN: '没有有效的服务授权',
  SAND_IAM_IDEMPOTENCY_CONFLICT: '幂等请求语义冲突',
  SAND_IAM_AUTH_POLICY_EXISTS: '与现有配置冲突',
  SAND_IAM_AUTH_SESSION_NOT_FOUND: '要撤销的会话不存在',
  SAND_IAM_MFA_CONFIGURATION_UNAVAILABLE: '多因素认证尚未就绪',
  SAND_IAM_MFA_TOTP_INVALID: '验证码不正确',
  SAND_IAM_MFA_TOTP_REPLAYED: '与现有配置冲突',
  SAND_IAM_MFA_RECOVERY_CODE_INVALID: '恢复码不正确',
  SAND_IAM_MFA_TOTP_REQUIRED_FOR_RECOVERY_CODES: '还没有可用的验证器',
  SAND_IAM_PASSKEY_CONFIGURATION_UNAVAILABLE: '通行密钥尚未配置',
  SAND_IAM_FEDERATION_PROVIDER_CONFLICT: '与现有配置冲突',
  SAND_IAM_FEDERATION_PROVIDER_CONFIGURATION_INVALID: '身份源协议配置未通过校验',
  SAND_IAM_FEDERATION_PROVIDER_ALREADY_MOUNTED: '与现有配置冲突',
  SAND_IAM_FEDERATION_IDENTITY_DOMAIN_IMMUTABLE: '与现有配置冲突',
  SAND_IAM_FEDERATION_MAPPING_INVALID: '属性映射未通过校验',
  SAND_IAM_SAML_CONFIGURATION_INVALID: 'SAML 配置未通过校验',
  SAND_IAM_SCIM_TOKEN_NAME_INVALID: '令牌名称未通过校验',
  SAND_IAM_SCIM_TOKEN_CONFLICT: '与现有配置冲突',
  SAND_IAM_SCIM_TOKEN_NOT_FOUND: '要撤销的令牌不存在',
  SAND_IAM_SCIM_TOKEN_EXPIRE_INVALID: '到期时间未通过校验',
  SAND_IAM_LDAP_EXTENSION_UNAVAILABLE: '目录同步环境未就绪',
  SAND_IAM_LDAP_TLS_REQUIRED: '目录必须使用加密连接',
  SAND_IAM_DIRECTORY_SYNC_FAILED: '目录同步未完成',
  SAND_IAM_IDP_PRESET_MANUAL_REQUIRED: '该预置身份源需要人工核对',
  SAND_IAM_IDP_PRESET_SECRET_NOT_ALLOWED: '预置草稿不能携带密钥',
  SAND_IAM_OAUTH_CLIENT_CODE_EXISTS: '与现有配置冲突',
  SAND_IAM_OAUTH_CLIENT_SECRET_UNAVAILABLE: '无法轮换客户端密钥',
  SAND_IAM_OIDC_CONFIGURATION_UNAVAILABLE: 'OIDC 签发尚未就绪',
  SAND_IAM_OIDC_SIGNING_KEY_NOT_FOUND: '要退役的签名密钥不存在',
  SAND_IAM_OIDC_SIGNING_KEY_SCOPE_UNSUPPORTED: '签名密钥不支持按应用分区',
  SAND_IAM_OIDC_SIGNING_KEY_CONFIGURATION_INVALID: '签名密钥配置异常',
  SAND_IAM_API_CONFLICT: '与现有配置冲突',
  SAND_IAM_ENVIRONMENT_CONFLICT: '应用环境代码重复',
  SAND_IAM_ROUTE_BINDING_CONFLICT: '与现有配置冲突',
  SAND_IAM_APPLICATION_ACTION_UNDECLARED: '业务动作尚未声明',
  SAND_IAM_APPLICATION_ACTION_DISABLED: '业务动作已停用',
  SAND_IAM_APPLICATION_ACTION_CODE_IMMUTABLE: '与现有配置冲突',
  SAND_IAM_APPLICATION_ACTION_CONFLICT: '与现有配置冲突',
  SAND_IAM_APPLICATION_ACTION_INVALID: '业务动作未通过校验',
  SAND_IAM_APPLICATION_ACTION_CODE_INVALID: '业务动作代码未通过校验',
  SAND_IAM_ROUTE_SYNC_ENVIRONMENT_MISMATCH: '环境不匹配',
  SAND_IAM_ROUTE_SYNC_APPLY_BLOCKED: '预检未通过，不能应用',
  SAND_IAM_ROUTE_SYNC_API_UNDECLARED: '接口尚未登记',
  SAND_IAM_ROUTE_SYNC_ACTION_UNDECLARED: '业务动作尚未声明',
  SAND_IAM_ROUTE_SYNC_ACTION_DISABLED: '业务动作已停用',
  SAND_IAM_ROUTE_SYNC_EMPTY: '清单没有已标记路由',
  SAND_IAM_ONBOARDING_MANIFEST_INVALID: '接入清单未通过校验',
  SAND_IAM_ONBOARDING_APPLY_REQUIRED: '尚未确认应用',
  SAND_IAM_ONBOARDING_PREVIEW_STALE: '预检已过期',
  SAND_IAM_API_NOT_REGISTERED: '接口未登记或已停用',
  SAND_IAM_ROUTE_NOT_REGISTERED: '路由没有启用绑定',
  SAND_IAM_ENTITY_SCOPE_CONFIGURATION_REQUIRED: '缺少数据范围前置条件',
  SAND_IAM_ENTITY_SCOPE_RESOLVER_REQUIRED: '缺少数据范围校验',
  SAND_IAM_ADMIN_APPLICATION_GRANT_CONFLICT: '与现有配置冲突',
  SAND_IAM_WEBHOOK_CONFLICT: '与现有配置冲突',
  SAND_IAM_WEBHOOK_NOT_FOUND: '通知不存在或已停用',
  SAND_IAM_WEBHOOK_EVENT_TYPES_INVALID: '订阅事件未通过校验',
  SAND_IAM_WEBHOOK_EVENT_TYPE_INVALID: '订阅事件未通过校验',
  SAND_IAM_WEBHOOK_CODE_INVALID: '系统代码未通过校验',
  SAND_IAM_WEBHOOK_NAME_INVALID: '通知名称未通过校验',
  SAND_IAM_WEBHOOK_URL_INVALID: '接收地址必须是 HTTPS',
  SAND_IAM_WEBHOOK_TIMEOUT_INVALID: '超时秒数未通过校验',
  SAND_IAM_WEBHOOK_ATTEMPTS_INVALID: '最大尝试次数未通过校验',
  SAND_IAM_WEBHOOK_DELIVERY_NOT_FOUND: '投递记录不存在',
  SAND_IAM_WEBHOOK_DELIVERY_NOT_RETRYABLE: '当前投递不能重试',
  SAND_IAM_AUDIT_EXPORT_RANGE_REQUIRED: '导出时间范围未通过校验',
  SAND_IAM_AUDIT_EXPORT_TOO_LARGE: '导出条数超过上限',
  SAND_IAM_AUDIT_TIME_RANGE_INVALID: '起始时间不能晚于结束时间',
  SAND_IAM_AUDIT_EXPORT_FAILED: '审计导出未完成',
  SAND_IAM_APPLICATION_EXPERIENCE_EXISTS: '与现有配置冲突',
  SAND_IAM_APPLICATION_EXPERIENCE_UNAVAILABLE: '登录外观尚未就绪',
  SAND_IAM_APPLICATION_EXPERIENCE_NOT_FOUND: '登录外观未配置',
  SAND_IAM_AUTH_REGISTRATION_DISABLED: '注册已关闭',
  SAND_IAM_AUTH_METHOD_DISABLED: '该登录方式已关闭',
  SAND_IAM_AUTH_ACCOUNT_CONFLICT: '与现有配置冲突',
  SAND_IAM_AUTH_ACCOUNT_LOCKED: '账号已锁定',
  SAND_IAM_AUTH_PASSWORD_POLICY_VIOLATION: '密码未通过策略',
  SAND_IAM_AUTH_VERIFICATION_REQUIRED: '还需要完成验证',
  SAND_IAM_AUTH_VERIFICATION_INVALID: '验证码不正确',
  SAND_IAM_CAPTCHA_REQUIRED: '需要人机验证',
  SAND_IAM_CAPTCHA_INVALID: '人机验证未通过',
  SAND_IAM_CAPTCHA_UNAVAILABLE: '人机验证不可用',
  SAND_IAM_MESSAGE_PROVIDER_CONFLICT: '与现有配置冲突',
  SAND_IAM_MESSAGE_PROVIDER_CONFIG_INVALID: '供应商配置未通过校验',
  SAND_IAM_MESSAGE_PROVIDER_UNAVAILABLE: '消息服务尚未就绪',
  SAND_IAM_IDENTITY_LIFECYCLE_UNAVAILABLE: '账号生命周期尚未启用',
  SAND_IAM_IDENTITY_NOT_ENABLEABLE: '当前账号不能启用',
  SAND_IAM_IDENTITY_NOT_RESTORABLE: '当前账号不能恢复',
  SAND_IAM_IDENTITY_RESTORE_WINDOW_EXPIRED: '删除保留期已过',
  SAND_IAM_IDENTITY_ALREADY_DELETED: '与现有配置冲突',
  SAND_IAM_IDENTITY_GROUP_DEPTH_EXCEEDED: '与现有配置冲突',
  SAND_IAM_IDENTITY_GROUP_CYCLE: '与现有配置冲突',
  SAND_IAM_IDENTITY_GROUP_HAS_CHILDREN: '与现有配置冲突',
  SAND_IAM_IDENTITY_GROUP_HAS_MEMBERS: '与现有配置冲突',
  SAND_IAM_IDENTITY_GROUP_CONFLICT: '与现有配置冲突',
  SAND_IAM_IDENTITY_GROUP_DISABLED: '用户组已停用',
  SAND_IAM_IDENTITY_GROUP_MEMBER_CONFLICT: '与现有配置冲突',
  SAND_IAM_IDENTITY_GROUP_MEMBER_NOT_FOUND: '组成员不存在',
  SAND_IAM_IDENTITY_GROUP_PARENT_INVALID: '上级用户组不可用',
  SAND_IAM_INVITATION_GROUPS_INVALID: '初始用户组未通过校验',
  SAND_IAM_GUEST_NOT_UPGRADEABLE: '该访客不能升级',
  SAND_IAM_INVITATION_CONFLICT: '与现有配置冲突',
  SAND_IAM_INVITATION_NOT_RESENDABLE: '当前邀请不能重发',
  SAND_IAM_INVITATION_NOT_REVOCABLE: '当前邀请不能撤销',
  SAND_IAM_INVITATION_INVALID: '邀请无效',
  SAND_IAM_INVITATION_EXPIRED: '邀请已过期',
  SAND_IAM_INVITATION_DELIVERY_UNAVAILABLE: '邀请投递未完成',
  SAND_IAM_INVITATION_DELIVERY_FAILED: '邀请投递失败',
  SAND_IAM_INVITATION_TARGET_INVALID: '接收目标未通过校验',
  SAND_IAM_INVITATION_CONFIGURATION_UNAVAILABLE: '邀请投递尚未就绪',
  SAND_IAM_IMPORT_FILE_INVALID: '导入文件未通过校验',
  SAND_IAM_IMPORT_MODE_INVALID: '导入方式未通过校验',
  SAND_IAM_IMPORT_CONFIRMATION_MISMATCH: '预检摘要不匹配',
  SAND_IAM_IMPORT_NOT_CONFIRMABLE: '当前任务不能确认',
  SAND_IAM_IMPORT_HAS_INVALID_ROWS: '预检仍有错误行',
  SAND_IAM_IMPORT_HEADERS_INVALID: '表头与模板不一致',
  SAND_IAM_IMPORT_TOO_MANY_ROWS: '导入行数超过上限',
  SAND_IAM_IMPORT_FILE_EMPTY: '导入文件没有数据行',
  SAND_IAM_IMPORT_IDENTITY_NOT_FOUND: '要更新的应用用户不存在',
  SAND_IAM_IMPORT_IDENTITY_STATE_CONFLICT: '与现有配置冲突',
  SAND_IAM_IMPORT_ROW_FAILED: '该行执行失败',
  SAND_IAM_IDENTITY_EXPORT_TOO_LARGE: '导出条数超过上限',
  SAND_IAM_IDENTITY_EXPORT_FAILED: '用户导出未完成',
  SAND_IAM_SYNC_CONNECTOR_CONFLICT: '与现有配置冲突',
  SAND_IAM_SYNC_CONNECTOR_NOT_FOUND: '同步连接不存在',
  SAND_IAM_SYNC_CONFIGURATION_INVALID: '连接配置未通过校验',
  SAND_IAM_SYNC_CONFIGURATION_UNAVAILABLE: '连接配置尚未就绪',
  SAND_IAM_SYNC_AUTHORITY_MAP_INVALID: '字段权威未通过校验',
  SAND_IAM_SYNC_AUTHORITY_MAP_REQUIRED: '双向同步缺少字段权威',
  SAND_IAM_SYNC_ALREADY_RUNNING: '同步仍在执行',
  SAND_IAM_SYNC_FIELD_CONFLICT: '与现有配置冲突',
  SAND_IAM_SYNC_GROUP_MAPPING_INVALID: '用户组映射未通过校验',
  SAND_IAM_SYNC_GROUP_MAPPING_REQUIRED: '存在未映射用户组',
  SAND_IAM_SYNC_GROUP_MAPPING_TARGET_NOT_FOUND: '映射目标用户组不存在',
  SAND_IAM_SYNC_DISABLE_THRESHOLD_EXCEEDED: '停用比例超过阈值',
  SAND_IAM_SYNC_DRIVER_UNAVAILABLE: '同步驱动尚未就绪',
  SAND_IAM_SYNC_DIRECTION_UNSUPPORTED: '当前驱动不支持该方向',
  SAND_IAM_SYNC_DRIVER_RESPONSE_INVALID: '驱动响应未通过校验',
  SAND_IAM_SYNC_OUTBOX_NOT_RETRYABLE: '当前出站事件不能重试',
  SAND_IAM_SYNC_OUTBOUND_PAYLOAD_INVALID: '出站载荷无法安全读取',
  SAND_IAM_SYNC_OUTBOUND_FAILED: '出站同步未完成',
  SAND_IAM_SYNC_OUTBOUND_NOT_ACCEPTED: '外部目录未接受出站事件',
  SAND_IAM_DCR_DISABLED: '动态注册未启用',
  SAND_IAM_DCR_TOKEN_NAME_INVALID: '令牌名称未通过校验',
  SAND_IAM_DCR_TOKEN_POLICY_INVALID: '令牌策略未通过校验',
  SAND_IAM_DCR_TOKEN_NOT_FOUND: '要撤销的令牌不存在',
  SAND_IAM_DCR_ACCESS_DENIED: '动态注册令牌无效或已耗尽',
  SAND_IAM_DCR_INVALID_CLIENT_METADATA: '客户端元数据未通过校验',
  SAND_IAM_DCR_INVALID_REDIRECT_URI: '回调地址不在允许主机内',
  SAND_IAM_CAS_DISABLED: 'CAS 接入未启用',
  SAND_IAM_CAS_OPTION_UNSUPPORTED: '该 CAS 选项当前不可用',
  SAND_IAM_CAS_REQUEST_INVALID: 'CAS 确认请求无效',
  SAND_IAM_CAS_REQUEST_REJECTED: 'CAS 请求未被接受',
  SAND_IAM_CAS_APPLICATION_MISMATCH: '当前应用用户与目标服务不匹配',
  SAND_IAM_CAS_SERVICE_URL_IMMUTABLE: '与现有配置冲突',
  SAND_IAM_CAS_SERVICE_URL_EXISTS: '与现有配置冲突',
  SAND_IAM_CAS_SERVICE_INVALID: 'CAS 服务地址未通过校验',
  SAND_IAM_CAS_SERVICE_NOT_REGISTERED: '该服务地址尚未登记',
  SAND_IAM_CAS_CONFIGURATION_UNAVAILABLE: 'CAS 运行环境尚未就绪',
  SAND_IAM_KERBEROS_CONFIGURATION_INVALID: 'Kerberos 配置未通过校验',
  SAND_IAM_RADIUS_NAS_DISABLED: '网络设备已停用',
  SAND_IAM_RADIUS_NAS_NETWORK_OVERLAP: '与现有配置冲突',
  SAND_IAM_RADIUS_MFA_REQUIRED: '当前账号不能用 RADIUS 登录',
  SAND_IAM_NETWORK_POLICY_EXISTS: '与现有配置冲突',
  SAND_IAM_NETWORK_POLICY_INVALID: '网络规则未通过校验',
  SAND_IAM_NETWORK_ACCESS_DENIED: '当前网络地址不允许访问',
  SAND_IAM_AUDIT_RETENTION_POLICY_EXISTS: '与现有配置冲突',
  SAND_IAM_AUDIT_RETENTION_INVALID: '归档或保留天数未通过校验',
  SAND_IAM_SECURITY_ALERT_POLICY_INVALID: '告警阈值未通过校验',
  SAND_IAM_SECURITY_ALERT_ALREADY_RESOLVED: '与现有配置冲突',
  SAND_IAM_INITIALIZATION_INVALID: '初始化包未通过校验',
  SAND_IAM_INITIALIZATION_PREVIEW_STALE: '预检已过期',
  SAND_IAM_INITIALIZATION_ORGANIZATION_NOT_FOUND: '目标客户主体不存在或已停用',
  SAND_IAM_INITIALIZATION_RUN_NOT_FOUND: '初始化记录不存在',
  SAND_IAM_INITIALIZATION_ROLLBACK_INVALID: '当前记录不能回滚',
  SAND_IAM_INITIALIZATION_ROLLBACK_CONFIRMATION_INVALID: '回滚确认未通过',
  SAND_IAM_INITIALIZATION_ROLLBACK_DRIFT: '与现有配置冲突',
  SAND_IAM_INITIALIZATION_BINDING_DRIFT: '与现有配置冲突',
  SAND_IAM_INITIALIZATION_BINDING_CONFLICT: '与现有配置冲突',
  SAND_IAM_INITIALIZATION_POLICY_TARGET_CONFLICT: '与现有配置冲突',
  SAND_IAM_INITIALIZATION_POLICY_AMBIGUOUS: '与现有配置冲突',
  SAND_IAM_INITIALIZATION_PROVIDER_SCOPE_CONFLICT: '与现有配置冲突',
  SAND_IAM_INITIALIZATION_PROVIDER_MOUNT_MISSING: '身份源缺少启用挂载',
  SAND_IAM_INITIALIZATION_SENSITIVE_FIELD: '初始化包包含敏感字段',
  SAND_IAM_INITIALIZATION_UNKNOWN_FIELD: '初始化包包含未知字段',
  SAND_IAM_INITIALIZATION_SECRET_REQUIRED: '外部身份源不能写入初始化包',
  SAND_IAM_INITIALIZATION_FORMAT_UNSUPPORTED: '初始化包格式不受支持',
  SAND_IAM_INITIALIZATION_TOO_LARGE: '初始化包超过大小上限',
  SAND_IAM_INITIALIZATION_REFERENCE_INVALID: '初始化包引用缺失',
  SAND_IAM_INITIALIZATION_ACTION_UNDECLARED: '策略动作尚未在包内声明',
  SAND_IAM_INITIALIZATION_RUN_INVALID: '初始化记录无法安全解释',
  SAND_IAM_OIDC_BACKCHANNEL_URI_INVALID: '后通道登出地址未通过校验',
  SAND_IAM_OIDC_BACKCHANNEL_DESTINATION_REJECTED: '后通道登出目标被拒绝',
  SAND_IAM_OIDC_BACKCHANNEL_TRANSPORT_UNAVAILABLE: '后通道登出传输尚未就绪',
  SAND_IAM_OIDC_BACKCHANNEL_DELIVERY_FAILED: '后通道登出投递失败'
}

const RECOVERY: Record<StableCode, string> = {
  SAND_IAM_VALIDATION_ERROR: '请按字段提示检查必填项、格式和关联对象后重新提交。',
  SAND_IAM_RESOURCE_NOT_FOUND:
    '目标对象可能已停用、删除或不在当前管理范围内，请刷新页面后重新选择。',
  SAND_IAM_ORGANIZATION_ACCESS_DENIED:
    '当前账号未获授该客户主体的管理范围，请联系平台管理员确认委派。',
  SAND_IAM_POLICY_DENIED: '当前策略不允许这项操作，请核对策略主体、业务资源、操作和生效条件。',
  SAND_IAM_RESOURCE_SCOPE_DENIED: '当前数据不在允许范围内，请核对策略的数据范围和业务对象归属。',
  SAND_IAM_AUTHENTICATION_FAILED:
    '登录会话或调用凭证无效，请重新登录，或由应用技术负责人更新凭证。',
  SAND_IAM_CREDENTIAL_REVOKED: '该调用凭证已撤销或停用，请使用轮换后安全交付的新凭证。',
  SAND_IAM_CONTEXT_EXPIRED: '本次调用上下文已过期，请由接入应用重新申请后再试。',
  SAND_IAM_CONTEXT_AUDIENCE_MISMATCH:
    '服务受众与目标服务不一致，请使用服务提供方给出的准确 audience。',
  SAND_IAM_SERVICE_ACTION_FORBIDDEN:
    '服务调用身份没有这项服务动作的有效授权，请核对授权状态、有效期和 audience。',
  SAND_IAM_IDEMPOTENCY_CONFLICT:
    '同一请求标识对应了不同内容，请勿重复提交，并联系技术支持核对请求。',
  SAND_IAM_AUTH_POLICY_EXISTS: '该接入应用已有认证策略，请直接编辑现有策略，不要重复新建。',
  SAND_IAM_AUTH_SESSION_NOT_FOUND: '会话可能已被撤销或已过期，请重新加载当前应用用户的会话列表。',
  SAND_IAM_MFA_CONFIGURATION_UNAVAILABLE:
    '请稍后重试；持续失败时联系平台管理员确认多因素认证部署密钥。',
  SAND_IAM_MFA_TOTP_INVALID: '请重新输入验证器上的 6 位验证码，不要使用刚用过的同一时间步。',
  SAND_IAM_MFA_TOTP_REPLAYED: '同一时间步的验证码只能用一次，请等待下一组数字后重试。',
  SAND_IAM_MFA_RECOVERY_CODE_INVALID: '请使用尚未用过的恢复码；用过的恢复码不能重放。',
  SAND_IAM_MFA_TOTP_REQUIRED_FOR_RECOVERY_CODES: '请先添加验证器，再重新生成恢复码。',
  SAND_IAM_PASSKEY_CONFIGURATION_UNAVAILABLE: '请先在认证设置高级区配置通行密钥域名和允许来源。',
  SAND_IAM_FEDERATION_PROVIDER_CONFLICT: '同范围下已有相同标识的身份源，请改用现有记录或更换标识。',
  SAND_IAM_FEDERATION_PROVIDER_CONFIGURATION_INVALID:
    '请按协议必填项检查地址、客户端标识和回跳白名单后重试。',
  SAND_IAM_FEDERATION_PROVIDER_ALREADY_MOUNTED: '该身份源已挂到所选接入应用，请直接编辑现有挂载。',
  SAND_IAM_FEDERATION_IDENTITY_DOMAIN_IMMUTABLE:
    '已有绑定或同步记录后，不能改协议或主体映射；请新建身份源。',
  SAND_IAM_FEDERATION_MAPPING_INVALID:
    '属性映射只能填写主体、用户名、显示名称、邮箱和是否启用，来源须为声明名。',
  SAND_IAM_SAML_CONFIGURATION_INVALID:
    '请完整填写实体、单点登录地址、接收地址和证书；私钥只写不读。',
  SAND_IAM_SCIM_TOKEN_NAME_INVALID: '请填写 1 至 128 字的令牌用途名称。',
  SAND_IAM_SCIM_TOKEN_CONFLICT: '同一用途名称可能已存在，请更换名称后重新签发。',
  SAND_IAM_SCIM_TOKEN_NOT_FOUND: '令牌可能已被撤销，请刷新列表。',
  SAND_IAM_SCIM_TOKEN_EXPIRE_INVALID: '到期时间必须是未来 1 年内的精确时间；留空则使用默认 90 天。',
  SAND_IAM_LDAP_EXTENSION_UNAVAILABLE: '当前运行环境未启用 LDAP 扩展，请联系平台管理员。',
  SAND_IAM_LDAP_TLS_REQUIRED: '目录地址必须是 ldaps://，不要使用未加密 ldap://。',
  SAND_IAM_DIRECTORY_SYNC_FAILED:
    '本次同步没有完整生效，请查看失败摘要后重试；不要把部分成功当成已连上生产目录。',
  SAND_IAM_IDP_PRESET_MANUAL_REQUIRED:
    '该预置尚未确认可直接套用，请按官方文档人工核对端点，不要保存猜测字段。',
  SAND_IAM_IDP_PRESET_SECRET_NOT_ALLOWED: '预置草稿接口禁止提交密钥，请在联合配置页单独填写。',
  SAND_IAM_OAUTH_CLIENT_CODE_EXISTS: '同一接入应用下客户端标识已存在，请改用现有客户端或更换标识。',
  SAND_IAM_OAUTH_CLIENT_SECRET_UNAVAILABLE:
    '只有已启用的机密客户端可以轮换密钥；公开客户端没有密钥。',
  SAND_IAM_OIDC_CONFIGURATION_UNAVAILABLE: '请联系平台管理员确认 OIDC 签发密钥部署后再重试。',
  SAND_IAM_OIDC_SIGNING_KEY_NOT_FOUND: '签名密钥可能已退役，请刷新状态后再操作。',
  SAND_IAM_OIDC_SIGNING_KEY_SCOPE_UNSUPPORTED:
    '当前签发范围是整个 issuer，不要按接入应用或环境分区。',
  SAND_IAM_OIDC_SIGNING_KEY_CONFIGURATION_INVALID:
    '请联系平台管理员检查签发密钥部署，不要在页面猜测私钥。',
  SAND_IAM_API_CONFLICT: '当前应用中已有相同接口代码和版本，请编辑现有记录。',
  SAND_IAM_ENVIRONMENT_CONFLICT:
    '所选接入应用中已有相同环境代码。请使用已有环境，或换一个系统代码后再保存。',
  SAND_IAM_ROUTE_BINDING_CONFLICT:
    '同一请求方法和路由模板已经绑定，请改清单或停用旧绑定，系统不会猜测覆盖。',
  SAND_IAM_APPLICATION_ACTION_UNDECLARED:
    '请先在应用业务动作目录声明并启用该动作，再登记接口或同步路由。',
  SAND_IAM_APPLICATION_ACTION_DISABLED: '已停用的业务动作不能用于新接口或授权，请改用已启用声明。',
  SAND_IAM_APPLICATION_ACTION_CODE_IMMUTABLE:
    '业务动作代码创建后不可修改；请新建声明并迁移接口和策略引用。',
  SAND_IAM_APPLICATION_ACTION_CONFLICT: '当前应用已存在相同业务动作代码，请使用已有声明。',
  SAND_IAM_APPLICATION_ACTION_INVALID: '请检查中文名称、说明和发布状态后重试。',
  SAND_IAM_APPLICATION_ACTION_CODE_INVALID: '请按 2–96 位小写字母开头规则填写业务动作代码。',
  SAND_IAM_ROUTE_SYNC_ENVIRONMENT_MISMATCH:
    '请核对清单中的客户主体、接入应用和应用环境是否仍启用且互相归属。',
  SAND_IAM_ROUTE_SYNC_APPLY_BLOCKED: '预检仍有冲突或未绑定项。修复后重新预检并确认保存。',
  SAND_IAM_ROUTE_SYNC_API_UNDECLARED: '请先登记接口目录，同步器不会自动创建业务资源、动作或策略。',
  SAND_IAM_ROUTE_SYNC_ACTION_UNDECLARED: '请先声明业务动作，再同步路由。',
  SAND_IAM_ROUTE_SYNC_ACTION_DISABLED: '相关接口授权会保持拒绝，请启用声明或改用已启用动作。',
  SAND_IAM_ROUTE_SYNC_EMPTY: '接入清单里还没有标记需要纳入管理的业务路由，请补充后重新预检。',
  SAND_IAM_ONBOARDING_MANIFEST_INVALID: '接入清单缺少必填内容，请按页面提示补充后重新预检。',
  SAND_IAM_ONBOARDING_APPLY_REQUIRED: '请先完成变更预览，再确认保存。',
  SAND_IAM_ONBOARDING_PREVIEW_STALE: '对象已被其他操作改变，请重新预检后再确认应用。',
  SAND_IAM_API_NOT_REGISTERED: '请确认接口代码、版本和启停状态，不要把 URL 当作权限键。',
  SAND_IAM_ROUTE_NOT_REGISTERED: '请先完成路由绑定或确认保存接入清单，再调用业务接口。',
  SAND_IAM_ENTITY_SCOPE_CONFIGURATION_REQUIRED:
    '写操作缺少数据范围校验。请联系应用开发负责人补齐后重试。',
  SAND_IAM_ENTITY_SCOPE_RESOLVER_REQUIRED: '数据范围校验尚未就绪。请联系应用开发负责人补齐后重试。',
  SAND_IAM_ADMIN_APPLICATION_GRANT_CONFLICT:
    '该后台管理员已经拥有此应用的委派，请编辑现有记录，不要重复新建。',
  SAND_IAM_WEBHOOK_CONFLICT: '当前应用已存在相同系统代码，请改用现有通知或更换代码。',
  SAND_IAM_WEBHOOK_NOT_FOUND: '通知可能已停用或删除，请刷新列表后重试。',
  SAND_IAM_WEBHOOK_EVENT_TYPES_INVALID: '请从事件目录勾选 1 至 64 个已冻结事件，不要手填未知代码。',
  SAND_IAM_WEBHOOK_EVENT_TYPE_INVALID: '请只订阅事件目录中的类型。',
  SAND_IAM_WEBHOOK_CODE_INVALID: '系统代码须为小写字母开头的 2–64 位字母、数字、下划线或连字符。',
  SAND_IAM_WEBHOOK_NAME_INVALID: '请填写 1 至 128 字的通知名称。',
  SAND_IAM_WEBHOOK_URL_INVALID: '接收地址必须是不含账号、密码和片段的 HTTPS 公网地址。',
  SAND_IAM_WEBHOOK_TIMEOUT_INVALID: '超时须为 1 至 30 秒。',
  SAND_IAM_WEBHOOK_ATTEMPTS_INVALID: '最大尝试次数须为 1 至 10 次。',
  SAND_IAM_WEBHOOK_DELIVERY_NOT_FOUND: '投递记录可能已过期，请刷新后重试。',
  SAND_IAM_WEBHOOK_DELIVERY_NOT_RETRYABLE:
    '只有等待中或最终失败的投递可以重试；投递中和已送达不能重放。',
  SAND_IAM_AUDIT_EXPORT_RANGE_REQUIRED: '请选择不超过 31 天的起止时间后再导出。',
  SAND_IAM_AUDIT_EXPORT_TOO_LARGE: '单次最多导出 10000 条，请缩小时间或筛选范围。',
  SAND_IAM_AUDIT_TIME_RANGE_INVALID: '请把起始时间改到结束时间之前。',
  SAND_IAM_AUDIT_EXPORT_FAILED: '请稍后重试；持续失败时联系平台管理员。',
  SAND_IAM_APPLICATION_EXPERIENCE_EXISTS: '该接入应用已有登录外观，请直接编辑现有记录。',
  SAND_IAM_APPLICATION_EXPERIENCE_UNAVAILABLE:
    '公开登录体验尚未启用。页面不能把这个状态显示成登录成功。',
  SAND_IAM_APPLICATION_EXPERIENCE_NOT_FOUND:
    '该应用还没有启用的登录外观。请先在管理端配置，不要把空态当成已登录。',
  SAND_IAM_AUTH_REGISTRATION_DISABLED:
    '当前应用未开放注册。邀请注册请走邀请链接，不要在本页自行注册。',
  SAND_IAM_AUTH_METHOD_DISABLED: '该登录方式未列入当前应用编排。请改用已启用方式，不要只隐藏按钮。',
  SAND_IAM_AUTH_ACCOUNT_CONFLICT: '用户名或联系方式已被使用，请改用其他标识或直接登录。',
  SAND_IAM_AUTH_ACCOUNT_LOCKED: '失败次数过多，请稍后再试或使用找回密码。',
  SAND_IAM_AUTH_PASSWORD_POLICY_VIOLATION: '请按认证策略的长度和字符要求重设密码。',
  SAND_IAM_AUTH_VERIFICATION_REQUIRED: '请先完成邮箱或手机验证，再继续登录。',
  SAND_IAM_AUTH_VERIFICATION_INVALID: '请使用尚未过期且未用过的验证码。',
  SAND_IAM_CAPTCHA_REQUIRED: '请完成人机验证后再提交。故障时不会放行。',
  SAND_IAM_CAPTCHA_INVALID: '请重新完成人机验证。',
  SAND_IAM_CAPTCHA_UNAVAILABLE: '人机验证服务不可用，登录不会放行。请稍后重试或联系应用管理员。',
  SAND_IAM_MESSAGE_PROVIDER_CONFLICT: '同一客户主体下系统代码可能已存在，请更换代码。',
  SAND_IAM_MESSAGE_PROVIDER_CONFIG_INVALID: '请填写完整供应商配置后重新保存。原值不会回显。',
  SAND_IAM_MESSAGE_PROVIDER_UNAVAILABLE: '消息服务未启用或未挂载，验证码不会改走未审计通道。',
  SAND_IAM_IDENTITY_LIFECYCLE_UNAVAILABLE:
    '删除、启用、恢复和用户组需要开启账号生命周期。请联系平台管理员；服务暂时不可用时不会显示为空列表。',
  SAND_IAM_IDENTITY_NOT_ENABLEABLE: '只有已停用账号可以启用。请刷新列表后按账号状态操作。',
  SAND_IAM_IDENTITY_NOT_RESTORABLE: '只有删除保留期内的账号可以恢复。过期后不能从本页找回。',
  SAND_IAM_IDENTITY_RESTORE_WINDOW_EXPIRED:
    '保留期已过，认证材料和关系将被清除。请改用新建用户，不要重试恢复。',
  SAND_IAM_IDENTITY_ALREADY_DELETED: '该用户已在删除保留期，请改用恢复或等待到期清理。',
  SAND_IAM_IDENTITY_GROUP_DEPTH_EXCEEDED: '用户组最多 8 层。请选择更浅的上级组，或先调整现有层级。',
  SAND_IAM_IDENTITY_GROUP_CYCLE: '不能把自己或下级组设为上级。请重新按名称选择上级组。',
  SAND_IAM_IDENTITY_GROUP_HAS_CHILDREN: '请先迁移或停用下级用户组，再停用或改挂本级。',
  SAND_IAM_IDENTITY_GROUP_HAS_MEMBERS: '请先移出全部成员，再停用该用户组。',
  SAND_IAM_IDENTITY_GROUP_CONFLICT: '同一接入应用下用户组代码可能已存在，请更换代码或编辑现有组。',
  SAND_IAM_IDENTITY_GROUP_DISABLED: '已停用的用户组不能加入成员。请先启用该组。',
  SAND_IAM_IDENTITY_GROUP_MEMBER_CONFLICT: '该用户可能已在组内。请刷新成员列表，不要跨应用选择。',
  SAND_IAM_IDENTITY_GROUP_MEMBER_NOT_FOUND: '成员可能已被移出，请刷新后再操作。',
  SAND_IAM_IDENTITY_GROUP_PARENT_INVALID:
    '上级用户组不存在、已停用或不属于当前应用，请按名称重新选择。',
  SAND_IAM_INVITATION_GROUPS_INVALID: '请按名称选择本应用已启用用户组，不要手填编号或跨应用组。',
  SAND_IAM_GUEST_NOT_UPGRADEABLE: '只能升级本应用、仍为访客状态的账号。请刷新后按名称重新选择。',
  SAND_IAM_INVITATION_CONFLICT: '同一接入应用已有未完成的相同目标邀请。请重发或撤销现有邀请。',
  SAND_IAM_INVITATION_NOT_RESENDABLE:
    '只有等待接受或投递失败的邀请可以重发。已接受、已撤销和已过期不能重放。',
  SAND_IAM_INVITATION_NOT_REVOCABLE: '只有发送中、等待接受或投递失败的邀请可以撤销。',
  SAND_IAM_INVITATION_INVALID:
    '邀请令牌无效、已撤销或已接受，不能重放。请使用最新链接或联系管理员重发。',
  SAND_IAM_INVITATION_EXPIRED: '邀请已过期。请联系应用管理员重发，不要重试旧链接。',
  SAND_IAM_INVITATION_DELIVERY_UNAVAILABLE:
    '邮件或短信通道未就绪。邀请保持可重试，账号不会被激活。',
  SAND_IAM_INVITATION_DELIVERY_FAILED: '投递失败可见且可重发。旧链接在重发后失效。',
  SAND_IAM_INVITATION_TARGET_INVALID: '请填写规范邮箱或带国家码的手机号。完整值不会出现在列表。',
  SAND_IAM_INVITATION_CONFIGURATION_UNAVAILABLE:
    '邀请令牌密钥或接受地址尚未配置。请联系平台管理员。',
  SAND_IAM_IMPORT_FILE_INVALID: '请上传不超过 2MB 的 UTF-8 CSV。单元格不能以公式字符开头。',
  SAND_IAM_IMPORT_MODE_INVALID: '请选择「新增邀请」或「更新已有用户」。',
  SAND_IAM_IMPORT_CONFIRMATION_MISMATCH: '文件或任务已被改变，请重新预检后再确认。不要强制覆盖。',
  SAND_IAM_IMPORT_NOT_CONFIRMABLE:
    '只有已预检、部分失败或失败的任务可以确认。已完成任务重复确认不会再创建。',
  SAND_IAM_IMPORT_HAS_INVALID_ROWS: '请按逐行错误修正 CSV 后重新预检。有错误行时不会写入账号。',
  SAND_IAM_IMPORT_HEADERS_INVALID:
    '表头必须是：用户名、显示名称、邮箱、手机号、账号状态、用户组代码。',
  SAND_IAM_IMPORT_TOO_MANY_ROWS: '单次最多 10000 行。请拆分文件后重新预检。',
  SAND_IAM_IMPORT_FILE_EMPTY: '请至少保留一行数据。',
  SAND_IAM_IMPORT_IDENTITY_NOT_FOUND: '更新模式只能处理本应用已有用户。未知用户不会被静默创建。',
  SAND_IAM_IMPORT_IDENTITY_STATE_CONFLICT: '访客或已删除账号不能通过导入更新。',
  SAND_IAM_IMPORT_ROW_FAILED: '该行失败不会伪装整批成功。可在部分失败后重试失败行。',
  SAND_IAM_IDENTITY_EXPORT_TOO_LARGE: '单次最多导出 10000 个应用用户。',
  SAND_IAM_IDENTITY_EXPORT_FAILED: '请稍后重试；持续失败时联系平台管理员。',
  SAND_IAM_SYNC_CONNECTOR_CONFLICT: '同一接入应用下系统代码可能已存在，请改用现有连接。',
  SAND_IAM_SYNC_CONNECTOR_NOT_FOUND: '连接可能已停用，请刷新列表。',
  SAND_IAM_SYNC_CONFIGURATION_INVALID:
    '请重新填写完整配置。原值不会回显，不要把失败当成已连接生产目录。',
  SAND_IAM_SYNC_CONFIGURATION_UNAVAILABLE: '请先保存连接配置再测试或执行。',
  SAND_IAM_SYNC_AUTHORITY_MAP_INVALID: '显示名称和用户组权威只能是来源或本地。',
  SAND_IAM_SYNC_AUTHORITY_MAP_REQUIRED: '双向同步必须声明显示名称权威方。',
  SAND_IAM_SYNC_ALREADY_RUNNING: '同一连接同一应用只允许一个运行中任务。请等待结束后再执行或停用。',
  SAND_IAM_SYNC_FIELD_CONFLICT: '本地与来源同时变化且策略为拒绝。请调整冲突策略或字段权威后重试。',
  SAND_IAM_SYNC_GROUP_MAPPING_INVALID: '请在连接配置里提供 group_map，不要让系统静默创建用户组。',
  SAND_IAM_SYNC_GROUP_MAPPING_REQUIRED:
    '来源用户组代码必须映射到本应用已有用户组。未映射代码会停止该页。',
  SAND_IAM_SYNC_GROUP_MAPPING_TARGET_NOT_FOUND: '映射目标必须是本应用已启用用户组。',
  SAND_IAM_SYNC_DISABLE_THRESHOLD_EXCEEDED: '单次停用比例超过阈值，已熔断。请人工确认后再执行。',
  SAND_IAM_SYNC_DRIVER_UNAVAILABLE: '当前环境没有该驱动。页面不会显示已连接生产目录。',
  SAND_IAM_SYNC_DIRECTION_UNSUPPORTED: '例如 postgresql 只允许入站。请改方向或更换驱动。',
  SAND_IAM_SYNC_DRIVER_RESPONSE_INVALID: '驱动返回格式无效。部分出站未接受时不会推进成功状态。',
  SAND_IAM_SYNC_OUTBOX_NOT_RETRYABLE:
    '只有失败的出站事件可以重新排队。纯入站连接没有可写出目标，已排队、已成功或不属于该连接的事件也不能重放。',
  SAND_IAM_SYNC_OUTBOUND_PAYLOAD_INVALID:
    '该事件载荷无法安全读取，页面不会展示或索取密文。请修正连接配置后再从本页重试。',
  SAND_IAM_SYNC_OUTBOUND_FAILED:
    '写出未完成。可在失败列表按该事件重新排队，不要把部分成功当成已连上生产目录。',
  SAND_IAM_SYNC_OUTBOUND_NOT_ACCEPTED:
    '外部目录未接受该事件。可在失败列表按该事件重新排队，不要把拒绝当成已写出。',
  SAND_IAM_DCR_DISABLED: '请联系平台管理员确认动态注册功能开关后再签发。',
  SAND_IAM_DCR_TOKEN_NAME_INVALID: '请填写 1 至 128 字的用途名称。',
  SAND_IAM_DCR_TOKEN_POLICY_INVALID:
    '回调主机必须是主机名或 127.0.0.1/::1，不能写完整 URL 或通配符；有效期 1–168 小时，次数 1–1000。',
  SAND_IAM_DCR_TOKEN_NOT_FOUND: '令牌可能已被撤销，请刷新列表。',
  SAND_IAM_DCR_ACCESS_DENIED: '请重新签发动态注册令牌；过期、耗尽或撤销的令牌不能重放。',
  SAND_IAM_DCR_INVALID_CLIENT_METADATA: '请按公开/机密与 Web/原生客户端规则检查登记信息。',
  SAND_IAM_DCR_INVALID_REDIRECT_URI: '回调地址的主机必须出现在该令牌允许的主机列表中。',
  SAND_IAM_CAS_DISABLED: '请联系平台管理员确认 CAS 功能开关。页面不会把管理端登录当成确认成功。',
  SAND_IAM_CAS_OPTION_UNSUPPORTED: '当前不支持 renew 或 gateway，请使用标准登录确认。',
  SAND_IAM_CAS_REQUEST_INVALID:
    '请求可能已过期、已使用或格式不正确。请从应用重新发起，不要重放旧 request。',
  SAND_IAM_CAS_REQUEST_REJECTED: '请核对服务地址和当前应用用户会话后重试。',
  SAND_IAM_CAS_APPLICATION_MISMATCH:
    '请使用目标接入应用的用户会话确认，不要使用 SandAdmin 登录态。',
  SAND_IAM_CAS_SERVICE_URL_IMMUTABLE: '服务地址启用后不可修改。请新增接入服务并停用旧记录。',
  SAND_IAM_CAS_SERVICE_URL_EXISTS: '该服务地址已登记到其他接入服务，请改用现有记录。',
  SAND_IAM_CAS_SERVICE_INVALID: '服务地址必须是无通配符、无账号信息和无片段的精确 HTTPS。',
  SAND_IAM_CAS_SERVICE_NOT_REGISTERED: '请先在管理端按精确 HTTPS 地址登记该服务。',
  SAND_IAM_CAS_CONFIGURATION_UNAVAILABLE: '请联系平台管理员检查 CAS 签发与 pepper 部署。',
  SAND_IAM_KERBEROS_CONFIGURATION_INVALID:
    '请填写 HTTP/主机@REALM 形式的 SPN、keytab 引用和允许 Realm，并保持三项安全要求开启。',
  SAND_IAM_RADIUS_NAS_DISABLED: '请先启用该网络设备，再设置共享密钥。',
  SAND_IAM_RADIUS_NAS_NETWORK_OVERLAP: '来源网段与已有设备重叠，请调整 CIDR 后再保存。',
  SAND_IAM_RADIUS_MFA_REQUIRED:
    '当前 RADIUS 只接受用户名和密码。已启用 MFA 的账号会被拒绝，请改用其他登录方式。',
  SAND_IAM_NETWORK_POLICY_EXISTS: '该应用已有网络规则，请直接编辑现有记录。',
  SAND_IAM_NETWORK_POLICY_INVALID: '请使用规范 CIDR。拒绝网段优先，启用后可能立即挡住登录。',
  SAND_IAM_NETWORK_ACCESS_DENIED:
    '当前来源地址命中拒绝规则或未出现在允许网段。请先用不会锁死自己的网段测试。',
  SAND_IAM_AUDIT_RETENTION_POLICY_EXISTS: '该客户主体已有审计策略，请直接编辑现有记录。',
  SAND_IAM_AUDIT_RETENTION_INVALID: '归档须为 1–3650 天，保留期不得短于归档期。',
  SAND_IAM_SECURITY_ALERT_POLICY_INVALID: '告警窗口须为 60–86400 秒，触发次数须为 2–10000。',
  SAND_IAM_SECURITY_ALERT_ALREADY_RESOLVED: '该告警已经处理，请刷新列表。',
  SAND_IAM_INITIALIZATION_INVALID:
    '初始化包内容不符合要求。请检查必填信息，且不要放入密码、令牌或密钥。',
  SAND_IAM_INITIALIZATION_PREVIEW_STALE: '配置已变化。请重新预检并确认中文差异，不要强制覆盖。',
  SAND_IAM_INITIALIZATION_ORGANIZATION_NOT_FOUND: '初始化包只能应用到已存在且启用的客户主体。',
  SAND_IAM_INITIALIZATION_RUN_NOT_FOUND: '记录可能已回滚或不存在，请刷新列表。',
  SAND_IAM_INITIALIZATION_ROLLBACK_INVALID: '只有已应用且无后续漂移的记录可以回滚。',
  SAND_IAM_INITIALIZATION_ROLLBACK_CONFIRMATION_INVALID:
    '回滚确认与当前记录不匹配。请重新打开记录后再确认。',
  SAND_IAM_INITIALIZATION_ROLLBACK_DRIFT:
    '初始化后又被修改。请先人工处理差异并重新预检，不要强制覆盖。',
  SAND_IAM_INITIALIZATION_BINDING_DRIFT: '绑定对象已不存在或不再匹配。请先修复数据再重新预检。',
  SAND_IAM_INITIALIZATION_BINDING_CONFLICT: '初始化键已绑定到其他对象。请先人工整理。',
  SAND_IAM_INITIALIZATION_POLICY_TARGET_CONFLICT: '策略修改后的目标已被占用。请先人工整理。',
  SAND_IAM_INITIALIZATION_POLICY_AMBIGUOUS: '现有策略存在重复自然键，请先人工整理。',
  SAND_IAM_INITIALIZATION_PROVIDER_SCOPE_CONFLICT: '同一客户主体已有其他范围的同名身份源。',
  SAND_IAM_INITIALIZATION_PROVIDER_MOUNT_MISSING: '请先修复身份源挂载关系，再重新预检。',
  SAND_IAM_INITIALIZATION_SENSITIVE_FIELD: '请删除密码、令牌、密钥或凭证字段后重新预检。',
  SAND_IAM_INITIALIZATION_UNKNOWN_FIELD: '请删除当前版本不认识的字段后重新预检。',
  SAND_IAM_INITIALIZATION_SECRET_REQUIRED: '外部身份源须在管理台单独配置密钥，不能写入初始化包。',
  SAND_IAM_INITIALIZATION_FORMAT_UNSUPPORTED: '初始化包版本不受支持，请重新导出当前版本的模板。',
  SAND_IAM_INITIALIZATION_TOO_LARGE: '请缩小初始化包后重试。',
  SAND_IAM_INITIALIZATION_REFERENCE_INVALID: '策略引用的角色或业务资源必须出现在同一初始化包中。',
  SAND_IAM_INITIALIZATION_ACTION_UNDECLARED: '请先在同一初始化包声明应用业务动作。',
  SAND_IAM_INITIALIZATION_RUN_INVALID: '请联系平台管理员核对运行记录，不要猜测回滚。',
  SAND_IAM_OIDC_BACKCHANNEL_URI_INVALID: '后通道地址必须是与登录回调同源的精确 HTTPS。',
  SAND_IAM_OIDC_BACKCHANNEL_DESTINATION_REJECTED: '目标主机解析结果不被接受。请核对登出地址。',
  SAND_IAM_OIDC_BACKCHANNEL_TRANSPORT_UNAVAILABLE:
    '当前环境不能投递后通道登出。页面不会显示已成功。',
  SAND_IAM_OIDC_BACKCHANNEL_DELIVERY_FAILED: '请根据后端结果重试；不要把配置保存当成已投递。'
}

/**
 * 应用用户请求失败时使用的本地传输错误。
 * 不依赖宿主 HttpError，避免把 check_admin 请求封装带进应用用户会话接口。
 */
export class SandIamTransportError extends Error {
  readonly http: number | null
  readonly data: Record<string, unknown> | null

  constructor(message: string, http: number | null, data: Record<string, unknown> | null) {
    super(message)
    this.name = 'SandIamTransportError'
    this.http = http
    this.data = data
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

function isTransportError(error: unknown): error is SandIamTransportError {
  return error instanceof SandIamTransportError
}

function readText(value: unknown): string {
  return typeof value === 'string' ? value : ''
}

function extractStableCode(text: string): StableCode | null {
  for (const code of STABLE_CODES) {
    if (text.includes(code)) return code
  }
  return null
}

function stableErrorDetail(code: StableCode): string {
  return RECOVERY[code]
}

export function describeSandIamError(error: unknown): SandIamRequestError {
  const http = isHttpError(error) ? error.code : isTransportError(error) ? error.http : null
  const body =
    isHttpError(error) && isRecord(error.data)
      ? error.data
      : isTransportError(error)
        ? error.data
        : null
  const combined = [
    error instanceof Error ? error.message : '',
    body ? readText(body.msg) : '',
    body ? readText(body.message) : '',
    body ? readText(body.code) : ''
  ]
    .filter((part) => part !== '')
    .join(' ')

  const code = extractStableCode(combined)

  if (code !== null) {
    return {
      code,
      http,
      title: LABELS[code],
      detail: stableErrorDetail(code)
    }
  }

  if (http === 503) {
    return {
      code: null,
      http,
      title: '服务暂时不可用',
      detail: '后台服务尚未准备好或暂时异常，请稍后重试；持续失败时请联系平台管理员。'
    }
  }

  if (http === 401) {
    return {
      code: null,
      http,
      title: '登录已失效',
      detail: '后台页面请重新登录；会话页需要使用当前应用用户自己的访问凭据。页面不会保留凭据明文。'
    }
  }

  if (http === 403) {
    return {
      code: null,
      http,
      title: '没有权限',
      detail: '当前账号无权执行此操作。请联系平台管理员确认页面权限和客户主体管理范围。'
    }
  }

  if (http === 409) {
    return {
      code: null,
      http,
      title: '与现有配置冲突',
      detail: '该接入应用已有同类配置，请编辑现有记录，不要重复新建。'
    }
  }

  if (http === 404) {
    return {
      code: null,
      http,
      title: '目标不存在',
      detail: '记录可能已被删除或撤销，请刷新后重试。'
    }
  }

  if (http !== null && http >= 500) {
    return {
      code: null,
      http,
      title: '后台服务发生异常',
      detail: `请求未完成（HTTP ${String(http)}），请稍后重试；持续失败时请联系平台管理员。`
    }
  }

  return {
    code: null,
    http,
    title: '请求未完成',
    detail: '请检查网络后重试；持续失败时请联系平台管理员。'
  }
}
