BEGIN;

CREATE TABLE IF NOT EXISTS sand_ai_provider (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(64) NOT NULL,
    name varchar(128) NOT NULL,
    adapter varchar(128) NOT NULL,
    encrypted_config jsonb NOT NULL DEFAULT '{}'::jsonb,
    timeout_ms integer NOT NULL DEFAULT 30000,
    status smallint NOT NULL DEFAULT 1,
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_ai_provider_code UNIQUE (code),
    CONSTRAINT ck_sand_ai_provider_timeout CHECK (timeout_ms > 0)
);

CREATE TABLE IF NOT EXISTS sand_ai_model (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(64) NOT NULL,
    name varchar(128) NOT NULL,
    type varchar(32) NOT NULL,
    capabilities jsonb NOT NULL DEFAULT '[]'::jsonb,
    status smallint NOT NULL DEFAULT 1,
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_ai_model_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS sand_ai_model_deployment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id bigint NOT NULL REFERENCES sand_ai_model(id) ON DELETE RESTRICT,
    provider_id bigint NOT NULL REFERENCES sand_ai_provider(id) ON DELETE RESTRICT,
    remote_model varchar(128) NOT NULL,
    config jsonb NOT NULL DEFAULT '{}'::jsonb,
    revision integer NOT NULL,
    status smallint NOT NULL DEFAULT 1,
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_ai_model_deployment_revision UNIQUE (model_id, revision),
    CONSTRAINT ck_sand_ai_model_deployment_revision CHECK (revision > 0)
);

CREATE TABLE IF NOT EXISTS sand_ai_config_revision (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_type varchar(64) NOT NULL,
    resource_id bigint NOT NULL,
    revision integer NOT NULL,
    payload jsonb NOT NULL,
    state varchar(16) NOT NULL,
    published_at timestamp(0) without time zone NULL,
    status smallint NOT NULL DEFAULT 1,
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_ai_config_revision UNIQUE (resource_type, resource_id, revision),
    CONSTRAINT ck_sand_ai_config_revision_state CHECK (state IN ('draft', 'tested', 'published', 'archived')),
    CONSTRAINT ck_sand_ai_config_revision_number CHECK (revision > 0)
);

CREATE TABLE IF NOT EXISTS sand_ai_invocation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id varchar(96) NOT NULL,
    -- SandIAM owns the referenced environment. Cross-plugin FK is deliberately
    -- avoided so this package remains installable against local or remote IAM.
    environment_id bigint NOT NULL,
    model_id bigint NULL REFERENCES sand_ai_model(id) ON DELETE RESTRICT,
    deployment_id bigint NULL REFERENCES sand_ai_model_deployment(id) ON DELETE RESTRICT,
    state varchar(24) NOT NULL,
    latency_ms integer NULL,
    error_code varchar(64) NULL,
    error_summary varchar(512) NULL,
    request_at timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamp(0) without time zone NULL,
    status smallint NOT NULL DEFAULT 1,
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_ai_invocation_request_id UNIQUE (request_id),
    CONSTRAINT ck_sand_ai_invocation_state CHECK (state IN ('queued', 'running', 'succeeded', 'failed', 'canceled')),
    CONSTRAINT ck_sand_ai_invocation_latency CHECK (latency_ms IS NULL OR latency_ms >= 0)
);

CREATE TABLE IF NOT EXISTS sand_ai_usage (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invocation_id bigint NOT NULL REFERENCES sand_ai_invocation(id) ON DELETE RESTRICT,
    input_tokens integer NOT NULL DEFAULT 0,
    output_tokens integer NOT NULL DEFAULT 0,
    total_tokens integer NOT NULL DEFAULT 0,
    cost_amount numeric(18, 6) NOT NULL DEFAULT 0,
    currency varchar(8) NOT NULL DEFAULT 'CNY',
    source varchar(32) NOT NULL,
    status smallint NOT NULL DEFAULT 1,
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_ai_usage_invocation UNIQUE (invocation_id),
    CONSTRAINT ck_sand_ai_usage_tokens CHECK (input_tokens >= 0 AND output_tokens >= 0 AND total_tokens >= 0),
    CONSTRAINT ck_sand_ai_usage_amount CHECK (cost_amount >= 0)
);

CREATE TABLE IF NOT EXISTS sand_ai_audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_type varchar(32) NOT NULL,
    actor_ref varchar(128) NOT NULL,
    action varchar(96) NOT NULL,
    resource_type varchar(64) NOT NULL,
    resource_id bigint NULL,
    summary varchar(512) NOT NULL,
    context jsonb NOT NULL DEFAULT '{}'::jsonb,
    status smallint NOT NULL DEFAULT 1,
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL
);

CREATE TABLE IF NOT EXISTS sand_ai_file (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment_id bigint NOT NULL,
    original_name varchar(512) NOT NULL,
    extension varchar(16) NOT NULL,
    media_type varchar(128) NOT NULL,
    size_bytes bigint NOT NULL,
    sha256 char(64) NOT NULL,
    storage_driver varchar(32) NOT NULL,
    object_key varchar(1024) NOT NULL,
    state varchar(24) NOT NULL DEFAULT 'uploaded',
    retention_until timestamp(0) without time zone NULL,
    status smallint NOT NULL DEFAULT 1,
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_ai_file_storage_object UNIQUE (storage_driver, object_key),
    CONSTRAINT ck_sand_ai_file_size CHECK (size_bytes > 0),
    CONSTRAINT ck_sand_ai_file_sha256 CHECK (sha256 ~ '^[a-f0-9]{64}$'),
    CONSTRAINT ck_sand_ai_file_state CHECK (state IN ('uploaded', 'parsing', 'parsed', 'parse_failed', 'deleting', 'delete_failed', 'deleted'))
);

CREATE TABLE IF NOT EXISTS sand_ai_file_parse (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id bigint NOT NULL REFERENCES sand_ai_file(id) ON DELETE RESTRICT,
    parser_code varchar(64) NOT NULL,
    parser_version varchar(32) NOT NULL,
    state varchar(24) NOT NULL,
    source_block_count integer NOT NULL DEFAULT 0,
    error_code varchar(64) NULL,
    error_summary varchar(512) NULL,
    started_at timestamp(0) without time zone NOT NULL,
    completed_at timestamp(0) without time zone NULL,
    status smallint NOT NULL DEFAULT 1,
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT ck_sand_ai_file_parse_state CHECK (state IN ('queued', 'running', 'succeeded', 'failed')),
    CONSTRAINT ck_sand_ai_file_parse_block_count CHECK (source_block_count >= 0)
);

CREATE TABLE IF NOT EXISTS sand_ai_source_block (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id bigint NOT NULL REFERENCES sand_ai_file(id) ON DELETE RESTRICT,
    parse_id bigint NOT NULL REFERENCES sand_ai_file_parse(id) ON DELETE RESTRICT,
    sequence_no integer NOT NULL,
    locator_type varchar(32) NOT NULL,
    locator jsonb NOT NULL DEFAULT '{}'::jsonb,
    content text NOT NULL,
    content_sha256 char(64) NOT NULL,
    char_count integer NOT NULL,
    status smallint NOT NULL DEFAULT 1,
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_ai_source_block_parse_sequence UNIQUE (parse_id, sequence_no),
    CONSTRAINT ck_sand_ai_source_block_sequence CHECK (sequence_no > 0),
    CONSTRAINT ck_sand_ai_source_block_content CHECK (char_length(content) > 0),
    CONSTRAINT ck_sand_ai_source_block_hash CHECK (content_sha256 ~ '^[a-f0-9]{64}$'),
    CONSTRAINT ck_sand_ai_source_block_char_count CHECK (char_count > 0)
);

CREATE INDEX IF NOT EXISTS idx_sand_ai_deployment_provider ON sand_ai_model_deployment (provider_id);
CREATE INDEX IF NOT EXISTS idx_sand_ai_config_revision_state ON sand_ai_config_revision (resource_type, resource_id, state);
CREATE INDEX IF NOT EXISTS idx_sand_ai_invocation_environment_time ON sand_ai_invocation (environment_id, request_at DESC);
CREATE INDEX IF NOT EXISTS idx_sand_ai_invocation_model_time ON sand_ai_invocation (model_id, request_at DESC);
CREATE INDEX IF NOT EXISTS idx_sand_ai_invocation_state_time ON sand_ai_invocation (state, request_at DESC);
CREATE INDEX IF NOT EXISTS idx_sand_ai_usage_time ON sand_ai_usage (create_time DESC);
CREATE INDEX IF NOT EXISTS idx_sand_ai_audit_resource_time ON sand_ai_audit_log (resource_type, resource_id, create_time DESC);
CREATE TABLE IF NOT EXISTS sand_ai_capability_profile (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment_id bigint NOT NULL,
    name varchar(128) NOT NULL,
    template_code varchar(64) NULL,
    data_egress_policy varchar(32) NOT NULL,
    revision integer NOT NULL,
    state varchar(16) NOT NULL DEFAULT 'draft',
    status smallint NOT NULL DEFAULT 2,
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_ai_capability_profile_environment_revision UNIQUE (environment_id, revision),
    CONSTRAINT ck_sand_ai_capability_profile_policy CHECK (data_egress_policy IN ('local_only', 'private_only', 'approved_cloud')),
    CONSTRAINT ck_sand_ai_capability_profile_state CHECK (state IN ('draft', 'published', 'archived')),
    CONSTRAINT ck_sand_ai_capability_profile_revision CHECK (revision > 0)
);

CREATE TABLE IF NOT EXISTS sand_ai_capability_route (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id bigint NOT NULL REFERENCES sand_ai_capability_profile(id) ON DELETE RESTRICT,
    capability_code varchar(64) NOT NULL,
    route_kind varchar(32) NOT NULL,
    deployment_id bigint NULL REFERENCES sand_ai_model_deployment(id) ON DELETE RESTRICT,
    driver_code varchar(128) NULL,
    priority integer NOT NULL,
    config jsonb NOT NULL DEFAULT '{}'::jsonb,
    status smallint NOT NULL DEFAULT 1,
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_ai_capability_route_priority UNIQUE (profile_id, capability_code, priority),
    CONSTRAINT ck_sand_ai_capability_route_kind CHECK (route_kind IN ('model_deployment', 'parse_driver')),
    CONSTRAINT ck_sand_ai_capability_route_priority CHECK (priority > 0),
    CONSTRAINT ck_sand_ai_capability_route_target CHECK (
        (route_kind = 'model_deployment' AND deployment_id IS NOT NULL AND driver_code IS NULL)
        OR (route_kind = 'parse_driver' AND deployment_id IS NULL AND driver_code IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS sand_ai_task_run (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment_id bigint NOT NULL,
    task_type varchar(64) NOT NULL,
    resource_type varchar(64) NOT NULL,
    resource_id bigint NOT NULL,
    file_parse_id bigint NULL REFERENCES sand_ai_file_parse(id) ON DELETE RESTRICT,
    request_id varchar(64) NOT NULL,
    state varchar(16) NOT NULL DEFAULT 'queued',
    attempt_count integer NOT NULL DEFAULT 0,
    max_attempts integer NOT NULL DEFAULT 3,
    available_at timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    locked_at timestamp(0) without time zone NULL,
    locked_by varchar(128) NULL,
    started_at timestamp(0) without time zone NULL,
    completed_at timestamp(0) without time zone NULL,
    canceled_at timestamp(0) without time zone NULL,
    input jsonb NOT NULL DEFAULT '{}'::jsonb,
    result jsonb NOT NULL DEFAULT '{}'::jsonb,
    error_code varchar(64) NULL,
    error_summary varchar(500) NULL,
    status smallint NOT NULL DEFAULT 1,
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_ai_task_run_environment_request UNIQUE (environment_id, request_id),
    CONSTRAINT uk_sand_ai_task_run_file_parse UNIQUE (file_parse_id),
    CONSTRAINT ck_sand_ai_task_run_state CHECK (state IN ('queued', 'running', 'retrying', 'succeeded', 'failed', 'canceled')),
    CONSTRAINT ck_sand_ai_task_run_attempt_count CHECK (attempt_count >= 0 AND attempt_count <= max_attempts),
    CONSTRAINT ck_sand_ai_task_run_max_attempts CHECK (max_attempts > 0)
);

CREATE TABLE IF NOT EXISTS sand_ai_task_step (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id bigint NOT NULL REFERENCES sand_ai_task_run(id) ON DELETE RESTRICT,
    step_code varchar(64) NOT NULL,
    sequence_no integer NOT NULL,
    state varchar(16) NOT NULL DEFAULT 'queued',
    attempt_count integer NOT NULL DEFAULT 0,
    started_at timestamp(0) without time zone NULL,
    completed_at timestamp(0) without time zone NULL,
    context jsonb NOT NULL DEFAULT '{}'::jsonb,
    error_code varchar(64) NULL,
    error_summary varchar(500) NULL,
    status smallint NOT NULL DEFAULT 1,
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_ai_task_step_sequence UNIQUE (task_id, sequence_no),
    CONSTRAINT ck_sand_ai_task_step_state CHECK (state IN ('queued', 'running', 'retrying', 'succeeded', 'failed', 'canceled')),
    CONSTRAINT ck_sand_ai_task_step_sequence CHECK (sequence_no > 0),
    CONSTRAINT ck_sand_ai_task_step_attempt_count CHECK (attempt_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_sand_ai_audit_action_time ON sand_ai_audit_log (action, create_time DESC);
CREATE INDEX IF NOT EXISTS idx_sand_ai_file_environment_time ON sand_ai_file (environment_id, create_time DESC);
CREATE INDEX IF NOT EXISTS idx_sand_ai_file_environment_hash ON sand_ai_file (environment_id, sha256);
CREATE INDEX IF NOT EXISTS idx_sand_ai_file_parse_file_time ON sand_ai_file_parse (file_id, create_time DESC);
CREATE INDEX IF NOT EXISTS idx_sand_ai_source_block_file_sequence ON sand_ai_source_block (file_id, sequence_no);
CREATE INDEX IF NOT EXISTS idx_sand_ai_task_run_claim ON sand_ai_task_run (state, available_at, id) WHERE status = 1 AND delete_time IS NULL;
CREATE INDEX IF NOT EXISTS idx_sand_ai_task_run_environment_time ON sand_ai_task_run (environment_id, create_time DESC);
CREATE INDEX IF NOT EXISTS idx_sand_ai_task_step_task_sequence ON sand_ai_task_step (task_id, sequence_no);
CREATE UNIQUE INDEX IF NOT EXISTS uk_sand_ai_task_run_active_resource ON sand_ai_task_run (environment_id, task_type, resource_type, resource_id) WHERE state IN ('queued', 'running', 'retrying') AND status = 1 AND delete_time IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uk_sand_ai_capability_profile_published_environment ON sand_ai_capability_profile (environment_id) WHERE state = 'published' AND status = 1 AND delete_time IS NULL;
CREATE INDEX IF NOT EXISTS idx_sand_ai_capability_route_profile_capability ON sand_ai_capability_route (profile_id, capability_code, priority);

CREATE INDEX IF NOT EXISTS idx_sand_ai_source_block_fts
    ON sand_ai_source_block
    USING GIN (to_tsvector('simple', content));

CREATE INDEX IF NOT EXISTS idx_sand_ai_file_environment_state
    ON sand_ai_file (environment_id, state, status, id);

COMMIT;
