-- IAM-05: scope identity providers and subjects to one application.
-- Existing bindings are assigned to generated legacy providers before the
-- former global provider_code + subject unique constraint is removed.
BEGIN;

CREATE TABLE IF NOT EXISTS sand_iam_identity_provider (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL REFERENCES sand_iam_application(id) ON DELETE RESTRICT,
    code varchar(64) NOT NULL,
    name varchar(128) NOT NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_identity_provider_application_code UNIQUE (application_id, code),
    CONSTRAINT uk_sand_iam_identity_provider_id_application UNIQUE (id, application_id)
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_identity_provider_application_id ON sand_iam_identity_provider (application_id);

ALTER TABLE sand_iam_identity_binding
    ADD COLUMN IF NOT EXISTS application_id bigint NULL,
    ADD COLUMN IF NOT EXISTS identity_provider_id bigint NULL;

UPDATE sand_iam_identity_binding binding
SET application_id = identity_record.application_id
FROM sand_iam_identity identity_record
WHERE binding.identity_id = identity_record.id
  AND binding.application_id IS NULL;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_attribute
        WHERE attrelid = 'sand_iam_identity_binding'::regclass
          AND attname = 'provider_code'
          AND NOT attisdropped
    ) THEN
        INSERT INTO sand_iam_identity_provider (
            application_id, code, name, status, created_by, updated_by, create_time, update_time
        )
        SELECT
            identity_record.application_id,
            binding.provider_code,
            '兼容身份源：' || binding.provider_code,
            1,
            MIN(binding.created_by),
            MIN(binding.updated_by),
            MIN(binding.create_time),
            MAX(binding.update_time)
        FROM sand_iam_identity_binding binding
        INNER JOIN sand_iam_identity identity_record ON identity_record.id = binding.identity_id
        GROUP BY identity_record.application_id, binding.provider_code
        ON CONFLICT (application_id, code) DO NOTHING;

        UPDATE sand_iam_identity_binding binding
        SET identity_provider_id = provider.id
        FROM sand_iam_identity identity_record,
             sand_iam_identity_provider provider
        WHERE binding.identity_id = identity_record.id
          AND provider.application_id = identity_record.application_id
          AND provider.code = binding.provider_code
          AND binding.identity_provider_id IS NULL;

        IF EXISTS (
            SELECT 1
            FROM sand_iam_identity_binding
            WHERE identity_provider_id IS NULL
        ) THEN
            RAISE EXCEPTION 'SandIAM identity binding migration could not resolve every provider_code';
        END IF;

        ALTER TABLE sand_iam_identity_binding
            DROP CONSTRAINT IF EXISTS uk_sand_iam_identity_binding_provider_subject;
        ALTER TABLE sand_iam_identity_binding
            DROP COLUMN provider_code;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uk_sand_iam_identity_id_application'
          AND conrelid = 'sand_iam_identity'::regclass
    ) THEN
        ALTER TABLE sand_iam_identity
            ADD CONSTRAINT uk_sand_iam_identity_id_application UNIQUE (id, application_id);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uk_sand_iam_identity_provider_id_application'
          AND conrelid = 'sand_iam_identity_provider'::regclass
    ) THEN
        ALTER TABLE sand_iam_identity_provider
            ADD CONSTRAINT uk_sand_iam_identity_provider_id_application UNIQUE (id, application_id);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_sand_iam_identity_binding_identity_application'
          AND conrelid = 'sand_iam_identity_binding'::regclass
    ) THEN
        ALTER TABLE sand_iam_identity_binding
            ADD CONSTRAINT fk_sand_iam_identity_binding_identity_application
            FOREIGN KEY (identity_id, application_id) REFERENCES sand_iam_identity(id, application_id) ON DELETE RESTRICT;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_sand_iam_identity_binding_provider_application'
          AND conrelid = 'sand_iam_identity_binding'::regclass
    ) THEN
        ALTER TABLE sand_iam_identity_binding
            ADD CONSTRAINT fk_sand_iam_identity_binding_provider_application
            FOREIGN KEY (identity_provider_id, application_id) REFERENCES sand_iam_identity_provider(id, application_id) ON DELETE RESTRICT;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'sand_iam_identity_binding'
          AND column_name = 'identity_provider_id'
          AND is_nullable = 'YES'
    ) THEN
        ALTER TABLE sand_iam_identity_binding
            ALTER COLUMN identity_provider_id SET NOT NULL;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'sand_iam_identity_binding'
          AND column_name = 'application_id'
          AND is_nullable = 'YES'
    ) THEN
        ALTER TABLE sand_iam_identity_binding
            ALTER COLUMN application_id SET NOT NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uk_sand_iam_identity_binding_provider_subject'
          AND conrelid = 'sand_iam_identity_binding'::regclass
    ) THEN
        ALTER TABLE sand_iam_identity_binding
            ADD CONSTRAINT uk_sand_iam_identity_binding_provider_subject
            UNIQUE (identity_provider_id, subject);
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_sand_iam_identity_binding_provider_id
    ON sand_iam_identity_binding (identity_provider_id);
CREATE INDEX IF NOT EXISTS idx_sand_iam_identity_binding_application_id
    ON sand_iam_identity_binding (application_id);

COMMIT;
