-- SandIAM 0.3.0 human authentication core. This migration is immutable.
BEGIN;

CREATE TABLE IF NOT EXISTS sand_iam_identity_auth (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL,
    identity_id bigint NOT NULL,
    username varchar(64) NOT NULL,
    email varchar(320) NULL,
    phone varchar(16) NULL,
    password_hash varchar(255) NOT NULL,
    password_changed_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email_verified_time timestamp(0) without time zone NULL,
    phone_verified_time timestamp(0) without time zone NULL,
    last_login_time timestamp(0) without time zone NULL,
    failed_login_count integer NOT NULL DEFAULT 0 CHECK (failed_login_count >= 0),
    locked_until timestamp(0) without time zone NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_identity_auth_identity UNIQUE (identity_id),
    CONSTRAINT uk_sand_iam_identity_auth_identity_application UNIQUE (identity_id, application_id),
    CONSTRAINT uk_sand_iam_identity_auth_application_username UNIQUE (application_id, username),
    CONSTRAINT fk_sand_iam_identity_auth_identity_application FOREIGN KEY (identity_id, application_id) REFERENCES sand_iam_identity(id, application_id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_sand_iam_identity_auth_application_email ON sand_iam_identity_auth (application_id, email) WHERE email IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uk_sand_iam_identity_auth_application_phone ON sand_iam_identity_auth (application_id, phone) WHERE phone IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_sand_iam_identity_auth_application_active ON sand_iam_identity_auth (application_id, status);

CREATE TABLE IF NOT EXISTS sand_iam_auth_session (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL,
    identity_id bigint NOT NULL,
    access_token_hash char(64) NOT NULL,
    refresh_token_hash char(64) NOT NULL,
    previous_refresh_token_hash char(64) NULL,
    access_expire_time timestamp(0) without time zone NOT NULL,
    refresh_expire_time timestamp(0) without time zone NOT NULL,
    last_used_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_time timestamp(0) without time zone NULL,
    ip_hash char(64) NOT NULL,
    user_agent varchar(255) NOT NULL DEFAULT '',
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_auth_session_access_token_hash UNIQUE (access_token_hash),
    CONSTRAINT uk_sand_iam_auth_session_refresh_token_hash UNIQUE (refresh_token_hash),
    CONSTRAINT uk_sand_iam_auth_session_previous_refresh_token_hash UNIQUE (previous_refresh_token_hash),
    CONSTRAINT fk_sand_iam_auth_session_identity_application FOREIGN KEY (identity_id, application_id) REFERENCES sand_iam_identity(id, application_id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_auth_session_identity_active ON sand_iam_auth_session (application_id, identity_id, status, refresh_expire_time);

CREATE TABLE IF NOT EXISTS sand_iam_auth_verification (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL,
    identity_id bigint NOT NULL,
    purpose varchar(32) NOT NULL CHECK (purpose IN ('email_verify', 'phone_verify', 'password_reset')),
    channel varchar(16) NOT NULL CHECK (channel IN ('email', 'phone')),
    destination_hash char(64) NOT NULL,
    code_hash char(64) NOT NULL,
    expire_time timestamp(0) without time zone NOT NULL,
    consumed_time timestamp(0) without time zone NULL,
    attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT fk_sand_iam_auth_verification_identity_application FOREIGN KEY (identity_id, application_id) REFERENCES sand_iam_identity(id, application_id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_auth_verification_active ON sand_iam_auth_verification (application_id, identity_id, purpose, channel, status, expire_time);

CREATE TABLE IF NOT EXISTS sand_iam_auth_rate_limit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL REFERENCES sand_iam_application(id) ON DELETE RESTRICT,
    action varchar(32) NOT NULL,
    subject_hash char(64) NOT NULL,
    window_start timestamp(0) without time zone NOT NULL,
    attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_auth_rate_limit_application_action_subject UNIQUE (application_id, action, subject_hash)
);

ALTER TABLE sand_iam_identity_auth ADD COLUMN IF NOT EXISTS pepper_version varchar(32) NOT NULL DEFAULT 'v1';
ALTER TABLE sand_iam_auth_session ADD COLUMN IF NOT EXISTS pepper_version varchar(32) NOT NULL DEFAULT 'v1';
ALTER TABLE sand_iam_auth_verification ADD COLUMN IF NOT EXISTS pepper_version varchar(32) NOT NULL DEFAULT 'v1';

CREATE TABLE IF NOT EXISTS sand_iam_auth_refresh_token (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id bigint NOT NULL REFERENCES sand_iam_auth_session(id) ON DELETE RESTRICT,
    token_hash char(64) NOT NULL,
    pepper_version varchar(32) NOT NULL,
    expire_time timestamp(0) without time zone NOT NULL,
    used_time timestamp(0) without time zone NULL,
    revoked_time timestamp(0) without time zone NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_auth_refresh_token_hash UNIQUE (token_hash)
);
ALTER TABLE sand_iam_auth_rate_limit ADD COLUMN IF NOT EXISTS delete_time timestamp(0) without time zone NULL;
ALTER TABLE sand_iam_auth_refresh_token ADD COLUMN IF NOT EXISTS delete_time timestamp(0) without time zone NULL;
CREATE INDEX IF NOT EXISTS idx_sand_iam_auth_refresh_token_session_active ON sand_iam_auth_refresh_token (session_id, status, expire_time);

CREATE TABLE IF NOT EXISTS sand_iam_auth_policy (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL REFERENCES sand_iam_application(id) ON DELETE RESTRICT,
    password_min_length integer NOT NULL DEFAULT 12 CHECK (password_min_length BETWEEN 12 AND 128),
    password_max_length integer NOT NULL DEFAULT 128 CHECK (password_max_length BETWEEN 12 AND 128),
    require_uppercase smallint NOT NULL DEFAULT 1 CHECK (require_uppercase IN (1, 2)),
    require_lowercase smallint NOT NULL DEFAULT 1 CHECK (require_lowercase IN (1, 2)),
    require_digit smallint NOT NULL DEFAULT 1 CHECK (require_digit IN (1, 2)),
    require_symbol smallint NOT NULL DEFAULT 1 CHECK (require_symbol IN (1, 2)),
    require_email_verification smallint NOT NULL DEFAULT 2 CHECK (require_email_verification IN (1, 2)),
    require_phone_verification smallint NOT NULL DEFAULT 2 CHECK (require_phone_verification IN (1, 2)),
    access_token_ttl_seconds integer NOT NULL DEFAULT 900 CHECK (access_token_ttl_seconds BETWEEN 60 AND 3600),
    refresh_token_ttl_seconds integer NOT NULL DEFAULT 2592000 CHECK (refresh_token_ttl_seconds BETWEEN 300 AND 7776000),
    verification_ttl_seconds integer NOT NULL DEFAULT 600 CHECK (verification_ttl_seconds BETWEEN 60 AND 3600),
    max_login_failures integer NOT NULL DEFAULT 5 CHECK (max_login_failures BETWEEN 3 AND 20),
    lock_seconds integer NOT NULL DEFAULT 900 CHECK (lock_seconds BETWEEN 60 AND 86400),
    rate_limit_per_minute integer NOT NULL DEFAULT 10 CHECK (rate_limit_per_minute BETWEEN 1 AND 1000),
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    created_by bigint NULL, updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_auth_policy_application UNIQUE (application_id),
    CONSTRAINT ck_sand_iam_auth_policy_password_range CHECK (password_min_length <= password_max_length)
);
ALTER TABLE sand_iam_auth_policy ADD COLUMN IF NOT EXISTS registration_enabled smallint NOT NULL DEFAULT 2 CHECK (registration_enabled IN (1, 2));

COMMIT;
