-- IAM-T02-004 BEGIN: SandIAM MFA and Passkey migration.
BEGIN;

ALTER TABLE sand_iam_auth_policy
    ADD COLUMN IF NOT EXISTS webauthn_rp_id varchar(255) NULL,
    ADD COLUMN IF NOT EXISTS webauthn_allowed_origins jsonb NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS webauthn_user_verification varchar(16) NOT NULL DEFAULT 'required';
DO $$ BEGIN
    ALTER TABLE sand_iam_auth_policy ADD CONSTRAINT ck_sand_iam_auth_policy_webauthn_uv CHECK (webauthn_user_verification IN ('required', 'preferred', 'discouraged'));
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE sand_iam_identity ADD CONSTRAINT uk_sand_iam_identity_id_application UNIQUE (id, application_id);
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS sand_iam_mfa_factor (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL REFERENCES sand_iam_application(id) ON DELETE RESTRICT,
    identity_id bigint NOT NULL,
    type varchar(16) NOT NULL CHECK (type = 'totp'),
    name varchar(128) NOT NULL,
    encrypted_secret text NULL,
    encryption_version varchar(32) NULL,
    last_used_counter bigint NULL CHECK (last_used_counter >= 0),
    last_used_time timestamp(0) without time zone NULL,
    revoked_time timestamp(0) without time zone NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT ck_sand_iam_mfa_factor_material CHECK (encrypted_secret IS NOT NULL),
    CONSTRAINT uk_sand_iam_mfa_factor_id_application_identity UNIQUE (id, application_id, identity_id),
    CONSTRAINT fk_sand_iam_mfa_factor_identity_application FOREIGN KEY (identity_id, application_id) REFERENCES sand_iam_identity(id, application_id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_mfa_factor_identity_active ON sand_iam_mfa_factor (application_id, identity_id, status, type);
CREATE UNIQUE INDEX IF NOT EXISTS uk_sand_iam_mfa_factor_identity_active_totp ON sand_iam_mfa_factor (application_id, identity_id) WHERE status = 1 AND delete_time IS NULL;

CREATE TABLE IF NOT EXISTS sand_iam_mfa_recovery_code (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL REFERENCES sand_iam_application(id) ON DELETE RESTRICT,
    identity_id bigint NOT NULL,
    factor_id bigint NOT NULL,
    code_hash char(64) NOT NULL,
    generation bigint NOT NULL,
    used_time timestamp(0) without time zone NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_mfa_recovery_code_hash UNIQUE (application_id, code_hash),
    CONSTRAINT fk_sand_iam_mfa_recovery_identity_application FOREIGN KEY (identity_id, application_id) REFERENCES sand_iam_identity(id, application_id) ON DELETE RESTRICT,
    CONSTRAINT fk_sand_iam_mfa_recovery_factor_scope FOREIGN KEY (factor_id, application_id, identity_id) REFERENCES sand_iam_mfa_factor(id, application_id, identity_id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_mfa_recovery_code_identity_active ON sand_iam_mfa_recovery_code (application_id, identity_id, status);

CREATE TABLE IF NOT EXISTS sand_iam_auth_challenge (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL REFERENCES sand_iam_application(id) ON DELETE RESTRICT,
    identity_id bigint NULL,
    purpose varchar(32) NOT NULL CHECK (purpose IN ('mfa_login', 'webauthn_register', 'webauthn_auth')),
    token_hash char(64) NOT NULL,
    encrypted_challenge text NOT NULL,
    encrypted_user_handle text NULL,
    encryption_version varchar(32) NOT NULL,
    context jsonb NOT NULL DEFAULT '{}'::jsonb,
    expire_time timestamp(0) without time zone NOT NULL,
    consumed_time timestamp(0) without time zone NULL,
    attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count BETWEEN 0 AND 5),
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_auth_challenge_token UNIQUE (token_hash),
    CONSTRAINT ck_sand_iam_auth_challenge_identity CHECK ((purpose = 'webauthn_auth' AND identity_id IS NULL) OR (purpose <> 'webauthn_auth' AND identity_id IS NOT NULL)),
    CONSTRAINT fk_sand_iam_auth_challenge_identity_application FOREIGN KEY (identity_id, application_id) REFERENCES sand_iam_identity(id, application_id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_auth_challenge_active ON sand_iam_auth_challenge (application_id, purpose, status, expire_time);

CREATE TABLE IF NOT EXISTS sand_iam_webauthn_credential (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL REFERENCES sand_iam_application(id) ON DELETE RESTRICT,
    identity_id bigint NOT NULL,
    name varchar(128) NOT NULL,
    credential_id varchar(1400) NOT NULL,
    public_key text NOT NULL,
    user_handle varchar(128) NOT NULL,
    sign_count bigint NOT NULL DEFAULT 0 CHECK (sign_count >= 0),
    last_used_time timestamp(0) without time zone NULL,
    revoked_time timestamp(0) without time zone NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_webauthn_credential_application_credential UNIQUE (application_id, credential_id),
    CONSTRAINT fk_sand_iam_webauthn_credential_identity_application FOREIGN KEY (identity_id, application_id) REFERENCES sand_iam_identity(id, application_id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_webauthn_credential_identity_active ON sand_iam_webauthn_credential (application_id, identity_id, status);

COMMIT;
