-- IAM-T04-006 BEGIN: application-scoped federation, directory and SCIM.
-- Secrets stay in encrypted_config/token_hash.  Raw directory credentials,
-- bearer tokens and assertion payloads are never persisted.

ALTER TABLE sand_iam_identity_provider
    ADD COLUMN IF NOT EXISTS scope_type varchar(16) NOT NULL DEFAULT 'application',
    ADD COLUMN IF NOT EXISTS organization_id bigint NULL,
    ADD COLUMN IF NOT EXISTS public_code varchar(64) NOT NULL DEFAULT ('ip_' || md5(random()::text || clock_timestamp()::text)),
    ADD COLUMN IF NOT EXISTS provider_type varchar(16) NOT NULL DEFAULT 'local',
    ADD COLUMN IF NOT EXISTS encrypted_config text NULL,
    ADD COLUMN IF NOT EXISTS attribute_mapping jsonb NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS conflict_policy varchar(16) NOT NULL DEFAULT 'reject',
    ADD COLUMN IF NOT EXISTS sync_cursor varchar(512) NULL,
    ADD COLUMN IF NOT EXISTS last_sync_time timestamp(0) without time zone NULL;

UPDATE sand_iam_identity_provider provider
SET organization_id = application.organization_id
FROM sand_iam_application application
WHERE provider.application_id = application.id AND provider.organization_id IS NULL;

ALTER TABLE sand_iam_identity_provider
    ALTER COLUMN organization_id SET NOT NULL,
    ALTER COLUMN application_id DROP NOT NULL,
    DROP CONSTRAINT IF EXISTS ck_sand_iam_identity_provider_type,
    DROP CONSTRAINT IF EXISTS ck_sand_iam_identity_provider_conflict_policy,
    DROP CONSTRAINT IF EXISTS ck_sand_iam_identity_provider_scope;
ALTER TABLE sand_iam_identity_provider
    ADD CONSTRAINT ck_sand_iam_identity_provider_type CHECK (provider_type IN ('local', 'oidc', 'oauth2', 'saml', 'ldap', 'scim', 'kerberos')),
    ADD CONSTRAINT ck_sand_iam_identity_provider_conflict_policy CHECK (conflict_policy IN ('reject', 'link_verified', 'create')),
    ADD CONSTRAINT ck_sand_iam_identity_provider_scope CHECK ((scope_type = 'application' AND application_id IS NOT NULL) OR (scope_type = 'organization' AND application_id IS NULL));
DO $$ BEGIN
    ALTER TABLE sand_iam_identity_provider ADD CONSTRAINT uk_sand_iam_identity_provider_public_code UNIQUE (public_code);
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE sand_iam_identity_provider ADD CONSTRAINT fk_sand_iam_identity_provider_organization FOREIGN KEY (organization_id) REFERENCES sand_iam_organization(id) ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
ALTER TABLE sand_iam_identity_provider
    ADD COLUMN IF NOT EXISTS scope_application_key bigint GENERATED ALWAYS AS (COALESCE(application_id, 0)) STORED;
DO $$ BEGIN
    ALTER TABLE sand_iam_application ADD CONSTRAINT uk_sand_iam_application_id_organization UNIQUE (id, organization_id);
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE sand_iam_identity_provider ADD CONSTRAINT uk_sand_iam_identity_provider_scope_key UNIQUE (id, organization_id, scope_application_key);
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE sand_iam_identity_provider ADD CONSTRAINT fk_sand_iam_identity_provider_application_organization FOREIGN KEY (application_id, organization_id) REFERENCES sand_iam_application(id, organization_id) ON DELETE RESTRICT;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_sand_iam_identity_provider_type_status ON sand_iam_identity_provider (organization_id, provider_type, status);
CREATE UNIQUE INDEX IF NOT EXISTS uk_sand_iam_identity_provider_organization_code ON sand_iam_identity_provider (organization_id, code) WHERE scope_type = 'organization';

CREATE TABLE IF NOT EXISTS sand_iam_identity_provider_application (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_provider_id bigint NOT NULL,
    application_id bigint NOT NULL,
    organization_id bigint NOT NULL,
    provider_scope_application_key bigint NOT NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sand_iam_identity_provider_application UNIQUE (identity_provider_id, application_id),
    CONSTRAINT ck_sand_iam_identity_provider_application_scope CHECK (provider_scope_application_key = 0 OR provider_scope_application_key = application_id),
    CONSTRAINT fk_sand_iam_identity_provider_application_provider FOREIGN KEY (identity_provider_id, organization_id, provider_scope_application_key) REFERENCES sand_iam_identity_provider(id, organization_id, scope_application_key) ON DELETE RESTRICT,
    CONSTRAINT fk_sand_iam_identity_provider_application_application FOREIGN KEY (application_id, organization_id) REFERENCES sand_iam_application(id, organization_id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_identity_provider_application_application ON sand_iam_identity_provider_application (application_id, status);
INSERT INTO sand_iam_identity_provider_application (identity_provider_id, application_id, organization_id, provider_scope_application_key, status)
SELECT id, application_id, organization_id, scope_application_key, status FROM sand_iam_identity_provider WHERE application_id IS NOT NULL
ON CONFLICT (identity_provider_id, application_id) DO NOTHING;

ALTER TABLE sand_iam_identity_binding
    DROP CONSTRAINT IF EXISTS fk_sand_iam_identity_binding_provider_application,
    DROP CONSTRAINT IF EXISTS uk_sand_iam_identity_binding_provider_subject,
    DROP CONSTRAINT IF EXISTS uk_sand_iam_identity_binding_provider_application_subject;
ALTER TABLE sand_iam_identity_binding
    ADD CONSTRAINT fk_sand_iam_identity_binding_provider_application FOREIGN KEY (identity_provider_id, application_id) REFERENCES sand_iam_identity_provider_application(identity_provider_id, application_id) ON DELETE RESTRICT,
    ADD CONSTRAINT uk_sand_iam_identity_binding_provider_application_subject UNIQUE (identity_provider_id, application_id, subject);

CREATE TABLE IF NOT EXISTS sand_iam_federation_transaction (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL,
    identity_provider_id bigint NOT NULL,
    protocol varchar(16) NOT NULL CHECK (protocol IN ('oidc', 'saml')),
    purpose varchar(16) NOT NULL DEFAULT 'login' CHECK (purpose IN ('login', 'link')),
    state_hash char(64) NOT NULL,
    browser_binding_hash char(64) NULL,
    saml_request_id varchar(191) NULL,
    nonce_hash char(64) NULL,
    assertion_hash char(64) NULL,
    encrypted_pkce_verifier text NULL,
    redirect_uri varchar(2048) NULL,
    expire_time timestamp(0) without time zone NOT NULL,
    consumed_time timestamp(0) without time zone NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sand_iam_federation_transaction_state UNIQUE (state_hash),
    CONSTRAINT fk_sand_iam_federation_transaction_provider_application FOREIGN KEY (identity_provider_id, application_id) REFERENCES sand_iam_identity_provider_application(identity_provider_id, application_id) ON DELETE RESTRICT
);
ALTER TABLE sand_iam_federation_transaction ADD COLUMN IF NOT EXISTS assertion_hash char(64) NULL;
ALTER TABLE sand_iam_federation_transaction ADD COLUMN IF NOT EXISTS purpose varchar(16) NOT NULL DEFAULT 'login';
ALTER TABLE sand_iam_federation_transaction ADD COLUMN IF NOT EXISTS browser_binding_hash char(64) NULL;
ALTER TABLE sand_iam_federation_transaction ADD COLUMN IF NOT EXISTS saml_request_id varchar(191) NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uk_sand_iam_federation_transaction_assertion ON sand_iam_federation_transaction (identity_provider_id, application_id, assertion_hash) WHERE assertion_hash IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_sand_iam_federation_transaction_provider_expire ON sand_iam_federation_transaction (identity_provider_id, expire_time);

ALTER TABLE sand_iam_auth_session
    ADD COLUMN IF NOT EXISTS auth_method varchar(32) NOT NULL DEFAULT 'local_password',
    ADD COLUMN IF NOT EXISTS identity_binding_id bigint NULL;
ALTER TABLE sand_iam_auth_session DROP CONSTRAINT IF EXISTS ck_sand_iam_auth_session_auth_method;
ALTER TABLE sand_iam_auth_session ADD CONSTRAINT ck_sand_iam_auth_session_auth_method CHECK (auth_method IN ('local_password', 'federation'));
DO $$ BEGIN ALTER TABLE sand_iam_auth_session ADD CONSTRAINT fk_sand_iam_auth_session_identity_binding FOREIGN KEY (identity_binding_id) REFERENCES sand_iam_identity_binding(id) ON DELETE RESTRICT; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_sand_iam_auth_session_binding_active ON sand_iam_auth_session (identity_binding_id, status);

CREATE TABLE IF NOT EXISTS sand_iam_directory_sync_run (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL,
    identity_provider_id bigint NOT NULL,
    state varchar(16) NOT NULL CHECK (state IN ('running', 'succeeded', 'failed', 'partial')),
    cursor_before varchar(512) NULL,
    cursor_after varchar(512) NULL,
    processed_count integer NOT NULL DEFAULT 0 CHECK (processed_count >= 0),
    failed_count integer NOT NULL DEFAULT 0 CHECK (failed_count >= 0),
    error_code varchar(96) NULL,
    start_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finish_time timestamp(0) without time zone NULL,
    CONSTRAINT fk_sand_iam_directory_sync_run_provider_application FOREIGN KEY (identity_provider_id, application_id) REFERENCES sand_iam_identity_provider_application(identity_provider_id, application_id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_directory_sync_run_provider_start ON sand_iam_directory_sync_run (identity_provider_id, start_time DESC);

CREATE TABLE IF NOT EXISTS sand_iam_scim_token (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL,
    identity_provider_id bigint NOT NULL,
    name varchar(128) NOT NULL,
    token_hash char(64) NOT NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    expire_time timestamp(0) without time zone NULL,
    last_used_time timestamp(0) without time zone NULL,
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_scim_token_hash UNIQUE (token_hash),
    CONSTRAINT uk_sand_iam_scim_token_provider_name UNIQUE (identity_provider_id, name),
    CONSTRAINT fk_sand_iam_scim_token_provider_application FOREIGN KEY (identity_provider_id, application_id) REFERENCES sand_iam_identity_provider_application(identity_provider_id, application_id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_scim_token_provider_status ON sand_iam_scim_token (identity_provider_id, status);

CREATE TABLE IF NOT EXISTS sand_iam_scim_group (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL,
    identity_provider_id bigint NOT NULL,
    external_id varchar(191) NOT NULL,
    display_name varchar(256) NOT NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sand_iam_scim_group_provider_external UNIQUE (identity_provider_id, application_id, external_id),
    CONSTRAINT uk_sand_iam_scim_group_id_application UNIQUE (id, application_id),
    CONSTRAINT fk_sand_iam_scim_group_provider_application FOREIGN KEY (identity_provider_id, application_id) REFERENCES sand_iam_identity_provider_application(identity_provider_id, application_id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_scim_group_application_id ON sand_iam_scim_group (application_id);
ALTER TABLE sand_iam_scim_group
    ADD COLUMN IF NOT EXISTS scim_id varchar(64) NULL,
    ADD COLUMN IF NOT EXISTS version bigint NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS source_state varchar(16) NOT NULL DEFAULT 'active',
    ADD COLUMN IF NOT EXISTS source_attributes jsonb NOT NULL DEFAULT '{}'::jsonb;
UPDATE sand_iam_scim_group SET scim_id = 'sg_' || md5(id::text || clock_timestamp()::text) WHERE scim_id IS NULL;
ALTER TABLE sand_iam_scim_group ALTER COLUMN scim_id SET NOT NULL;
DO $$ BEGIN ALTER TABLE sand_iam_scim_group ADD CONSTRAINT uk_sand_iam_scim_group_scim_id UNIQUE (scim_id); EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
ALTER TABLE sand_iam_scim_group DROP CONSTRAINT IF EXISTS ck_sand_iam_scim_group_source_state;
ALTER TABLE sand_iam_scim_group ADD CONSTRAINT ck_sand_iam_scim_group_source_state CHECK (source_state IN ('active', 'disabled', 'deleted'));

CREATE TABLE IF NOT EXISTS sand_iam_scim_group_member (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL,
    group_id bigint NOT NULL,
    identity_id bigint NOT NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sand_iam_scim_group_member UNIQUE (group_id, identity_id),
    CONSTRAINT fk_sand_iam_scim_group_member_group_application FOREIGN KEY (group_id, application_id) REFERENCES sand_iam_scim_group(id, application_id) ON DELETE RESTRICT,
    CONSTRAINT fk_sand_iam_scim_group_member_identity_application FOREIGN KEY (identity_id, application_id) REFERENCES sand_iam_identity(id, application_id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_scim_group_member_identity_id ON sand_iam_scim_group_member (identity_id);

CREATE TABLE IF NOT EXISTS sand_iam_scim_resource (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL,
    identity_provider_id bigint NOT NULL,
    identity_id bigint NOT NULL,
    external_id varchar(191) NOT NULL,
    scim_id varchar(64) NOT NULL,
    version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
    source_state varchar(16) NOT NULL DEFAULT 'active' CHECK (source_state IN ('active', 'disabled', 'deleted')),
    source_attributes jsonb NOT NULL DEFAULT '{}'::jsonb,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sand_iam_scim_resource_provider_external UNIQUE (identity_provider_id, application_id, external_id),
    CONSTRAINT uk_sand_iam_scim_resource_scim_id UNIQUE (scim_id),
    CONSTRAINT uk_sand_iam_scim_resource_identity UNIQUE (identity_provider_id, application_id, identity_id),
    CONSTRAINT fk_sand_iam_scim_resource_provider_application FOREIGN KEY (identity_provider_id, application_id) REFERENCES sand_iam_identity_provider_application(identity_provider_id, application_id) ON DELETE RESTRICT,
    CONSTRAINT fk_sand_iam_scim_resource_identity_application FOREIGN KEY (identity_id, application_id) REFERENCES sand_iam_identity(id, application_id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_scim_resource_application_state ON sand_iam_scim_resource (application_id, source_state);

CREATE TABLE IF NOT EXISTS sand_iam_provisioning_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL,
    identity_provider_id bigint NOT NULL,
    scim_resource_id bigint NULL,
    event_type varchar(64) NOT NULL,
    outcome varchar(16) NOT NULL CHECK (outcome IN ('succeeded', 'failed', 'denied')),
    request_id varchar(96) NOT NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sand_iam_provisioning_event_provider_application FOREIGN KEY (identity_provider_id, application_id) REFERENCES sand_iam_identity_provider_application(identity_provider_id, application_id) ON DELETE RESTRICT,
    CONSTRAINT fk_sand_iam_provisioning_event_resource FOREIGN KEY (scim_resource_id) REFERENCES sand_iam_scim_resource(id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_provisioning_event_provider_create ON sand_iam_provisioning_event (identity_provider_id, create_time DESC);

WITH permission_def("name","slug","sort") AS (
    VALUES
        ('创建联合身份源','sand_iam:federation:create',100),
        ('配置联合身份源','sand_iam:federation:configure',99),
        ('挂载联合身份源','sand_iam:federation:mount',98),
        ('同步企业目录','sand_iam:federation:sync',97),
        ('签发SCIM令牌','sand_iam:scim:token_issue',96)
)
INSERT INTO sand_system_menu (parent_id, name, code, slug, type, path, component, icon, sort, status, create_time, update_time)
SELECT parent.id, permission_def.name, '', permission_def.slug, 3, '', '', '', permission_def.sort, 1, NOW(), NOW()
FROM permission_def
JOIN sand_system_menu parent ON parent.code = 'SandIAMIdentityProvider'
WHERE NOT EXISTS (SELECT 1 FROM sand_system_menu existing WHERE existing.slug = permission_def.slug);

-- IAM-T04-006 END
