-- Application-owned business-action vocabulary.
--
-- Compatibility policy: deliberately do not backfill sand_iam_api_resource.action
-- or sand_iam_policy.action. Existing free strings are not evidence of a valid
-- declaration; the management API exposes them as pending_claim records for a
-- human operator to review and claim explicitly.
-- This table is intentionally unrelated to sand_iam_service_action.

CREATE TABLE IF NOT EXISTS sand_iam_application_business_action (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL REFERENCES sand_iam_application(id) ON DELETE RESTRICT,
    code varchar(96) NOT NULL,
    name varchar(128) NOT NULL,
    description varchar(500) NOT NULL DEFAULT '',
    state varchar(16) NOT NULL DEFAULT 'draft',
    status smallint NOT NULL DEFAULT 1,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'sand_iam_application_business_action'::regclass AND conname = 'sand_iam_application_business_action_code_check') THEN
        ALTER TABLE sand_iam_application_business_action ADD CONSTRAINT sand_iam_application_business_action_code_check CHECK (code ~ '^[a-z][a-z0-9_.:-]{1,95}$');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'sand_iam_application_business_action'::regclass AND conname = 'sand_iam_application_business_action_state_check') THEN
        ALTER TABLE sand_iam_application_business_action ADD CONSTRAINT sand_iam_application_business_action_state_check CHECK (state IN ('draft', 'published'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'sand_iam_application_business_action'::regclass AND conname = 'sand_iam_application_business_action_status_check') THEN
        ALTER TABLE sand_iam_application_business_action ADD CONSTRAINT sand_iam_application_business_action_status_check CHECK (status IN (1, 2));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'sand_iam_application_business_action'::regclass AND conname = 'sand_iam_application_business_action_application_code_unique') THEN
        ALTER TABLE sand_iam_application_business_action ADD CONSTRAINT sand_iam_application_business_action_application_code_unique UNIQUE (application_id, code);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS sand_iam_application_business_action_application_status_idx
    ON sand_iam_application_business_action (application_id, status);

COMMENT ON TABLE sand_iam_application_business_action IS 'Application-owned declared business actions; never service integration actions.';
COMMENT ON COLUMN sand_iam_application_business_action.code IS 'Stable action code. Management API never updates code after creation; published declarations are immutable by contract.';
