-- IAM-T11: role grants inherited through active user-group membership.
-- The application is the authoritative organization boundary: both referenced
-- records must carry the same application_id, which belongs to exactly one
-- SandIAM organization.

CREATE UNIQUE INDEX IF NOT EXISTS ux_sand_iam_role_id_application
    ON sand_iam_role (id, application_id);

CREATE TABLE IF NOT EXISTS sand_iam_identity_group_role (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_group_id bigint NOT NULL,
    role_id bigint NOT NULL,
    application_id bigint NOT NULL REFERENCES sand_iam_application(id) ON DELETE RESTRICT,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_identity_group_role UNIQUE (identity_group_id, role_id),
    CONSTRAINT fk_sand_iam_group_role_group_app FOREIGN KEY (identity_group_id, application_id)
        REFERENCES sand_iam_identity_group(id, application_id) ON DELETE RESTRICT,
    CONSTRAINT fk_sand_iam_group_role_role_app FOREIGN KEY (role_id, application_id)
        REFERENCES sand_iam_role(id, application_id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_sand_iam_identity_group_role_role
    ON sand_iam_identity_group_role (application_id, role_id, status);
