BEGIN;

ALTER TABLE sand_ai_file_parse
    DROP CONSTRAINT IF EXISTS ck_sand_ai_file_parse_state;

ALTER TABLE sand_ai_file_parse
    ADD CONSTRAINT ck_sand_ai_file_parse_state
    CHECK (state IN ('queued', 'running', 'succeeded', 'failed'));

CREATE TABLE IF NOT EXISTS sand_ai_task_run (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment_id bigint NOT NULL REFERENCES sand_ai_environment(id) ON DELETE RESTRICT,
    task_type varchar(64) NOT NULL,
    resource_type varchar(64) NOT NULL,
    resource_id bigint NOT NULL,
    file_parse_id bigint NULL REFERENCES sand_ai_file_parse(id) ON DELETE RESTRICT,
    request_id varchar(64) NOT NULL,
    state varchar(16) NOT NULL DEFAULT 'queued',
    attempt_count integer NOT NULL DEFAULT 0,
    max_attempts integer NOT NULL DEFAULT 3,
    available_at timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    locked_at timestamp(0) without time zone NULL,
    locked_by varchar(128) NULL,
    started_at timestamp(0) without time zone NULL,
    completed_at timestamp(0) without time zone NULL,
    canceled_at timestamp(0) without time zone NULL,
    input jsonb NOT NULL DEFAULT '{}'::jsonb,
    result jsonb NOT NULL DEFAULT '{}'::jsonb,
    error_code varchar(64) NULL,
    error_summary varchar(500) NULL,
    status smallint NOT NULL DEFAULT 1,
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_ai_task_run_environment_request UNIQUE (environment_id, request_id),
    CONSTRAINT uk_sand_ai_task_run_file_parse UNIQUE (file_parse_id),
    CONSTRAINT ck_sand_ai_task_run_state CHECK (state IN ('queued', 'running', 'retrying', 'succeeded', 'failed', 'canceled')),
    CONSTRAINT ck_sand_ai_task_run_attempt_count CHECK (attempt_count >= 0 AND attempt_count <= max_attempts),
    CONSTRAINT ck_sand_ai_task_run_max_attempts CHECK (max_attempts > 0)
);

CREATE TABLE IF NOT EXISTS sand_ai_task_step (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id bigint NOT NULL REFERENCES sand_ai_task_run(id) ON DELETE RESTRICT,
    step_code varchar(64) NOT NULL,
    sequence_no integer NOT NULL,
    state varchar(16) NOT NULL DEFAULT 'queued',
    attempt_count integer NOT NULL DEFAULT 0,
    started_at timestamp(0) without time zone NULL,
    completed_at timestamp(0) without time zone NULL,
    context jsonb NOT NULL DEFAULT '{}'::jsonb,
    error_code varchar(64) NULL,
    error_summary varchar(500) NULL,
    status smallint NOT NULL DEFAULT 1,
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_ai_task_step_sequence UNIQUE (task_id, sequence_no),
    CONSTRAINT ck_sand_ai_task_step_state CHECK (state IN ('queued', 'running', 'retrying', 'succeeded', 'failed', 'canceled')),
    CONSTRAINT ck_sand_ai_task_step_sequence CHECK (sequence_no > 0),
    CONSTRAINT ck_sand_ai_task_step_attempt_count CHECK (attempt_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_sand_ai_task_run_claim
    ON sand_ai_task_run (state, available_at, id)
    WHERE status = 1 AND delete_time IS NULL;
CREATE INDEX IF NOT EXISTS idx_sand_ai_task_run_environment_time
    ON sand_ai_task_run (environment_id, create_time DESC);
CREATE INDEX IF NOT EXISTS idx_sand_ai_task_step_task_sequence
    ON sand_ai_task_step (task_id, sequence_no);
CREATE UNIQUE INDEX IF NOT EXISTS uk_sand_ai_task_run_active_resource
    ON sand_ai_task_run (environment_id, task_type, resource_type, resource_id)
    WHERE state IN ('queued', 'running', 'retrying') AND status = 1 AND delete_time IS NULL;

COMMIT;
