BEGIN;

CREATE TABLE IF NOT EXISTS sand_ai_capability_profile (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment_id bigint NOT NULL REFERENCES sand_ai_environment(id) ON DELETE RESTRICT,
    name varchar(128) NOT NULL,
    template_code varchar(64) NULL,
    data_egress_policy varchar(32) NOT NULL,
    revision integer NOT NULL,
    state varchar(16) NOT NULL DEFAULT 'draft',
    status smallint NOT NULL DEFAULT 2,
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_ai_capability_profile_environment_revision UNIQUE (environment_id, revision),
    CONSTRAINT ck_sand_ai_capability_profile_policy CHECK (data_egress_policy IN ('local_only', 'private_only', 'approved_cloud')),
    CONSTRAINT ck_sand_ai_capability_profile_state CHECK (state IN ('draft', 'published', 'archived')),
    CONSTRAINT ck_sand_ai_capability_profile_revision CHECK (revision > 0)
);

CREATE TABLE IF NOT EXISTS sand_ai_capability_route (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id bigint NOT NULL REFERENCES sand_ai_capability_profile(id) ON DELETE RESTRICT,
    capability_code varchar(64) NOT NULL,
    route_kind varchar(32) NOT NULL,
    deployment_id bigint NULL REFERENCES sand_ai_model_deployment(id) ON DELETE RESTRICT,
    driver_code varchar(128) NULL,
    priority integer NOT NULL,
    config jsonb NOT NULL DEFAULT '{}'::jsonb,
    status smallint NOT NULL DEFAULT 1,
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_ai_capability_route_priority UNIQUE (profile_id, capability_code, priority),
    CONSTRAINT ck_sand_ai_capability_route_kind CHECK (route_kind IN ('model_deployment', 'parse_driver')),
    CONSTRAINT ck_sand_ai_capability_route_priority CHECK (priority > 0),
    CONSTRAINT ck_sand_ai_capability_route_target CHECK (
        (route_kind = 'model_deployment' AND deployment_id IS NOT NULL AND driver_code IS NULL)
        OR (route_kind = 'parse_driver' AND deployment_id IS NULL AND driver_code IS NOT NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sand_ai_capability_profile_published_environment
    ON sand_ai_capability_profile (environment_id)
    WHERE state = 'published' AND status = 1 AND delete_time IS NULL;
CREATE INDEX IF NOT EXISTS idx_sand_ai_capability_route_profile_capability
    ON sand_ai_capability_route (profile_id, capability_code, priority);

COMMIT;
