BEGIN;

ALTER TABLE sand_ai_file DROP CONSTRAINT IF EXISTS ck_sand_ai_file_state;
ALTER TABLE sand_ai_file ADD CONSTRAINT ck_sand_ai_file_state
    CHECK (state IN ('uploaded', 'parsing', 'parsed', 'parse_failed', 'deleting', 'delete_failed', 'deleted'));

CREATE TABLE IF NOT EXISTS sand_ai_file_parse (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id bigint NOT NULL REFERENCES sand_ai_file(id) ON DELETE RESTRICT,
    parser_code varchar(64) NOT NULL,
    parser_version varchar(32) NOT NULL,
    state varchar(24) NOT NULL,
    source_block_count integer NOT NULL DEFAULT 0,
    error_code varchar(64) NULL,
    error_summary varchar(512) NULL,
    started_at timestamp(0) without time zone NOT NULL,
    completed_at timestamp(0) without time zone NULL,
    status smallint NOT NULL DEFAULT 1,
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT ck_sand_ai_file_parse_state CHECK (state IN ('running', 'succeeded', 'failed')),
    CONSTRAINT ck_sand_ai_file_parse_block_count CHECK (source_block_count >= 0)
);

CREATE TABLE IF NOT EXISTS sand_ai_source_block (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id bigint NOT NULL REFERENCES sand_ai_file(id) ON DELETE RESTRICT,
    parse_id bigint NOT NULL REFERENCES sand_ai_file_parse(id) ON DELETE RESTRICT,
    sequence_no integer NOT NULL,
    locator_type varchar(32) NOT NULL,
    locator jsonb NOT NULL DEFAULT '{}'::jsonb,
    content text NOT NULL,
    content_sha256 char(64) NOT NULL,
    char_count integer NOT NULL,
    status smallint NOT NULL DEFAULT 1,
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_ai_source_block_parse_sequence UNIQUE (parse_id, sequence_no),
    CONSTRAINT ck_sand_ai_source_block_sequence CHECK (sequence_no > 0),
    CONSTRAINT ck_sand_ai_source_block_content CHECK (char_length(content) > 0),
    CONSTRAINT ck_sand_ai_source_block_hash CHECK (content_sha256 ~ '^[a-f0-9]{64}$'),
    CONSTRAINT ck_sand_ai_source_block_char_count CHECK (char_count > 0)
);

CREATE INDEX IF NOT EXISTS idx_sand_ai_file_parse_file_time ON sand_ai_file_parse (file_id, create_time DESC);
CREATE INDEX IF NOT EXISTS idx_sand_ai_source_block_file_sequence ON sand_ai_source_block (file_id, sequence_no);

COMMIT;
