-- Consumer-owned PostgreSQL only. Execute only with database authorization.
-- This script does not create a database, account, sand_iam_* table, or sa_* table.
-- provider_b_document is the pre-existing business document source; HTTP never submits bytes.
CREATE TABLE provider_b_document (
    id varchar(64) PRIMARY KEY,
    organization_id bigint NOT NULL,
    body bytea NOT NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE provider_b_document_process (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL,
    document_id varchar(64) NOT NULL REFERENCES provider_b_document(id) ON DELETE RESTRICT,
    workload_client_id bigint NOT NULL,
    idempotency_key varchar(96) NOT NULL,
    content_sha256 char(64) NOT NULL,
    content_bytes bigint NOT NULL CHECK (content_bytes >= 0),
    context_id varchar(64) NOT NULL,
    processed_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_provider_b_process_workload_idempotency UNIQUE (workload_client_id, idempotency_key)
);
CREATE TABLE provider_b_audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NULL,
    workload_client_id bigint NULL,
    document_id varchar(64) NULL,
    action varchar(96) NOT NULL,
    outcome varchar(16) NOT NULL,
    request_id varchar(96) NOT NULL,
    context_id varchar(64) NULL,
    context_hash char(64) NULL,
    idempotency_key_hash char(64) NULL,
    replayed boolean NOT NULL DEFAULT false,
    error_code varchar(96) NULL,
    http_status smallint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_provider_b_process_document ON provider_b_document_process (organization_id, document_id);
CREATE INDEX idx_provider_b_audit_request_context ON provider_b_audit_log (request_id, context_id);
