#!/usr/bin/env bash

set -euo pipefail

readonly db_prefix='sand_iam_acceptance_sp02a_'
readonly maintenance_db="${SAND_IAM_SP02A_MAINTENANCE_DB:-postgres}"
readonly db_name="${SAND_IAM_SP02A_DB:-${db_prefix}run_$$}"
readonly baseline_ref="${SAND_IAM_SP02A_BASELINE_REF:-1a6f9ef190abebe89ae2a766dbfe8bbee1a6d14e}"
readonly repo_root="$(git rev-parse --show-toplevel)"
readonly sand_iam_root="${repo_root}/sand-iam"

database_created=false

fail() {
    printf 'SP-02A failed: %s\n' "$*" >&2
    exit 1
}

assert_test_database_name() {
    [[ "${db_name}" =~ ^sand_iam_acceptance_sp02a_[a-z0-9_]{1,48}$ ]] || fail "refusing unsafe temporary database name: ${db_name}"
}

psql_maintenance() {
    psql --no-psqlrc --set=ON_ERROR_STOP=1 --dbname="${maintenance_db}" "$@"
}

psql_fixture() {
    psql --no-psqlrc --set=ON_ERROR_STOP=1 --dbname="${db_name}" "$@"
}

cleanup() {
    if [[ "${database_created}" == true ]]; then
        assert_test_database_name
        dropdb --if-exists --force --maintenance-db="${maintenance_db}" "${db_name}"
        database_created=false
    fi
}

trap cleanup EXIT

assert_test_database_name

if [[ "${db_name}" == "${maintenance_db}" ]]; then
    fail 'temporary database name must differ from the maintenance database'
fi

existing_database="$(psql_maintenance --tuples-only --no-align --command="SELECT 1 FROM pg_database WHERE datname = '${db_name}'")" || fail 'unable to inspect PostgreSQL databases'
if [[ "${existing_database}" == '1' ]]; then
    fail "refusing to reuse existing database: ${db_name}"
fi

createdb --template=template0 --maintenance-db="${maintenance_db}" "${db_name}"
database_created=true

# The historical plugin snapshot predates its host fixture. Supply only the
# neutral menu contract required by later SandIAM migrations.
psql_fixture <<'SQL'
CREATE TABLE sand_system_menu (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id bigint NOT NULL DEFAULT 0,
    name varchar(128) NOT NULL,
    code varchar(128) NOT NULL DEFAULT '',
    slug varchar(128) NOT NULL DEFAULT '',
    type smallint NOT NULL,
    path varchar(255) NOT NULL DEFAULT '',
    component varchar(255) NOT NULL DEFAULT '',
    icon varchar(128) NOT NULL DEFAULT '',
    sort integer NOT NULL DEFAULT 0,
    is_hidden smallint NOT NULL DEFAULT 2,
    status smallint NOT NULL DEFAULT 1,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE sand_system_role_menu (
    role_id bigint NOT NULL,
    menu_id bigint NOT NULL,
    PRIMARY KEY (role_id, menu_id)
);
SQL

git -C "${repo_root}" cat-file -e "${baseline_ref}^{commit}" 2>/dev/null \
    || fail "0.1 baseline commit is unavailable: ${baseline_ref}"
git -C "${repo_root}" show "${baseline_ref}:sand-iam/install.sql" | psql_fixture
awk '/^BEGIN;/{exit} {print}' "${sand_iam_root}/lifecycle/base.pgsql" | psql_fixture
# The published 0.6 demo menu predates the dedicated developer route. Keep
# that real predecessor shape so migration 036 must create its own new parent.
psql_fixture --command="DELETE FROM sand_system_menu WHERE code = 'SandIAMDeveloperDocs'"

if ! psql_fixture --tuples-only --no-align --command="SELECT 1 FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'sand_iam_identity_binding' AND column_name = 'provider_code'" | grep -qx '1'; then
    fail "baseline ${baseline_ref} did not create the expected 0.1 provider_code fixture"
fi

psql_fixture <<'SQL'
INSERT INTO sand_iam_organization (code, name) VALUES
    ('sp02a-org-a', 'SP-02A 组织 A'),
    ('sp02a-org-b', 'SP-02A 组织 B');

INSERT INTO sand_iam_application (organization_id, code, name)
SELECT organization.id, application.code, application.name
FROM sand_iam_organization organization
JOIN (VALUES
    ('sp02a-org-a', 'sp02a-app-a', 'SP-02A 应用 A'),
    ('sp02a-org-b', 'sp02a-app-b', 'SP-02A 应用 B')
) AS application(organization_code, code, name) ON application.organization_code = organization.code;

INSERT INTO sand_iam_identity (application_id, code, display_name)
SELECT application.id, identity_record.code, identity_record.display_name
FROM sand_iam_application application
JOIN (VALUES
    ('sp02a-app-a', 'sp02a-user-a', 'SP-02A 用户 A'),
    ('sp02a-app-b', 'sp02a-user-b', 'SP-02A 用户 B')
) AS identity_record(application_code, code, display_name) ON identity_record.application_code = application.code;

INSERT INTO sand_iam_identity_binding (identity_id, provider_code, subject)
SELECT identity_record.id, 'phone', '13800138000'
FROM sand_iam_identity identity_record
WHERE identity_record.code = 'sp02a-user-a';
SQL

# Advance the historical 0.1 fixture through the authoritative source
# migrations to the published 0.6.0/032 boundary. The release update payload
# intentionally starts at 033 and must not silently claim direct 0.1 support.
for migration in "${sand_iam_root}"/migrations/*.pgsql; do
    migration_name="${migration##*/}"
    case "${migration_name}" in
        00[2-9]_*.pgsql|0[12][0-9]_*.pgsql|03[0-2]_*.pgsql)
            psql_fixture --file="${migration}"
            ;;
    esac
done

psql_fixture --file="${sand_iam_root}/update.sql"

psql_fixture <<'SQL'
DO $$
DECLARE
    developer_menu_count integer;
    acceptance_permission_count integer;
BEGIN
    SELECT count(*) INTO developer_menu_count
    FROM sand_system_menu developer
    JOIN sand_system_menu root ON root.id = developer.parent_id
    WHERE developer.code = 'SandIAMDeveloperDocs'
      AND root.code = 'SandIAM'
      AND developer.name = '开发者接入'
      AND developer.slug = ''
      AND developer.type = 2
      AND developer.path = 'developer-docs'
      AND developer.component = '/plugin/sand-iam/developer-docs/index'
      AND developer.icon = ''
      AND developer.sort = 56
      AND developer.is_hidden = 1
      AND developer.status = 1;
    IF developer_menu_count <> 1 THEN
        RAISE EXCEPTION '0.6.0 -> 0.7.0 upgrade did not create the exact unique developer menu';
    END IF;

    SELECT count(*) INTO acceptance_permission_count
    FROM sand_system_menu permission
    JOIN sand_system_menu developer ON developer.id = permission.parent_id
    WHERE developer.code = 'SandIAMDeveloperDocs'
      AND permission.code IN ('sand_iam:acceptance_fixture:cleanup', 'sand_iam:acceptance_fixture:read')
      AND permission.slug = permission.code
      AND permission.type = 3
      AND permission.is_hidden = 1
      AND permission.status = 1;
    IF acceptance_permission_count <> 2 THEN
        RAISE EXCEPTION '0.6.0 -> 0.7.0 upgrade did not attach the exact acceptance permissions';
    END IF;
    IF EXISTS (
        SELECT 1
        FROM sand_system_role_menu role_menu
        JOIN sand_system_menu permission ON permission.id = role_menu.menu_id
        WHERE permission.code IN ('sand_iam:acceptance_fixture:cleanup', 'sand_iam:acceptance_fixture:read')
    ) THEN
        RAISE EXCEPTION '0.6.0 -> 0.7.0 upgrade granted acceptance permissions to an existing role';
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM sand_iam_identity_binding binding
        JOIN sand_iam_identity identity_record ON identity_record.id = binding.identity_id
        JOIN sand_iam_identity_provider provider ON provider.id = binding.identity_provider_id
        WHERE binding.application_id = identity_record.application_id
          AND provider.application_id = identity_record.application_id
          AND identity_record.code = 'sp02a-user-a'
          AND provider.code = 'phone'
          AND binding.subject = '13800138000'
    ) THEN
        RAISE EXCEPTION 'legacy binding was not migrated to its application-scoped provider';
    END IF;
END
$$;

INSERT INTO sand_iam_identity_provider (organization_id, application_id, code, name)
SELECT application.organization_id, application.id, 'phone', 'SP-02A 手机号身份源'
FROM sand_iam_application application
WHERE application.code = 'sp02a-app-b';

INSERT INTO sand_iam_identity_provider_application (identity_provider_id, application_id, organization_id, provider_scope_application_key)
SELECT provider.id, application.id, application.organization_id, provider.scope_application_key
FROM sand_iam_application application
JOIN sand_iam_identity_provider provider ON provider.application_id = application.id
WHERE application.code = 'sp02a-app-b'
  AND provider.code = 'phone';

INSERT INTO sand_iam_identity_binding (application_id, identity_id, identity_provider_id, subject)
SELECT application.id, identity_record.id, provider.id, '13800138000'
FROM sand_iam_application application
JOIN sand_iam_identity identity_record ON identity_record.application_id = application.id
JOIN sand_iam_identity_provider provider ON provider.application_id = application.id
WHERE application.code = 'sp02a-app-b'
  AND identity_record.code = 'sp02a-user-b'
  AND provider.code = 'phone';

DO $$
BEGIN
    INSERT INTO sand_iam_identity_binding (application_id, identity_id, identity_provider_id, subject)
    SELECT application.id, identity_record.id, provider.id, '13800138000'
    FROM sand_iam_application application
    JOIN sand_iam_identity identity_record ON identity_record.application_id = application.id
    JOIN sand_iam_identity_provider provider ON provider.application_id = application.id
    WHERE application.code = 'sp02a-app-a'
      AND identity_record.code = 'sp02a-user-a'
      AND provider.code = 'phone';
    RAISE EXCEPTION 'same-provider duplicate subject was accepted';
EXCEPTION WHEN unique_violation THEN
    NULL;
END
$$;

DO $$
BEGIN
    INSERT INTO sand_iam_identity_binding (application_id, identity_id, identity_provider_id, subject)
    SELECT application_a.id, identity_a.id, provider_b.id, 'sp02a-provider-cross-app'
    FROM sand_iam_application application_a
    JOIN sand_iam_identity identity_a ON identity_a.application_id = application_a.id
    CROSS JOIN sand_iam_application application_b
    JOIN sand_iam_identity_provider provider_b ON provider_b.application_id = application_b.id
    WHERE application_a.code = 'sp02a-app-a'
      AND identity_a.code = 'sp02a-user-a'
      AND application_b.code = 'sp02a-app-b'
      AND provider_b.code = 'phone';
    RAISE EXCEPTION 'provider/application cross-binding was accepted';
EXCEPTION WHEN foreign_key_violation THEN
    NULL;
END
$$;

DO $$
BEGIN
    INSERT INTO sand_iam_identity_binding (application_id, identity_id, identity_provider_id, subject)
    SELECT application_b.id, identity_a.id, provider_b.id, 'sp02a-identity-cross-app'
    FROM sand_iam_application application_a
    JOIN sand_iam_identity identity_a ON identity_a.application_id = application_a.id
    CROSS JOIN sand_iam_application application_b
    JOIN sand_iam_identity_provider provider_b ON provider_b.application_id = application_b.id
    WHERE application_a.code = 'sp02a-app-a'
      AND identity_a.code = 'sp02a-user-a'
      AND application_b.code = 'sp02a-app-b'
      AND provider_b.code = 'phone';
    RAISE EXCEPTION 'identity/application cross-binding was accepted';
EXCEPTION WHEN foreign_key_violation THEN
    NULL;
END
$$;
SQL

psql_fixture --file="${sand_iam_root}/update.sql"
psql_fixture --file="${sand_iam_root}/uninstall.sql"

remaining_tables="$(psql_fixture --tuples-only --no-align --command="SELECT count(*) FROM pg_tables WHERE schemaname = current_schema() AND tablename LIKE 'sand_iam_%'")"
[[ "${remaining_tables}" == '0' ]] || fail "uninstall left ${remaining_tables} sand_iam_* tables"

printf 'SP-02A passed: 0.1 -> source 032 -> release 037 upgrade, constraints, repeated update, uninstall, and cleanup verified (%s).\n' "${db_name}"
