#!/usr/bin/env bash

set -euo pipefail

readonly db_prefix='sand_iam_acceptance_t01_'
readonly maintenance_db="${SAND_IAM_T01_MAINTENANCE_DB:-postgres}"
readonly db_name="${SAND_IAM_T01_DB:-${db_prefix}run_$$}"
readonly repo_root="$(git rev-parse --show-toplevel)"
readonly sand_iam_root="${repo_root}/sand-iam"
database_created=false

fail() { printf 'IAM-T01 lifecycle failed: %s\n' "$*" >&2; exit 1; }
[[ "${db_name}" =~ ^sand_iam_acceptance_t01_[a-z0-9_]{1,48}$ ]] || fail 'unsafe temporary database name'
[[ "${db_name}" != "${maintenance_db}" ]] || fail 'temporary database cannot be the maintenance database'

cleanup() {
    if [[ "${database_created}" == true ]]; then
        dropdb --if-exists --force --maintenance-db="${maintenance_db}" "${db_name}"
    fi
}
trap cleanup EXIT

psql_admin() { psql --no-psqlrc --set=ON_ERROR_STOP=1 --dbname="${maintenance_db}" "$@"; }
psql_test() { psql --no-psqlrc --set=ON_ERROR_STOP=1 --dbname="${db_name}" "$@"; }

[[ "$(psql_admin --tuples-only --no-align --command="SELECT 1 FROM pg_database WHERE datname = '${db_name}'")" != '1' ]] || fail 'refusing to reuse existing database'
createdb --template=template0 --maintenance-db="${maintenance_db}" "${db_name}"
database_created=true

# The package lifecycle intentionally owns SandIAM tables only; this minimal host table lets its menu upsert run.
psql_test <<'SQL'
CREATE TABLE sand_system_menu (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id bigint NOT NULL DEFAULT 0, name varchar(128) NOT NULL, code varchar(128) NOT NULL DEFAULT '', slug varchar(128) NOT NULL DEFAULT '',
    type smallint NOT NULL, path varchar(255) NOT NULL DEFAULT '', component varchar(255) NOT NULL DEFAULT '', icon varchar(128) NOT NULL DEFAULT '', sort integer NOT NULL DEFAULT 0, is_hidden smallint NOT NULL DEFAULT 2,
    status smallint NOT NULL DEFAULT 1, create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sand_system_role_menu (
    role_id bigint NOT NULL,
    menu_id bigint NOT NULL,
    PRIMARY KEY (role_id, menu_id)
);

CREATE TYPE tablestruct AS (
    fields_key_name varchar(100), fields_name varchar(200), fields_type varchar(20),
    fields_length bigint, fields_not_null varchar(10), fields_default varchar(500), fields_comment varchar(1000)
);

CREATE FUNCTION pgsql_type(a_type varchar) RETURNS varchar LANGUAGE plpgsql AS $$
BEGIN
    RETURN CASE a_type WHEN 'int8' THEN 'bigint' WHEN 'int4' THEN 'integer' WHEN 'int2' THEN 'smallint' WHEN 'bpchar' THEN 'char' ELSE a_type END;
END $$;

CREATE FUNCTION table_msg(a_schema_name varchar, a_table_name varchar) RETURNS SETOF tablestruct LANGUAGE plpgsql AS $$
DECLARE
    v_ret tablestruct;
    v_record record;
BEGIN
    FOR v_record IN
        SELECT
            constraint_info.constraint_name AS fields_key_name,
            attribute.attname AS fields_name,
            pgsql_type(type_record.typname::varchar) AS fields_type,
            NULLIF(attribute.atttypmod - 4, -5)::bigint AS fields_length,
            CASE WHEN attribute.attnotnull THEN 'not null' ELSE '' END AS fields_not_null,
            pg_get_expr(default_record.adbin, default_record.adrelid)::varchar AS fields_default,
            description.description::varchar AS fields_comment
        FROM pg_attribute attribute
        JOIN pg_class class_record ON class_record.oid = attribute.attrelid
        JOIN pg_namespace namespace_record ON namespace_record.oid = class_record.relnamespace
        JOIN pg_type type_record ON type_record.oid = attribute.atttypid
        LEFT JOIN pg_attrdef default_record ON default_record.adrelid = class_record.oid AND default_record.adnum = attribute.attnum
        LEFT JOIN pg_description description ON description.objoid = class_record.oid AND description.objsubid = attribute.attnum
        LEFT JOIN LATERAL (
            SELECT key_usage.constraint_name
            FROM information_schema.key_column_usage key_usage
            WHERE key_usage.table_schema = a_schema_name
              AND key_usage.table_name = a_table_name
              AND key_usage.column_name = attribute.attname
            ORDER BY key_usage.constraint_name
            LIMIT 1
        ) constraint_info ON true
        WHERE namespace_record.nspname = a_schema_name
          AND class_record.relname = a_table_name
          AND attribute.attnum > 0
          AND NOT attribute.attisdropped
        ORDER BY attribute.attnum
    LOOP
        v_ret.fields_key_name := COALESCE(v_record.fields_key_name, '');
        v_ret.fields_name := v_record.fields_name;
        v_ret.fields_type := v_record.fields_type;
        v_ret.fields_length := CASE WHEN v_record.fields_length > 0 THEN v_record.fields_length ELSE NULL END;
        v_ret.fields_not_null := v_record.fields_not_null;
        v_ret.fields_default := v_record.fields_default;
        v_ret.fields_comment := v_record.fields_comment;
        RETURN NEXT v_ret;
    END LOOP;
END $$;

CREATE FUNCTION table_msg(a_table_name varchar) RETURNS SETOF tablestruct LANGUAGE sql AS $$
    SELECT * FROM table_msg('public', a_table_name)
$$;
SQL

psql_test --file="${sand_iam_root}/install.sql"

export SAND_IAM_T01_HOST_ROOT="${SAND_IAM_T01_HOST_ROOT:-/Users/code/project/sand_plugins/sandadmin-demo-host/server}"
export DB_TYPE='pgsql'
export DB_HOST='/tmp'
export DB_PORT='5432'
export DB_NAME="${db_name}"
export DB_USER="$(psql_admin --tuples-only --no-align --command='SELECT current_user')"
export DB_PASSWORD=''
export SAND_IAM_AUTH_PEPPER='t01-ephemeral-auth-pepper'
export SAND_IAM_AUTH_PEPPER_VERSION='t01-v1'
export SAND_IAM_AUTH_EMAIL_SENDER='SandIamT01Sender'
export SAND_IAM_MFA_ENCRYPTION_KEY='MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY='
export SAND_IAM_MFA_ENCRYPTION_KEY_VERSION='t01-v1'
export SAND_IAM_MFA_ENCRYPTION_KEYS='{"legacy-v0":"ZmVkY2JhOTg3NjU0MzIxMGZlZGNiYTk4NzY1NDMyMTA="}'
export SAND_IAM_FEDERATION_ENCRYPTION_KEY='MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY='
psql_test -f "${sand_iam_root}/migrations/007_federation_handoff.pgsql"

php "${sand_iam_root}/plugin/sand-iam/tests/human_auth_service_integration_test.php"
php "${sand_iam_root}/plugin/sand-iam/tests/mfa_passkey_integration_test.php"
php "${sand_iam_root}/plugin/sand-iam/tests/oauth_oidc_integration_test.php"
php "${sand_iam_root}/plugin/sand-iam/tests/federation_ab_integration_test.php"

psql_test <<'SQL'
INSERT INTO sand_iam_organization (code, name) VALUES ('t01-org-a', 'T01 organization A'), ('t01-org-b', 'T01 organization B');
INSERT INTO sand_iam_application (organization_id, code, name)
SELECT id, 't01-app', 'T01 app' FROM sand_iam_organization WHERE code IN ('t01-org-a', 't01-org-b');
INSERT INTO sand_iam_identity (application_id, code, display_name)
SELECT application.id, 't01-user', 'T01 user'
FROM sand_iam_application application
JOIN sand_iam_organization organization ON organization.id = application.organization_id
WHERE organization.code IN ('t01-org-a', 't01-org-b');
INSERT INTO sand_iam_identity_auth (application_id, identity_id, username, email, password_hash, pepper_version)
SELECT application_id, id, 't01-user', 't01@example.test', '$argon2id$opaque', 'v1' FROM sand_iam_identity WHERE application_id = (SELECT id FROM sand_iam_application WHERE organization_id = (SELECT id FROM sand_iam_organization WHERE code = 't01-org-a'));
DO $$
BEGIN
    INSERT INTO sand_iam_identity_auth (application_id, identity_id, username, email, password_hash, pepper_version)
    SELECT application_id, id, 't01-user-b', 't01@example.test', '$argon2id$opaque', 'v1' FROM sand_iam_identity WHERE application_id = (SELECT id FROM sand_iam_application WHERE organization_id = (SELECT id FROM sand_iam_organization WHERE code = 't01-org-b'));
EXCEPTION WHEN unique_violation THEN
    RAISE EXCEPTION 'email was incorrectly global rather than application scoped';
END $$;

-- Security state-machine evidence: only HMAC-shaped token material is stored;
-- used refresh tokens revoke their whole session family; a consumed challenge is
-- not reusable; and an identity-auth disable leaves no active eligible session.
INSERT INTO sand_iam_auth_session (application_id, identity_id, access_token_hash, refresh_token_hash, pepper_version, access_expire_time, refresh_expire_time, ip_hash)
SELECT application_id, id, repeat('a', 64), repeat('b', 64), 'v1', NOW() + interval '15 minutes', NOW() + interval '30 days', repeat('c', 64)
FROM sand_iam_identity WHERE code = 't01-user' AND application_id = (SELECT application.id FROM sand_iam_application application JOIN sand_iam_organization organization ON organization.id = application.organization_id WHERE organization.code = 't01-org-a');
INSERT INTO sand_iam_auth_refresh_token (session_id, token_hash, pepper_version, expire_time)
SELECT id, repeat('d', 64), 'v1', NOW() + interval '30 days'
FROM sand_iam_auth_session WHERE refresh_token_hash = repeat('b', 64);
UPDATE sand_iam_auth_refresh_token SET used_time = NOW(), status = 2 WHERE token_hash = repeat('d', 64);
UPDATE sand_iam_auth_session SET status = 2, revoked_time = NOW() WHERE id = (SELECT session_id FROM sand_iam_auth_refresh_token WHERE token_hash = repeat('d', 64));
UPDATE sand_iam_auth_refresh_token SET status = 2, revoked_time = NOW() WHERE session_id = (SELECT session_id FROM sand_iam_auth_refresh_token WHERE token_hash = repeat('d', 64)) AND status = 1;
INSERT INTO sand_iam_auth_verification (application_id, identity_id, purpose, channel, destination_hash, code_hash, pepper_version, expire_time)
SELECT application_id, id, 'email_verify', 'email', repeat('e', 64), repeat('f', 64), 'v1', NOW() + interval '10 minutes'
FROM sand_iam_identity
WHERE code = 't01-user'
  AND application_id = (SELECT application.id FROM sand_iam_application application JOIN sand_iam_organization organization ON organization.id = application.organization_id WHERE organization.code = 't01-org-a');
UPDATE sand_iam_auth_verification SET consumed_time = NOW(), status = 2 WHERE code_hash = repeat('f', 64) AND status = 1;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM sand_iam_auth_refresh_token WHERE token_hash = repeat('d', 64) AND status = 1) THEN RAISE EXCEPTION 'replayed refresh family remained active'; END IF;
    IF EXISTS (SELECT 1 FROM sand_iam_auth_verification WHERE code_hash = repeat('f', 64) AND status = 1) THEN RAISE EXCEPTION 'consumed verification remained active'; END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name IN ('sand_iam_auth_session', 'sand_iam_auth_refresh_token', 'sand_iam_auth_verification') AND column_name IN ('access_token', 'refresh_token', 'verification_code')) THEN RAISE EXCEPTION 'plaintext sensitive token column exists'; END IF;
END $$;
SQL

printf 'IAM-T01 post-install schema snapshot: tables=%s ledger_rows=%s\n' \
    "$(psql_test --tuples-only --no-align --command="SELECT count(*) FROM pg_tables WHERE schemaname = current_schema() AND tablename LIKE 'sand_iam_%'")" \
    "$(psql_test --tuples-only --no-align --command="SELECT count(*) FROM sand_iam_schema_migration")"
psql_test --tuples-only --no-align --command="SELECT tablename FROM pg_tables WHERE schemaname = current_schema() AND tablename LIKE 'sand_iam_%' ORDER BY tablename" \
    | sed 's/^/IAM-T01 post-install table: /'

psql_test --file="${sand_iam_root}/update.sql"
psql_test --file="${sand_iam_root}/update.sql"
psql_test --file="${sand_iam_root}/uninstall.sql"
[[ "$(psql_test --tuples-only --no-align --command="SELECT count(*) FROM pg_tables WHERE schemaname = current_schema() AND tablename LIKE 'sand_iam_%'")" == '0' ]] || fail 'uninstall left SandIAM tables'

# Rebuild the same isolated database at the published 0.6.0/032 boundary, then
# prove the package update crosses 032 -> 037 cleanly and preserves application
# isolation in SQL.
awk '/^-- lifecycle source: migrations\/033_identity_group_role\.pgsql/{exit} {print}' "${sand_iam_root}/install.sql" | psql_test
[[ "$(psql_test --tuples-only --no-align --command="SELECT to_regclass('sand_iam_auth_session') IS NOT NULL AND to_regclass('sand_iam_identity_group_role') IS NULL AND to_regclass('sand_iam_schema_migration') IS NULL")" == 't' ]] || fail 'could not establish the isolated 0.6.0/032 baseline'
psql_test --file="${sand_iam_root}/update.sql"
psql_test --file="${sand_iam_root}/update.sql"

psql_test <<'SQL'
INSERT INTO sand_iam_organization (code, name) VALUES ('t02-upgrade-org-a', 'T02 upgrade A'), ('t02-upgrade-org-b', 'T02 upgrade B');
INSERT INTO sand_iam_application (organization_id, code, name)
SELECT id, code || '-app', name || ' app' FROM sand_iam_organization WHERE code LIKE 't02-upgrade-org-%';
INSERT INTO sand_iam_identity (application_id, code, display_name)
SELECT id, code || '-user', name || ' user' FROM sand_iam_application WHERE code LIKE 't02-upgrade-org-%';

DO $$
DECLARE
    app_a bigint;
    app_b bigint;
    identity_a bigint;
    identity_b bigint;
    factor_a bigint;
BEGIN
    SELECT id INTO app_a FROM sand_iam_application WHERE code = 't02-upgrade-org-a-app';
    SELECT id INTO app_b FROM sand_iam_application WHERE code = 't02-upgrade-org-b-app';
    SELECT id INTO identity_a FROM sand_iam_identity WHERE application_id = app_a;
    SELECT id INTO identity_b FROM sand_iam_identity WHERE application_id = app_b;

    BEGIN
        INSERT INTO sand_iam_mfa_factor (application_id, identity_id, type, name, encrypted_secret, encryption_version, status)
        VALUES (app_a, identity_b, 'totp', 'cross-app factor', 'v1.fixture', 'v1', 2);
        RAISE EXCEPTION 'cross-application MFA factor was accepted';
    EXCEPTION WHEN foreign_key_violation THEN NULL;
    END;

    INSERT INTO sand_iam_mfa_factor (application_id, identity_id, type, name, encrypted_secret, encryption_version, status)
    VALUES (app_a, identity_a, 'totp', 'valid factor', 'v1.fixture', 'v1', 2)
    RETURNING id INTO factor_a;

    BEGIN
        INSERT INTO sand_iam_mfa_recovery_code (application_id, identity_id, factor_id, code_hash, generation)
        VALUES (app_b, identity_b, factor_a, repeat('a', 64), 1);
        RAISE EXCEPTION 'cross-application recovery factor was accepted';
    EXCEPTION WHEN foreign_key_violation THEN NULL;
    END;

    BEGIN
        INSERT INTO sand_iam_auth_challenge (application_id, identity_id, purpose, token_hash, encrypted_challenge, encryption_version, expire_time)
        VALUES (app_a, identity_b, 'mfa_login', repeat('b', 64), 'v1.fixture', 'v1', NOW() + interval '5 minutes');
        RAISE EXCEPTION 'cross-application challenge identity was accepted';
    EXCEPTION WHEN foreign_key_violation THEN NULL;
    END;

    BEGIN
        INSERT INTO sand_iam_webauthn_credential (application_id, identity_id, name, credential_id, public_key, user_handle)
        VALUES (app_a, identity_b, 'cross-app credential', 'fixture-id', 'fixture-public-key', 'fixture-user-handle');
        RAISE EXCEPTION 'cross-application WebAuthn credential was accepted';
    EXCEPTION WHEN foreign_key_violation THEN NULL;
    END;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'sand_iam_mfa_factor'
          AND column_name IN ('credential_id', 'public_key', 'user_handle', 'sign_count')
    ) THEN
        RAISE EXCEPTION '0.6.0/032 -> 0.7.0 upgrade retained the obsolete mixed MFA factor schema';
    END IF;
    IF to_regclass('sand_iam_webauthn_credential') IS NULL THEN
        RAISE EXCEPTION '0.6.0/032 -> 0.7.0 upgrade did not preserve the separate WebAuthn credential table';
    END IF;
END $$;
SQL

psql_test --file="${sand_iam_root}/uninstall.sql"
[[ "$(psql_test --tuples-only --no-align --command="SELECT count(*) FROM pg_tables WHERE schemaname = current_schema() AND tablename LIKE 'sand_iam_%'")" == '0' ]] || fail '0.6.0/032 -> 0.7.0 upgrade uninstall left SandIAM tables'
printf 'SandIAM auth lifecycle passed: fresh install -> update x2 -> uninstall; isolated 0.6.0/032 -> 0.7.0 update x2 -> isolation checks -> uninstall (%s).\n' "${db_name}"
