<?php
declare(strict_types=1);
use Sand\Iam\Example\ProviderB\{ContextVerifier,ProcessStore,ProviderApplication,ProviderConfig,ProviderException,ProviderProtocol};
spl_autoload_register(static function(string $class):void {$p='Sand\\Iam\\Example\\ProviderB\\';if(str_starts_with($class,$p))require_once dirname(__DIR__).'/src/'.substr($class,strlen($p)).'.php';});
require_once __DIR__ . '/Fakes.php';
require_once __DIR__ . '/PdoFakes.php';
require_once dirname(__DIR__, 4) . '/sdk/php/src/SandIamException.php';
require_once dirname(__DIR__, 4) . '/sdk/php/src/SandIamClient.php';
$passed=0;$total=0;
$test=static function(string $name,callable $run)use(&$passed,&$total):void{++$total;try{$run();++$passed;echo"[PASS] $name\n";}catch(Throwable $e){echo"[FAIL] $name: {$e->getMessage()}\n";}};
$expect=static function(string $code,callable $run):void{try{$run();}catch(ProviderException $e){if($e->errorCode===$code)return;throw new RuntimeException("expected $code");}throw new RuntimeException("expected $code");};
$test('configuration rejects non-postgresql',static function()use($expect):void{$expect('PROVIDER_B_POSTGRESQL_REQUIRED',static fn()=>ProviderConfig::fromArray(['SAND_IAM_BASE_URL'=>'https://iam.example','SAND_IAM_ORGANIZATION_CODE'=>'org-a','SAND_IAM_APPLICATION_CODE'=>'app-a','PROVIDER_B_DATABASE_DSN'=>'sqlite::memory:']));});
$test('same key and bytes replay after a second verification',static function():void{$store=new MemoryStore();$app=new ProviderApplication(new AllowVerifier(),$store);$first=$app->process('doc-1','a','idem-key-0001','request-0001');$again=$app->process('doc-1','b','idem-key-0001','request-0002');if($first['replayed']||!$again['replayed']||$store->effects!==1||$store->calls!==2)throw new RuntimeException('replay contract');});
$test('different bytes for same key reject without new effect',static function()use($expect):void{$store=new MemoryStore();$app=new ProviderApplication(new AllowVerifier(),$store);$app->process('doc-1','a','idem-key-0002','request-0003');$store->body='changed';$expect('PROVIDER_B_IDEMPOTENCY_KEY_REUSED',static fn()=>$app->process('doc-1','b','idem-key-0002','request-0004'));if($store->effects!==1)throw new RuntimeException('extra effect');});
$test('denial has no persistence side effect',static function()use($expect):void{$store=new MemoryStore();$app=new ProviderApplication(new DenyVerifier(),$store);$expect('PROVIDER_B_CONTEXT_DENIED',static fn()=>$app->process('doc-1','x','idem-key-0003','request-0005'));if($store->calls!==0||$store->effects!==0)throw new RuntimeException('denial persisted');});
$test('same context and key are rechecked after revocation before replay',static function()use($expect):void{$store=new MemoryStore();$verifier=new RevocableVerifier();$app=new ProviderApplication($verifier,$store);$app->process('doc-1','same-context','idem-key-0006','request-0006');$verifier->revoked=true;$expect('PROVIDER_B_CONTEXT_DENIED',static fn()=>$app->process('doc-1','same-context','idem-key-0006','request-0007'));if($store->calls!==1||$verifier->calls!==2)throw new RuntimeException('revoked replay reached store');});
$test('sdk verifier maps only 401 and 403 to authorization denial',static function()use($expect):void{$config=ProviderConfig::fromArray(['SAND_IAM_BASE_URL'=>'https://iam.example','SAND_IAM_ORGANIZATION_CODE'=>'org-a','SAND_IAM_APPLICATION_CODE'=>'app-a','PROVIDER_B_DATABASE_DSN'=>'pgsql:host=example']);foreach([401,403]as$status){$verifier=new \Sand\Iam\Example\ProviderB\SandIamContextVerifier($config,static function(string $c,string $r)use($status):array{throw new \Sand\Iam\Sdk\SandIamException('SAND_IAM_AUTHENTICATION_FAILED','deny',$status);});$expect('PROVIDER_B_CONTEXT_DENIED',static fn()=>$verifier->verify('context','request-0008'));}foreach([200,500]as$status){$verifier=new \Sand\Iam\Example\ProviderB\SandIamContextVerifier($config,static function(string $c,string $r)use($status):array{throw new \Sand\Iam\Sdk\SandIamException('SAND_IAM_SDK_INVALID_RESPONSE','bad',$status);});$expect('PROVIDER_B_CONTEXT_UNAVAILABLE',static fn()=>$verifier->verify('context','request-0008'));}});
$claims=['context_id'=>'ctx-1','workload_client_id'=>10,'organization_id'=>20];
$test('pdo store hashes NUL and empty stream bodies and binds false boolean',static function()use($claims):void{foreach(["a\0b",'']as$body){$db=new FakePdo(fopen('data://text/plain,'.rawurlencode($body),'rb'));$r=(new \Sand\Iam\Example\ProviderB\PdoProcessStore($db))->process($claims,'doc-1','idem-key-1001','request-1001');if($r['content_sha256']!==hash('sha256',$body)||$r['content_bytes']!==strlen($body)||$db->auditBindings[':replayed']!==[false,PDO::PARAM_BOOL])throw new RuntimeException('stream hash or false bind');}});
$test('pdo store replay binds true and audit failure rolls back',static function()use($claims,$expect):void{$body='body';$db=new FakePdo($body);$db->existing=['id'=>7,'document_id'=>'doc-1','content_sha256'=>hash('sha256',$body),'content_bytes'=>4];$r=(new \Sand\Iam\Example\ProviderB\PdoProcessStore($db))->process($claims,'doc-1','idem-key-1002','request-1002');if(!$r['replayed']||$db->auditBindings[':replayed']!==[true,PDO::PARAM_BOOL])throw new RuntimeException('true bind');$fail=new FakePdo('body');$fail->auditFails=true;$expect('PROVIDER_B_PERSISTENCE_FAILED',static fn()=>(new \Sand\Iam\Example\ProviderB\PdoProcessStore($fail))->process($claims,'doc-1','idem-key-1003','request-1003'));if($fail->rollbacks!==1||$fail->commits!==0)throw new RuntimeException('audit did not roll back');});
$test('pdo store fails closed when stream cannot be read',static function()use($claims,$expect):void{$stream=fopen('php://temp','rb');fclose($stream);$db=new FakePdo($stream);$expect('PROVIDER_B_DOCUMENT_INVALID',static fn()=>(new \Sand\Iam\Example\ProviderB\PdoProcessStore($db))->process($claims,'doc-1','idem-key-1004','request-1004'));if($db->rollbacks!==1||$db->commits!==0)throw new RuntimeException('unreadable stream committed');});
$test('pdo store rejects live write-only stream before process or audit writes',static function()use($claims,$expect):void{$stream=fopen('/dev/null','wb');$db=new FakePdo($stream);$expect('PROVIDER_B_DOCUMENT_INVALID',static fn()=>(new \Sand\Iam\Example\ProviderB\PdoProcessStore($db))->process($claims,'doc-1','idem-key-1005','request-1005'));if($db->processWrites!==0||$db->audits!==0||$db->rollbacks!==1||$db->commits!==0)throw new RuntimeException('write-only stream reached a write');fclose($stream);});
$test('failed request codes produce one independent redacted audit without process writes',static function():void{$config=ProviderConfig::fromArray(['SAND_IAM_BASE_URL'=>'https://iam.example','SAND_IAM_ORGANIZATION_CODE'=>'org-a','SAND_IAM_APPLICATION_CODE'=>'app-a','PROVIDER_B_DATABASE_DSN'=>'pgsql:host=example']);foreach(['PROVIDER_B_CONTEXT_DENIED','PROVIDER_B_CONTEXT_CLAIMS_INVALID','PROVIDER_B_CONTEXT_UNAVAILABLE','PROVIDER_B_INVALID_REQUEST']as$code){$db=new FakePdo('body');(new \Sand\Iam\Example\ProviderB\FailureAuditWriter($config,static fn()=>$db))->write('doc-1','context','idem-key-1006','request-1006',$code,403);if($db->audits!==1||$db->processWrites!==0)throw new RuntimeException('failed audit contract');}});
$test('route input early failures retain audit eligibility and never reach store',static function()use($expect):void{$config=ProviderConfig::fromArray(['SAND_IAM_BASE_URL'=>'https://iam.example','SAND_IAM_ORGANIZATION_CODE'=>'org-a','SAND_IAM_APPLICATION_CODE'=>'app-a','PROVIDER_B_DATABASE_DSN'=>'pgsql:host=example']);$cases=[['{','ctx','idem-key-1007',400],['{"unexpected":true}','ctx','idem-key-1007',400],['{}','','idem-key-1007',401],['{}','ctx','',401]];foreach($cases as[$raw,$context,$key,$status]){$db=new FakePdo('body');try{\Sand\Iam\Example\ProviderB\RouteInput::validate($raw,$context,$key);}catch(ProviderException $e){(new \Sand\Iam\Example\ProviderB\FailureAuditWriter($config,static fn()=>$db))->write('doc-1',$context,$key,'request-1007',$e->errorCode,$e->httpStatus);if($e->httpStatus!==$status||$db->audits!==1||$db->processWrites!==0)throw new RuntimeException('early failure audit');continue;}throw new RuntimeException('early input accepted');}});
$test('failure audit exception preserves original rejection and writes no process',static function():void{$config=ProviderConfig::fromArray(['SAND_IAM_BASE_URL'=>'https://iam.example','SAND_IAM_ORGANIZATION_CODE'=>'org-a','SAND_IAM_APPLICATION_CODE'=>'app-a','PROVIDER_B_DATABASE_DSN'=>'pgsql:host=example']);$db=new FakePdo('body');$db->auditFails=true;$status=401;(new \Sand\Iam\Example\ProviderB\FailureAuditWriter($config,static fn()=>$db))->write('doc-1','ctx','idem-key-1008','request-1008','PROVIDER_B_AUTHORIZATION_HEADERS_REQUIRED',$status);if($status!==401||$db->processWrites!==0)throw new RuntimeException('audit altered rejection');});
$test('trailing newline identifiers reject before verification or persistence', static function () use ($expect): void {
    foreach ([0 => 'PROVIDER_B_INVALID_DOCUMENT_ID', 2 => 'PROVIDER_B_INVALID_IDEMPOTENCY_KEY', 3 => 'PROVIDER_B_INVALID_REQUEST_ID'] as $index => $code) {
        $store = new MemoryStore();
        $verifier = new RevocableVerifier();
        $app = new ProviderApplication($verifier, $store);
        $args = ['doc-1', 'context', 'idem-key-0001', 'request-0001'];
        $args[$index] .= "\n";
        $expect($code, static fn () => $app->process(...$args));
        if ($store->calls !== 0 || $store->effects !== 0 || $verifier->calls !== 0) throw new RuntimeException('invalid identifier reached authorization or persistence');
    }
});
echo"Provider B offline tests: passed=$passed/$total; failed=".($total-$passed).PHP_EOL;
exit($passed===$total?0:1);
