-- SandIAM P0 PostgreSQL schema (v0.1.0).
-- Authoritative source for package install and upgrade from the empty 0.1.0 baseline.
-- This script owns only sand_iam_* objects.
BEGIN;

CREATE TABLE IF NOT EXISTS sand_iam_organization (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(64) NOT NULL,
    name varchar(128) NOT NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_organization_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS sand_iam_application (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL REFERENCES sand_iam_organization(id) ON DELETE RESTRICT,
    code varchar(64) NOT NULL,
    name varchar(128) NOT NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_application_organization_code UNIQUE (organization_id, code)
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_application_organization_id ON sand_iam_application (organization_id);

CREATE TABLE IF NOT EXISTS sand_iam_environment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL REFERENCES sand_iam_application(id) ON DELETE RESTRICT,
    code varchar(64) NOT NULL,
    name varchar(128) NOT NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_environment_application_code UNIQUE (application_id, code)
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_environment_application_id ON sand_iam_environment (application_id);

CREATE TABLE IF NOT EXISTS sand_iam_workload_client (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment_id bigint NOT NULL REFERENCES sand_iam_environment(id) ON DELETE RESTRICT,
    code varchar(64) NOT NULL,
    name varchar(128) NOT NULL,
    audience varchar(128) NOT NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_workload_client_environment_code UNIQUE (environment_id, code)
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_workload_client_environment_id ON sand_iam_workload_client (environment_id);

CREATE TABLE IF NOT EXISTS sand_iam_credential (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workload_client_id bigint NOT NULL REFERENCES sand_iam_workload_client(id) ON DELETE RESTRICT,
    name varchar(128) NOT NULL,
    key_prefix varchar(32) NOT NULL,
    secret_hash varchar(255) NOT NULL,
    expire_time timestamp(0) without time zone NULL,
    revoked_time timestamp(0) without time zone NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_credential_key_prefix UNIQUE (key_prefix),
    CONSTRAINT uk_sand_iam_credential_secret_hash UNIQUE (secret_hash)
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_credential_client_active ON sand_iam_credential (workload_client_id, status, expire_time);

CREATE TABLE IF NOT EXISTS sand_iam_service (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(64) NOT NULL,
    name varchar(128) NOT NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_service_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS sand_iam_service_action (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id bigint NOT NULL REFERENCES sand_iam_service(id) ON DELETE RESTRICT,
    code varchar(96) NOT NULL,
    name varchar(128) NOT NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_service_action_service_code UNIQUE (service_id, code)
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_service_action_service_id ON sand_iam_service_action (service_id);

CREATE TABLE IF NOT EXISTS sand_iam_service_grant (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workload_client_id bigint NOT NULL REFERENCES sand_iam_workload_client(id) ON DELETE RESTRICT,
    service_action_id bigint NOT NULL REFERENCES sand_iam_service_action(id) ON DELETE RESTRICT,
    audience varchar(128) NOT NULL,
    quota_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
    data_class varchar(32) NOT NULL DEFAULT 'internal',
    network_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
    expire_time timestamp(0) without time zone NULL,
    revoked_time timestamp(0) without time zone NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_service_grant_client_action_audience UNIQUE (workload_client_id, service_action_id, audience)
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_service_grant_action_active ON sand_iam_service_grant (service_action_id, status, expire_time);

CREATE TABLE IF NOT EXISTS sand_iam_identity (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL REFERENCES sand_iam_application(id) ON DELETE RESTRICT,
    code varchar(64) NOT NULL,
    display_name varchar(128) NOT NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_identity_application_code UNIQUE (application_id, code)
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_identity_application_id ON sand_iam_identity (application_id);

CREATE TABLE IF NOT EXISTS sand_iam_identity_binding (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_id bigint NOT NULL REFERENCES sand_iam_identity(id) ON DELETE RESTRICT,
    provider_code varchar(64) NOT NULL,
    subject varchar(191) NOT NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_identity_binding_provider_subject UNIQUE (provider_code, subject)
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_identity_binding_identity_id ON sand_iam_identity_binding (identity_id);

CREATE TABLE IF NOT EXISTS sand_iam_user_type (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL REFERENCES sand_iam_application(id) ON DELETE RESTRICT,
    code varchar(64) NOT NULL,
    name varchar(128) NOT NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_user_type_application_code UNIQUE (application_id, code)
);

CREATE TABLE IF NOT EXISTS sand_iam_identity_user_type (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_id bigint NOT NULL REFERENCES sand_iam_identity(id) ON DELETE RESTRICT,
    user_type_id bigint NOT NULL REFERENCES sand_iam_user_type(id) ON DELETE RESTRICT,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_identity_user_type_identity_type UNIQUE (identity_id, user_type_id)
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_identity_user_type_type_id ON sand_iam_identity_user_type (user_type_id);

CREATE TABLE IF NOT EXISTS sand_iam_role (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL REFERENCES sand_iam_application(id) ON DELETE RESTRICT,
    code varchar(64) NOT NULL,
    name varchar(128) NOT NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_role_application_code UNIQUE (application_id, code)
);

CREATE TABLE IF NOT EXISTS sand_iam_identity_role (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_id bigint NOT NULL REFERENCES sand_iam_identity(id) ON DELETE RESTRICT,
    role_id bigint NOT NULL REFERENCES sand_iam_role(id) ON DELETE RESTRICT,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_identity_role_identity_role UNIQUE (identity_id, role_id)
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_identity_role_role_id ON sand_iam_identity_role (role_id);

CREATE TABLE IF NOT EXISTS sand_iam_resource (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL REFERENCES sand_iam_application(id) ON DELETE RESTRICT,
    code varchar(64) NOT NULL,
    name varchar(128) NOT NULL,
    owner_field varchar(64) NULL,
    organization_field varchar(64) NULL,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_resource_application_code UNIQUE (application_id, code)
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_resource_application_id ON sand_iam_resource (application_id);

CREATE TABLE IF NOT EXISTS sand_iam_policy (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL REFERENCES sand_iam_application(id) ON DELETE RESTRICT,
    resource_id bigint NOT NULL REFERENCES sand_iam_resource(id) ON DELETE RESTRICT,
    role_id bigint NULL REFERENCES sand_iam_role(id) ON DELETE RESTRICT,
    identity_id bigint NULL REFERENCES sand_iam_identity(id) ON DELETE RESTRICT,
    action varchar(64) NOT NULL,
    effect varchar(8) NOT NULL,
    condition jsonb NOT NULL DEFAULT '{}'::jsonb,
    scope jsonb NOT NULL DEFAULT '{}'::jsonb,
    priority integer NOT NULL DEFAULT 100,
    state varchar(16) NOT NULL DEFAULT 'draft',
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT ck_sand_iam_policy_subject CHECK ((role_id IS NOT NULL AND identity_id IS NULL) OR (role_id IS NULL AND identity_id IS NOT NULL)),
    CONSTRAINT ck_sand_iam_policy_effect CHECK (effect IN ('allow', 'deny')),
    CONSTRAINT ck_sand_iam_policy_state CHECK (state IN ('draft', 'published', 'revoked'))
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_policy_resource_action_state ON sand_iam_policy (resource_id, action, state, status, priority);
CREATE INDEX IF NOT EXISTS idx_sand_iam_policy_role_id ON sand_iam_policy (role_id) WHERE role_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_sand_iam_policy_identity_id ON sand_iam_policy (identity_id) WHERE identity_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS sand_iam_admin_organization_grant (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id bigint NOT NULL,
    organization_id bigint NOT NULL REFERENCES sand_iam_organization(id) ON DELETE RESTRICT,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_admin_organization_grant_admin_organization UNIQUE (admin_user_id, organization_id)
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_admin_organization_grant_organization_active ON sand_iam_admin_organization_grant (organization_id, status);

CREATE TABLE IF NOT EXISTS sand_iam_audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_type varchar(32) NOT NULL,
    actor_ref varchar(128) NOT NULL,
    organization_id bigint NULL REFERENCES sand_iam_organization(id) ON DELETE RESTRICT,
    application_id bigint NULL REFERENCES sand_iam_application(id) ON DELETE RESTRICT,
    action varchar(96) NOT NULL,
    resource_type varchar(64) NOT NULL,
    resource_id bigint NULL,
    outcome varchar(16) NOT NULL CHECK (outcome IN ('allowed', 'denied', 'succeeded', 'failed')),
    request_id varchar(96) NOT NULL,
    context jsonb NOT NULL DEFAULT '{}'::jsonb,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sand_iam_audit_log_request_action UNIQUE (request_id, action)
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_audit_log_application_time ON sand_iam_audit_log (application_id, create_time);
CREATE INDEX IF NOT EXISTS idx_sand_iam_audit_log_action_outcome_time ON sand_iam_audit_log (action, outcome, create_time);

COMMIT;
