-- SandIAM P0 PostgreSQL upgrade baseline (v0.1.0).
-- P0 is the first schema-bearing package release, so an already-installed P0
-- package requires no DDL during same-version lifecycle verification. Every
-- later schema change must append an immutable migration before this script is
-- changed for a released version.
BEGIN;
COMMIT;

-- IAM-04 authorization and backend-organization delegation (v0.1.1).
BEGIN;

CREATE TABLE IF NOT EXISTS sand_iam_admin_organization_grant (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id bigint NOT NULL,
    organization_id bigint NOT NULL REFERENCES sand_iam_organization(id) ON DELETE RESTRICT,
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    created_by bigint NULL,
    updated_by bigint NULL,
    create_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delete_time timestamp(0) without time zone NULL,
    CONSTRAINT uk_sand_iam_admin_organization_grant_admin_organization UNIQUE (admin_user_id, organization_id)
);
CREATE INDEX IF NOT EXISTS idx_sand_iam_admin_organization_grant_organization_active ON sand_iam_admin_organization_grant (organization_id, status);

COMMIT;
